// AUTO-GENERATED by tools/gen_mp_addsub_bits_stage1.py - do not edit.
#ifndef ADD_MOD_UNROLL_4096B_BODY_DEFINED
#define ADD_MOD_UNROLL_4096B_BODY_DEFINED
static inline void add_mod_unroll_4096b_body(uint *r, const uint *a, const uint *b, const uint *N) {
    ulong carry_add = 0ul;
    ulong carry_sub = 1ul;
    {
        ulong sum = (ulong)a[0] + (ulong)b[0] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[0]) + carry_sub;
        carry_sub = temp >> 32;
        r[0] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[1] + (ulong)b[1] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[1]) + carry_sub;
        carry_sub = temp >> 32;
        r[1] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[2] + (ulong)b[2] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[2]) + carry_sub;
        carry_sub = temp >> 32;
        r[2] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[3] + (ulong)b[3] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[3]) + carry_sub;
        carry_sub = temp >> 32;
        r[3] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[4] + (ulong)b[4] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[4]) + carry_sub;
        carry_sub = temp >> 32;
        r[4] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[5] + (ulong)b[5] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[5]) + carry_sub;
        carry_sub = temp >> 32;
        r[5] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[6] + (ulong)b[6] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[6]) + carry_sub;
        carry_sub = temp >> 32;
        r[6] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[7] + (ulong)b[7] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[7]) + carry_sub;
        carry_sub = temp >> 32;
        r[7] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[8] + (ulong)b[8] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[8]) + carry_sub;
        carry_sub = temp >> 32;
        r[8] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[9] + (ulong)b[9] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[9]) + carry_sub;
        carry_sub = temp >> 32;
        r[9] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[10] + (ulong)b[10] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[10]) + carry_sub;
        carry_sub = temp >> 32;
        r[10] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[11] + (ulong)b[11] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[11]) + carry_sub;
        carry_sub = temp >> 32;
        r[11] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[12] + (ulong)b[12] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[12]) + carry_sub;
        carry_sub = temp >> 32;
        r[12] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[13] + (ulong)b[13] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[13]) + carry_sub;
        carry_sub = temp >> 32;
        r[13] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[14] + (ulong)b[14] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[14]) + carry_sub;
        carry_sub = temp >> 32;
        r[14] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[15] + (ulong)b[15] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[15]) + carry_sub;
        carry_sub = temp >> 32;
        r[15] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[16] + (ulong)b[16] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[16]) + carry_sub;
        carry_sub = temp >> 32;
        r[16] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[17] + (ulong)b[17] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[17]) + carry_sub;
        carry_sub = temp >> 32;
        r[17] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[18] + (ulong)b[18] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[18]) + carry_sub;
        carry_sub = temp >> 32;
        r[18] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[19] + (ulong)b[19] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[19]) + carry_sub;
        carry_sub = temp >> 32;
        r[19] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[20] + (ulong)b[20] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[20]) + carry_sub;
        carry_sub = temp >> 32;
        r[20] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[21] + (ulong)b[21] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[21]) + carry_sub;
        carry_sub = temp >> 32;
        r[21] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[22] + (ulong)b[22] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[22]) + carry_sub;
        carry_sub = temp >> 32;
        r[22] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[23] + (ulong)b[23] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[23]) + carry_sub;
        carry_sub = temp >> 32;
        r[23] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[24] + (ulong)b[24] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[24]) + carry_sub;
        carry_sub = temp >> 32;
        r[24] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[25] + (ulong)b[25] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[25]) + carry_sub;
        carry_sub = temp >> 32;
        r[25] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[26] + (ulong)b[26] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[26]) + carry_sub;
        carry_sub = temp >> 32;
        r[26] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[27] + (ulong)b[27] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[27]) + carry_sub;
        carry_sub = temp >> 32;
        r[27] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[28] + (ulong)b[28] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[28]) + carry_sub;
        carry_sub = temp >> 32;
        r[28] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[29] + (ulong)b[29] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[29]) + carry_sub;
        carry_sub = temp >> 32;
        r[29] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[30] + (ulong)b[30] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[30]) + carry_sub;
        carry_sub = temp >> 32;
        r[30] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[31] + (ulong)b[31] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[31]) + carry_sub;
        carry_sub = temp >> 32;
        r[31] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[32] + (ulong)b[32] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[32]) + carry_sub;
        carry_sub = temp >> 32;
        r[32] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[33] + (ulong)b[33] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[33]) + carry_sub;
        carry_sub = temp >> 32;
        r[33] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[34] + (ulong)b[34] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[34]) + carry_sub;
        carry_sub = temp >> 32;
        r[34] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[35] + (ulong)b[35] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[35]) + carry_sub;
        carry_sub = temp >> 32;
        r[35] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[36] + (ulong)b[36] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[36]) + carry_sub;
        carry_sub = temp >> 32;
        r[36] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[37] + (ulong)b[37] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[37]) + carry_sub;
        carry_sub = temp >> 32;
        r[37] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[38] + (ulong)b[38] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[38]) + carry_sub;
        carry_sub = temp >> 32;
        r[38] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[39] + (ulong)b[39] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[39]) + carry_sub;
        carry_sub = temp >> 32;
        r[39] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[40] + (ulong)b[40] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[40]) + carry_sub;
        carry_sub = temp >> 32;
        r[40] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[41] + (ulong)b[41] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[41]) + carry_sub;
        carry_sub = temp >> 32;
        r[41] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[42] + (ulong)b[42] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[42]) + carry_sub;
        carry_sub = temp >> 32;
        r[42] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[43] + (ulong)b[43] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[43]) + carry_sub;
        carry_sub = temp >> 32;
        r[43] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[44] + (ulong)b[44] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[44]) + carry_sub;
        carry_sub = temp >> 32;
        r[44] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[45] + (ulong)b[45] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[45]) + carry_sub;
        carry_sub = temp >> 32;
        r[45] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[46] + (ulong)b[46] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[46]) + carry_sub;
        carry_sub = temp >> 32;
        r[46] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[47] + (ulong)b[47] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[47]) + carry_sub;
        carry_sub = temp >> 32;
        r[47] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[48] + (ulong)b[48] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[48]) + carry_sub;
        carry_sub = temp >> 32;
        r[48] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[49] + (ulong)b[49] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[49]) + carry_sub;
        carry_sub = temp >> 32;
        r[49] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[50] + (ulong)b[50] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[50]) + carry_sub;
        carry_sub = temp >> 32;
        r[50] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[51] + (ulong)b[51] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[51]) + carry_sub;
        carry_sub = temp >> 32;
        r[51] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[52] + (ulong)b[52] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[52]) + carry_sub;
        carry_sub = temp >> 32;
        r[52] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[53] + (ulong)b[53] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[53]) + carry_sub;
        carry_sub = temp >> 32;
        r[53] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[54] + (ulong)b[54] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[54]) + carry_sub;
        carry_sub = temp >> 32;
        r[54] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[55] + (ulong)b[55] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[55]) + carry_sub;
        carry_sub = temp >> 32;
        r[55] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[56] + (ulong)b[56] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[56]) + carry_sub;
        carry_sub = temp >> 32;
        r[56] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[57] + (ulong)b[57] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[57]) + carry_sub;
        carry_sub = temp >> 32;
        r[57] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[58] + (ulong)b[58] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[58]) + carry_sub;
        carry_sub = temp >> 32;
        r[58] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[59] + (ulong)b[59] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[59]) + carry_sub;
        carry_sub = temp >> 32;
        r[59] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[60] + (ulong)b[60] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[60]) + carry_sub;
        carry_sub = temp >> 32;
        r[60] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[61] + (ulong)b[61] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[61]) + carry_sub;
        carry_sub = temp >> 32;
        r[61] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[62] + (ulong)b[62] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[62]) + carry_sub;
        carry_sub = temp >> 32;
        r[62] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[63] + (ulong)b[63] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[63]) + carry_sub;
        carry_sub = temp >> 32;
        r[63] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[64] + (ulong)b[64] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[64]) + carry_sub;
        carry_sub = temp >> 32;
        r[64] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[65] + (ulong)b[65] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[65]) + carry_sub;
        carry_sub = temp >> 32;
        r[65] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[66] + (ulong)b[66] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[66]) + carry_sub;
        carry_sub = temp >> 32;
        r[66] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[67] + (ulong)b[67] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[67]) + carry_sub;
        carry_sub = temp >> 32;
        r[67] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[68] + (ulong)b[68] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[68]) + carry_sub;
        carry_sub = temp >> 32;
        r[68] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[69] + (ulong)b[69] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[69]) + carry_sub;
        carry_sub = temp >> 32;
        r[69] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[70] + (ulong)b[70] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[70]) + carry_sub;
        carry_sub = temp >> 32;
        r[70] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[71] + (ulong)b[71] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[71]) + carry_sub;
        carry_sub = temp >> 32;
        r[71] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[72] + (ulong)b[72] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[72]) + carry_sub;
        carry_sub = temp >> 32;
        r[72] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[73] + (ulong)b[73] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[73]) + carry_sub;
        carry_sub = temp >> 32;
        r[73] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[74] + (ulong)b[74] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[74]) + carry_sub;
        carry_sub = temp >> 32;
        r[74] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[75] + (ulong)b[75] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[75]) + carry_sub;
        carry_sub = temp >> 32;
        r[75] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[76] + (ulong)b[76] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[76]) + carry_sub;
        carry_sub = temp >> 32;
        r[76] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[77] + (ulong)b[77] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[77]) + carry_sub;
        carry_sub = temp >> 32;
        r[77] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[78] + (ulong)b[78] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[78]) + carry_sub;
        carry_sub = temp >> 32;
        r[78] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[79] + (ulong)b[79] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[79]) + carry_sub;
        carry_sub = temp >> 32;
        r[79] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[80] + (ulong)b[80] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[80]) + carry_sub;
        carry_sub = temp >> 32;
        r[80] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[81] + (ulong)b[81] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[81]) + carry_sub;
        carry_sub = temp >> 32;
        r[81] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[82] + (ulong)b[82] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[82]) + carry_sub;
        carry_sub = temp >> 32;
        r[82] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[83] + (ulong)b[83] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[83]) + carry_sub;
        carry_sub = temp >> 32;
        r[83] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[84] + (ulong)b[84] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[84]) + carry_sub;
        carry_sub = temp >> 32;
        r[84] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[85] + (ulong)b[85] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[85]) + carry_sub;
        carry_sub = temp >> 32;
        r[85] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[86] + (ulong)b[86] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[86]) + carry_sub;
        carry_sub = temp >> 32;
        r[86] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[87] + (ulong)b[87] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[87]) + carry_sub;
        carry_sub = temp >> 32;
        r[87] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[88] + (ulong)b[88] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[88]) + carry_sub;
        carry_sub = temp >> 32;
        r[88] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[89] + (ulong)b[89] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[89]) + carry_sub;
        carry_sub = temp >> 32;
        r[89] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[90] + (ulong)b[90] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[90]) + carry_sub;
        carry_sub = temp >> 32;
        r[90] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[91] + (ulong)b[91] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[91]) + carry_sub;
        carry_sub = temp >> 32;
        r[91] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[92] + (ulong)b[92] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[92]) + carry_sub;
        carry_sub = temp >> 32;
        r[92] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[93] + (ulong)b[93] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[93]) + carry_sub;
        carry_sub = temp >> 32;
        r[93] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[94] + (ulong)b[94] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[94]) + carry_sub;
        carry_sub = temp >> 32;
        r[94] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[95] + (ulong)b[95] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[95]) + carry_sub;
        carry_sub = temp >> 32;
        r[95] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[96] + (ulong)b[96] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[96]) + carry_sub;
        carry_sub = temp >> 32;
        r[96] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[97] + (ulong)b[97] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[97]) + carry_sub;
        carry_sub = temp >> 32;
        r[97] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[98] + (ulong)b[98] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[98]) + carry_sub;
        carry_sub = temp >> 32;
        r[98] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[99] + (ulong)b[99] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[99]) + carry_sub;
        carry_sub = temp >> 32;
        r[99] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[100] + (ulong)b[100] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[100]) + carry_sub;
        carry_sub = temp >> 32;
        r[100] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[101] + (ulong)b[101] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[101]) + carry_sub;
        carry_sub = temp >> 32;
        r[101] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[102] + (ulong)b[102] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[102]) + carry_sub;
        carry_sub = temp >> 32;
        r[102] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[103] + (ulong)b[103] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[103]) + carry_sub;
        carry_sub = temp >> 32;
        r[103] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[104] + (ulong)b[104] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[104]) + carry_sub;
        carry_sub = temp >> 32;
        r[104] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[105] + (ulong)b[105] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[105]) + carry_sub;
        carry_sub = temp >> 32;
        r[105] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[106] + (ulong)b[106] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[106]) + carry_sub;
        carry_sub = temp >> 32;
        r[106] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[107] + (ulong)b[107] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[107]) + carry_sub;
        carry_sub = temp >> 32;
        r[107] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[108] + (ulong)b[108] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[108]) + carry_sub;
        carry_sub = temp >> 32;
        r[108] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[109] + (ulong)b[109] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[109]) + carry_sub;
        carry_sub = temp >> 32;
        r[109] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[110] + (ulong)b[110] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[110]) + carry_sub;
        carry_sub = temp >> 32;
        r[110] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[111] + (ulong)b[111] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[111]) + carry_sub;
        carry_sub = temp >> 32;
        r[111] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[112] + (ulong)b[112] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[112]) + carry_sub;
        carry_sub = temp >> 32;
        r[112] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[113] + (ulong)b[113] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[113]) + carry_sub;
        carry_sub = temp >> 32;
        r[113] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[114] + (ulong)b[114] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[114]) + carry_sub;
        carry_sub = temp >> 32;
        r[114] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[115] + (ulong)b[115] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[115]) + carry_sub;
        carry_sub = temp >> 32;
        r[115] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[116] + (ulong)b[116] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[116]) + carry_sub;
        carry_sub = temp >> 32;
        r[116] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[117] + (ulong)b[117] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[117]) + carry_sub;
        carry_sub = temp >> 32;
        r[117] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[118] + (ulong)b[118] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[118]) + carry_sub;
        carry_sub = temp >> 32;
        r[118] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[119] + (ulong)b[119] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[119]) + carry_sub;
        carry_sub = temp >> 32;
        r[119] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[120] + (ulong)b[120] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[120]) + carry_sub;
        carry_sub = temp >> 32;
        r[120] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[121] + (ulong)b[121] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[121]) + carry_sub;
        carry_sub = temp >> 32;
        r[121] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[122] + (ulong)b[122] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[122]) + carry_sub;
        carry_sub = temp >> 32;
        r[122] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[123] + (ulong)b[123] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[123]) + carry_sub;
        carry_sub = temp >> 32;
        r[123] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[124] + (ulong)b[124] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[124]) + carry_sub;
        carry_sub = temp >> 32;
        r[124] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[125] + (ulong)b[125] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[125]) + carry_sub;
        carry_sub = temp >> 32;
        r[125] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[126] + (ulong)b[126] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[126]) + carry_sub;
        carry_sub = temp >> 32;
        r[126] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[127] + (ulong)b[127] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[127]) + carry_sub;
        carry_sub = temp >> 32;
        r[127] = (uint)temp;
    }
    if ((carry_add | carry_sub) != 0ul) {
        return;
    }
    ulong c = 0ul;
    {
        ulong s = (ulong)r[0] + (ulong)N[0] + c;
        r[0] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[1] + (ulong)N[1] + c;
        r[1] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[2] + (ulong)N[2] + c;
        r[2] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[3] + (ulong)N[3] + c;
        r[3] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[4] + (ulong)N[4] + c;
        r[4] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[5] + (ulong)N[5] + c;
        r[5] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[6] + (ulong)N[6] + c;
        r[6] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[7] + (ulong)N[7] + c;
        r[7] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[8] + (ulong)N[8] + c;
        r[8] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[9] + (ulong)N[9] + c;
        r[9] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[10] + (ulong)N[10] + c;
        r[10] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[11] + (ulong)N[11] + c;
        r[11] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[12] + (ulong)N[12] + c;
        r[12] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[13] + (ulong)N[13] + c;
        r[13] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[14] + (ulong)N[14] + c;
        r[14] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[15] + (ulong)N[15] + c;
        r[15] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[16] + (ulong)N[16] + c;
        r[16] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[17] + (ulong)N[17] + c;
        r[17] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[18] + (ulong)N[18] + c;
        r[18] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[19] + (ulong)N[19] + c;
        r[19] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[20] + (ulong)N[20] + c;
        r[20] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[21] + (ulong)N[21] + c;
        r[21] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[22] + (ulong)N[22] + c;
        r[22] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[23] + (ulong)N[23] + c;
        r[23] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[24] + (ulong)N[24] + c;
        r[24] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[25] + (ulong)N[25] + c;
        r[25] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[26] + (ulong)N[26] + c;
        r[26] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[27] + (ulong)N[27] + c;
        r[27] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[28] + (ulong)N[28] + c;
        r[28] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[29] + (ulong)N[29] + c;
        r[29] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[30] + (ulong)N[30] + c;
        r[30] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[31] + (ulong)N[31] + c;
        r[31] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[32] + (ulong)N[32] + c;
        r[32] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[33] + (ulong)N[33] + c;
        r[33] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[34] + (ulong)N[34] + c;
        r[34] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[35] + (ulong)N[35] + c;
        r[35] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[36] + (ulong)N[36] + c;
        r[36] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[37] + (ulong)N[37] + c;
        r[37] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[38] + (ulong)N[38] + c;
        r[38] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[39] + (ulong)N[39] + c;
        r[39] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[40] + (ulong)N[40] + c;
        r[40] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[41] + (ulong)N[41] + c;
        r[41] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[42] + (ulong)N[42] + c;
        r[42] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[43] + (ulong)N[43] + c;
        r[43] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[44] + (ulong)N[44] + c;
        r[44] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[45] + (ulong)N[45] + c;
        r[45] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[46] + (ulong)N[46] + c;
        r[46] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[47] + (ulong)N[47] + c;
        r[47] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[48] + (ulong)N[48] + c;
        r[48] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[49] + (ulong)N[49] + c;
        r[49] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[50] + (ulong)N[50] + c;
        r[50] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[51] + (ulong)N[51] + c;
        r[51] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[52] + (ulong)N[52] + c;
        r[52] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[53] + (ulong)N[53] + c;
        r[53] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[54] + (ulong)N[54] + c;
        r[54] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[55] + (ulong)N[55] + c;
        r[55] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[56] + (ulong)N[56] + c;
        r[56] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[57] + (ulong)N[57] + c;
        r[57] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[58] + (ulong)N[58] + c;
        r[58] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[59] + (ulong)N[59] + c;
        r[59] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[60] + (ulong)N[60] + c;
        r[60] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[61] + (ulong)N[61] + c;
        r[61] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[62] + (ulong)N[62] + c;
        r[62] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[63] + (ulong)N[63] + c;
        r[63] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[64] + (ulong)N[64] + c;
        r[64] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[65] + (ulong)N[65] + c;
        r[65] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[66] + (ulong)N[66] + c;
        r[66] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[67] + (ulong)N[67] + c;
        r[67] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[68] + (ulong)N[68] + c;
        r[68] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[69] + (ulong)N[69] + c;
        r[69] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[70] + (ulong)N[70] + c;
        r[70] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[71] + (ulong)N[71] + c;
        r[71] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[72] + (ulong)N[72] + c;
        r[72] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[73] + (ulong)N[73] + c;
        r[73] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[74] + (ulong)N[74] + c;
        r[74] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[75] + (ulong)N[75] + c;
        r[75] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[76] + (ulong)N[76] + c;
        r[76] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[77] + (ulong)N[77] + c;
        r[77] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[78] + (ulong)N[78] + c;
        r[78] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[79] + (ulong)N[79] + c;
        r[79] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[80] + (ulong)N[80] + c;
        r[80] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[81] + (ulong)N[81] + c;
        r[81] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[82] + (ulong)N[82] + c;
        r[82] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[83] + (ulong)N[83] + c;
        r[83] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[84] + (ulong)N[84] + c;
        r[84] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[85] + (ulong)N[85] + c;
        r[85] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[86] + (ulong)N[86] + c;
        r[86] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[87] + (ulong)N[87] + c;
        r[87] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[88] + (ulong)N[88] + c;
        r[88] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[89] + (ulong)N[89] + c;
        r[89] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[90] + (ulong)N[90] + c;
        r[90] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[91] + (ulong)N[91] + c;
        r[91] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[92] + (ulong)N[92] + c;
        r[92] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[93] + (ulong)N[93] + c;
        r[93] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[94] + (ulong)N[94] + c;
        r[94] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[95] + (ulong)N[95] + c;
        r[95] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[96] + (ulong)N[96] + c;
        r[96] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[97] + (ulong)N[97] + c;
        r[97] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[98] + (ulong)N[98] + c;
        r[98] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[99] + (ulong)N[99] + c;
        r[99] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[100] + (ulong)N[100] + c;
        r[100] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[101] + (ulong)N[101] + c;
        r[101] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[102] + (ulong)N[102] + c;
        r[102] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[103] + (ulong)N[103] + c;
        r[103] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[104] + (ulong)N[104] + c;
        r[104] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[105] + (ulong)N[105] + c;
        r[105] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[106] + (ulong)N[106] + c;
        r[106] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[107] + (ulong)N[107] + c;
        r[107] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[108] + (ulong)N[108] + c;
        r[108] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[109] + (ulong)N[109] + c;
        r[109] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[110] + (ulong)N[110] + c;
        r[110] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[111] + (ulong)N[111] + c;
        r[111] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[112] + (ulong)N[112] + c;
        r[112] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[113] + (ulong)N[113] + c;
        r[113] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[114] + (ulong)N[114] + c;
        r[114] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[115] + (ulong)N[115] + c;
        r[115] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[116] + (ulong)N[116] + c;
        r[116] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[117] + (ulong)N[117] + c;
        r[117] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[118] + (ulong)N[118] + c;
        r[118] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[119] + (ulong)N[119] + c;
        r[119] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[120] + (ulong)N[120] + c;
        r[120] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[121] + (ulong)N[121] + c;
        r[121] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[122] + (ulong)N[122] + c;
        r[122] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[123] + (ulong)N[123] + c;
        r[123] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[124] + (ulong)N[124] + c;
        r[124] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[125] + (ulong)N[125] + c;
        r[125] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[126] + (ulong)N[126] + c;
        r[126] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[127] + (ulong)N[127] + c;
        r[127] = (uint)s;
        c = s >> 32;
    }
}
#endif

static inline void add_mod_unroll_4096b(uint *r, const uint *a, const uint *b,
                                          const uint *N, uint limbs) {
    if (limbs == 128u) { add_mod_unroll_4096b_body(r, a, b, N); }
    (void)limbs;
}
