// AUTO-GENERATED by tools/gen_mp_addsub_bits_stage1.py - do not edit.
static inline void add_mod_unroll_384b_body(uint *r, const uint *a, const uint *b, const uint *N) {
    ulong carry_add = 0ul;
    ulong carry_sub = 1ul;
    {
        ulong sum = (ulong)a[0] + (ulong)b[0] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[0]) + carry_sub;
        carry_sub = temp >> 32;
        r[0] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[1] + (ulong)b[1] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[1]) + carry_sub;
        carry_sub = temp >> 32;
        r[1] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[2] + (ulong)b[2] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[2]) + carry_sub;
        carry_sub = temp >> 32;
        r[2] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[3] + (ulong)b[3] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[3]) + carry_sub;
        carry_sub = temp >> 32;
        r[3] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[4] + (ulong)b[4] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[4]) + carry_sub;
        carry_sub = temp >> 32;
        r[4] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[5] + (ulong)b[5] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[5]) + carry_sub;
        carry_sub = temp >> 32;
        r[5] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[6] + (ulong)b[6] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[6]) + carry_sub;
        carry_sub = temp >> 32;
        r[6] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[7] + (ulong)b[7] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[7]) + carry_sub;
        carry_sub = temp >> 32;
        r[7] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[8] + (ulong)b[8] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[8]) + carry_sub;
        carry_sub = temp >> 32;
        r[8] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[9] + (ulong)b[9] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[9]) + carry_sub;
        carry_sub = temp >> 32;
        r[9] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[10] + (ulong)b[10] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[10]) + carry_sub;
        carry_sub = temp >> 32;
        r[10] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[11] + (ulong)b[11] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[11]) + carry_sub;
        carry_sub = temp >> 32;
        r[11] = (uint)temp;
    }
    if ((carry_add | carry_sub) != 0ul) {
        return;
    }
    ulong c = 0ul;
    {
        ulong s = (ulong)r[0] + (ulong)N[0] + c;
        r[0] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[1] + (ulong)N[1] + c;
        r[1] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[2] + (ulong)N[2] + c;
        r[2] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[3] + (ulong)N[3] + c;
        r[3] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[4] + (ulong)N[4] + c;
        r[4] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[5] + (ulong)N[5] + c;
        r[5] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[6] + (ulong)N[6] + c;
        r[6] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[7] + (ulong)N[7] + c;
        r[7] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[8] + (ulong)N[8] + c;
        r[8] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[9] + (ulong)N[9] + c;
        r[9] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[10] + (ulong)N[10] + c;
        r[10] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[11] + (ulong)N[11] + c;
        r[11] = (uint)s;
        c = s >> 32;
    }
}

static inline void add_mod_unroll_384b(uint *r, const uint *a, const uint *b,
                                          const uint *N, uint limbs) {
    if (limbs == 16u) { add_mod_unroll_384b_body(r, a, b, N); }
    (void)limbs;
}
