// AUTO-GENERATED by tools/gen_mp_addsub_bits_stage1.py - do not edit.
#if defined(__AMDGCN__)
static inline int sub_mod_asm_3584b_body(uint *r, const uint *a, const uint *b, const uint *N) {
    uint br = 0u;
    asm_sub_fused_block32_priv_nofix(a + 0, b + 0, N + 0, r + 0, br, &br);
    asm_sub_fused_block32_priv_nofix(a + 32, b + 32, N + 32, r + 32, br, &br);
    asm_sub_fused_block32_priv_nofix(a + 64, b + 64, N + 64, r + 64, br, &br);
    asm_sub_fused_block16_priv_nofix(a + 96, b + 96, N + 96, r + 96, br, &br);
    if (br != 0u) {
        ulong c = 0ul;
        c = (ulong)r[0] + (ulong)N[0] + c; r[0] = (uint)c; c >>= 32;
        c = (ulong)r[1] + (ulong)N[1] + c; r[1] = (uint)c; c >>= 32;
        c = (ulong)r[2] + (ulong)N[2] + c; r[2] = (uint)c; c >>= 32;
        c = (ulong)r[3] + (ulong)N[3] + c; r[3] = (uint)c; c >>= 32;
        c = (ulong)r[4] + (ulong)N[4] + c; r[4] = (uint)c; c >>= 32;
        c = (ulong)r[5] + (ulong)N[5] + c; r[5] = (uint)c; c >>= 32;
        c = (ulong)r[6] + (ulong)N[6] + c; r[6] = (uint)c; c >>= 32;
        c = (ulong)r[7] + (ulong)N[7] + c; r[7] = (uint)c; c >>= 32;
        c = (ulong)r[8] + (ulong)N[8] + c; r[8] = (uint)c; c >>= 32;
        c = (ulong)r[9] + (ulong)N[9] + c; r[9] = (uint)c; c >>= 32;
        c = (ulong)r[10] + (ulong)N[10] + c; r[10] = (uint)c; c >>= 32;
        c = (ulong)r[11] + (ulong)N[11] + c; r[11] = (uint)c; c >>= 32;
        c = (ulong)r[12] + (ulong)N[12] + c; r[12] = (uint)c; c >>= 32;
        c = (ulong)r[13] + (ulong)N[13] + c; r[13] = (uint)c; c >>= 32;
        c = (ulong)r[14] + (ulong)N[14] + c; r[14] = (uint)c; c >>= 32;
        c = (ulong)r[15] + (ulong)N[15] + c; r[15] = (uint)c; c >>= 32;
        c = (ulong)r[16] + (ulong)N[16] + c; r[16] = (uint)c; c >>= 32;
        c = (ulong)r[17] + (ulong)N[17] + c; r[17] = (uint)c; c >>= 32;
        c = (ulong)r[18] + (ulong)N[18] + c; r[18] = (uint)c; c >>= 32;
        c = (ulong)r[19] + (ulong)N[19] + c; r[19] = (uint)c; c >>= 32;
        c = (ulong)r[20] + (ulong)N[20] + c; r[20] = (uint)c; c >>= 32;
        c = (ulong)r[21] + (ulong)N[21] + c; r[21] = (uint)c; c >>= 32;
        c = (ulong)r[22] + (ulong)N[22] + c; r[22] = (uint)c; c >>= 32;
        c = (ulong)r[23] + (ulong)N[23] + c; r[23] = (uint)c; c >>= 32;
        c = (ulong)r[24] + (ulong)N[24] + c; r[24] = (uint)c; c >>= 32;
        c = (ulong)r[25] + (ulong)N[25] + c; r[25] = (uint)c; c >>= 32;
        c = (ulong)r[26] + (ulong)N[26] + c; r[26] = (uint)c; c >>= 32;
        c = (ulong)r[27] + (ulong)N[27] + c; r[27] = (uint)c; c >>= 32;
        c = (ulong)r[28] + (ulong)N[28] + c; r[28] = (uint)c; c >>= 32;
        c = (ulong)r[29] + (ulong)N[29] + c; r[29] = (uint)c; c >>= 32;
        c = (ulong)r[30] + (ulong)N[30] + c; r[30] = (uint)c; c >>= 32;
        c = (ulong)r[31] + (ulong)N[31] + c; r[31] = (uint)c; c >>= 32;
        c = (ulong)r[32] + (ulong)N[32] + c; r[32] = (uint)c; c >>= 32;
        c = (ulong)r[33] + (ulong)N[33] + c; r[33] = (uint)c; c >>= 32;
        c = (ulong)r[34] + (ulong)N[34] + c; r[34] = (uint)c; c >>= 32;
        c = (ulong)r[35] + (ulong)N[35] + c; r[35] = (uint)c; c >>= 32;
        c = (ulong)r[36] + (ulong)N[36] + c; r[36] = (uint)c; c >>= 32;
        c = (ulong)r[37] + (ulong)N[37] + c; r[37] = (uint)c; c >>= 32;
        c = (ulong)r[38] + (ulong)N[38] + c; r[38] = (uint)c; c >>= 32;
        c = (ulong)r[39] + (ulong)N[39] + c; r[39] = (uint)c; c >>= 32;
        c = (ulong)r[40] + (ulong)N[40] + c; r[40] = (uint)c; c >>= 32;
        c = (ulong)r[41] + (ulong)N[41] + c; r[41] = (uint)c; c >>= 32;
        c = (ulong)r[42] + (ulong)N[42] + c; r[42] = (uint)c; c >>= 32;
        c = (ulong)r[43] + (ulong)N[43] + c; r[43] = (uint)c; c >>= 32;
        c = (ulong)r[44] + (ulong)N[44] + c; r[44] = (uint)c; c >>= 32;
        c = (ulong)r[45] + (ulong)N[45] + c; r[45] = (uint)c; c >>= 32;
        c = (ulong)r[46] + (ulong)N[46] + c; r[46] = (uint)c; c >>= 32;
        c = (ulong)r[47] + (ulong)N[47] + c; r[47] = (uint)c; c >>= 32;
        c = (ulong)r[48] + (ulong)N[48] + c; r[48] = (uint)c; c >>= 32;
        c = (ulong)r[49] + (ulong)N[49] + c; r[49] = (uint)c; c >>= 32;
        c = (ulong)r[50] + (ulong)N[50] + c; r[50] = (uint)c; c >>= 32;
        c = (ulong)r[51] + (ulong)N[51] + c; r[51] = (uint)c; c >>= 32;
        c = (ulong)r[52] + (ulong)N[52] + c; r[52] = (uint)c; c >>= 32;
        c = (ulong)r[53] + (ulong)N[53] + c; r[53] = (uint)c; c >>= 32;
        c = (ulong)r[54] + (ulong)N[54] + c; r[54] = (uint)c; c >>= 32;
        c = (ulong)r[55] + (ulong)N[55] + c; r[55] = (uint)c; c >>= 32;
        c = (ulong)r[56] + (ulong)N[56] + c; r[56] = (uint)c; c >>= 32;
        c = (ulong)r[57] + (ulong)N[57] + c; r[57] = (uint)c; c >>= 32;
        c = (ulong)r[58] + (ulong)N[58] + c; r[58] = (uint)c; c >>= 32;
        c = (ulong)r[59] + (ulong)N[59] + c; r[59] = (uint)c; c >>= 32;
        c = (ulong)r[60] + (ulong)N[60] + c; r[60] = (uint)c; c >>= 32;
        c = (ulong)r[61] + (ulong)N[61] + c; r[61] = (uint)c; c >>= 32;
        c = (ulong)r[62] + (ulong)N[62] + c; r[62] = (uint)c; c >>= 32;
        c = (ulong)r[63] + (ulong)N[63] + c; r[63] = (uint)c; c >>= 32;
        c = (ulong)r[64] + (ulong)N[64] + c; r[64] = (uint)c; c >>= 32;
        c = (ulong)r[65] + (ulong)N[65] + c; r[65] = (uint)c; c >>= 32;
        c = (ulong)r[66] + (ulong)N[66] + c; r[66] = (uint)c; c >>= 32;
        c = (ulong)r[67] + (ulong)N[67] + c; r[67] = (uint)c; c >>= 32;
        c = (ulong)r[68] + (ulong)N[68] + c; r[68] = (uint)c; c >>= 32;
        c = (ulong)r[69] + (ulong)N[69] + c; r[69] = (uint)c; c >>= 32;
        c = (ulong)r[70] + (ulong)N[70] + c; r[70] = (uint)c; c >>= 32;
        c = (ulong)r[71] + (ulong)N[71] + c; r[71] = (uint)c; c >>= 32;
        c = (ulong)r[72] + (ulong)N[72] + c; r[72] = (uint)c; c >>= 32;
        c = (ulong)r[73] + (ulong)N[73] + c; r[73] = (uint)c; c >>= 32;
        c = (ulong)r[74] + (ulong)N[74] + c; r[74] = (uint)c; c >>= 32;
        c = (ulong)r[75] + (ulong)N[75] + c; r[75] = (uint)c; c >>= 32;
        c = (ulong)r[76] + (ulong)N[76] + c; r[76] = (uint)c; c >>= 32;
        c = (ulong)r[77] + (ulong)N[77] + c; r[77] = (uint)c; c >>= 32;
        c = (ulong)r[78] + (ulong)N[78] + c; r[78] = (uint)c; c >>= 32;
        c = (ulong)r[79] + (ulong)N[79] + c; r[79] = (uint)c; c >>= 32;
        c = (ulong)r[80] + (ulong)N[80] + c; r[80] = (uint)c; c >>= 32;
        c = (ulong)r[81] + (ulong)N[81] + c; r[81] = (uint)c; c >>= 32;
        c = (ulong)r[82] + (ulong)N[82] + c; r[82] = (uint)c; c >>= 32;
        c = (ulong)r[83] + (ulong)N[83] + c; r[83] = (uint)c; c >>= 32;
        c = (ulong)r[84] + (ulong)N[84] + c; r[84] = (uint)c; c >>= 32;
        c = (ulong)r[85] + (ulong)N[85] + c; r[85] = (uint)c; c >>= 32;
        c = (ulong)r[86] + (ulong)N[86] + c; r[86] = (uint)c; c >>= 32;
        c = (ulong)r[87] + (ulong)N[87] + c; r[87] = (uint)c; c >>= 32;
        c = (ulong)r[88] + (ulong)N[88] + c; r[88] = (uint)c; c >>= 32;
        c = (ulong)r[89] + (ulong)N[89] + c; r[89] = (uint)c; c >>= 32;
        c = (ulong)r[90] + (ulong)N[90] + c; r[90] = (uint)c; c >>= 32;
        c = (ulong)r[91] + (ulong)N[91] + c; r[91] = (uint)c; c >>= 32;
        c = (ulong)r[92] + (ulong)N[92] + c; r[92] = (uint)c; c >>= 32;
        c = (ulong)r[93] + (ulong)N[93] + c; r[93] = (uint)c; c >>= 32;
        c = (ulong)r[94] + (ulong)N[94] + c; r[94] = (uint)c; c >>= 32;
        c = (ulong)r[95] + (ulong)N[95] + c; r[95] = (uint)c; c >>= 32;
        c = (ulong)r[96] + (ulong)N[96] + c; r[96] = (uint)c; c >>= 32;
        c = (ulong)r[97] + (ulong)N[97] + c; r[97] = (uint)c; c >>= 32;
        c = (ulong)r[98] + (ulong)N[98] + c; r[98] = (uint)c; c >>= 32;
        c = (ulong)r[99] + (ulong)N[99] + c; r[99] = (uint)c; c >>= 32;
        c = (ulong)r[100] + (ulong)N[100] + c; r[100] = (uint)c; c >>= 32;
        c = (ulong)r[101] + (ulong)N[101] + c; r[101] = (uint)c; c >>= 32;
        c = (ulong)r[102] + (ulong)N[102] + c; r[102] = (uint)c; c >>= 32;
        c = (ulong)r[103] + (ulong)N[103] + c; r[103] = (uint)c; c >>= 32;
        c = (ulong)r[104] + (ulong)N[104] + c; r[104] = (uint)c; c >>= 32;
        c = (ulong)r[105] + (ulong)N[105] + c; r[105] = (uint)c; c >>= 32;
        c = (ulong)r[106] + (ulong)N[106] + c; r[106] = (uint)c; c >>= 32;
        c = (ulong)r[107] + (ulong)N[107] + c; r[107] = (uint)c; c >>= 32;
        c = (ulong)r[108] + (ulong)N[108] + c; r[108] = (uint)c; c >>= 32;
        c = (ulong)r[109] + (ulong)N[109] + c; r[109] = (uint)c; c >>= 32;
        c = (ulong)r[110] + (ulong)N[110] + c; r[110] = (uint)c; c >>= 32;
        c = (ulong)r[111] + (ulong)N[111] + c; r[111] = (uint)c; c >>= 32;
    }
    return br != 0u ? 1 : 0;
}

#endif
#if !defined(__AMDGCN__)
#ifndef SUB_MOD_UNROLL_3584B_BODY_DEFINED
#define SUB_MOD_UNROLL_3584B_BODY_DEFINED
static inline int sub_mod_unroll_3584b_body(uint *r, const uint *a, const uint *b, const uint *N) {
    ulong br = 0ul;
    #pragma unroll
    for (uint blk = 0u; blk < 3u; ++blk) {
        uint off = blk * 32u;
        #pragma unroll 32
        for (uint j = 0u; j < 32u; ++j) {
            uint i = off + j;
            ulong av = (ulong)a[i];
            ulong bv = (ulong)b[i];
            ulong w = av - bv - br;
            r[i] = (uint)w;
            br = (av < bv + br) ? 1ul : 0ul;
        }
    }
    { uint off = 3 * 32u;
        { uint i = off + 0;
            ulong av = (ulong)a[i];
            ulong bv = (ulong)b[i];
            ulong w = av - bv - br;
            r[i] = (uint)w;
            br = (av < bv + br) ? 1ul : 0ul; }
        { uint i = off + 1;
            ulong av = (ulong)a[i];
            ulong bv = (ulong)b[i];
            ulong w = av - bv - br;
            r[i] = (uint)w;
            br = (av < bv + br) ? 1ul : 0ul; }
        { uint i = off + 2;
            ulong av = (ulong)a[i];
            ulong bv = (ulong)b[i];
            ulong w = av - bv - br;
            r[i] = (uint)w;
            br = (av < bv + br) ? 1ul : 0ul; }
        { uint i = off + 3;
            ulong av = (ulong)a[i];
            ulong bv = (ulong)b[i];
            ulong w = av - bv - br;
            r[i] = (uint)w;
            br = (av < bv + br) ? 1ul : 0ul; }
        { uint i = off + 4;
            ulong av = (ulong)a[i];
            ulong bv = (ulong)b[i];
            ulong w = av - bv - br;
            r[i] = (uint)w;
            br = (av < bv + br) ? 1ul : 0ul; }
        { uint i = off + 5;
            ulong av = (ulong)a[i];
            ulong bv = (ulong)b[i];
            ulong w = av - bv - br;
            r[i] = (uint)w;
            br = (av < bv + br) ? 1ul : 0ul; }
        { uint i = off + 6;
            ulong av = (ulong)a[i];
            ulong bv = (ulong)b[i];
            ulong w = av - bv - br;
            r[i] = (uint)w;
            br = (av < bv + br) ? 1ul : 0ul; }
        { uint i = off + 7;
            ulong av = (ulong)a[i];
            ulong bv = (ulong)b[i];
            ulong w = av - bv - br;
            r[i] = (uint)w;
            br = (av < bv + br) ? 1ul : 0ul; }
        { uint i = off + 8;
            ulong av = (ulong)a[i];
            ulong bv = (ulong)b[i];
            ulong w = av - bv - br;
            r[i] = (uint)w;
            br = (av < bv + br) ? 1ul : 0ul; }
        { uint i = off + 9;
            ulong av = (ulong)a[i];
            ulong bv = (ulong)b[i];
            ulong w = av - bv - br;
            r[i] = (uint)w;
            br = (av < bv + br) ? 1ul : 0ul; }
        { uint i = off + 10;
            ulong av = (ulong)a[i];
            ulong bv = (ulong)b[i];
            ulong w = av - bv - br;
            r[i] = (uint)w;
            br = (av < bv + br) ? 1ul : 0ul; }
        { uint i = off + 11;
            ulong av = (ulong)a[i];
            ulong bv = (ulong)b[i];
            ulong w = av - bv - br;
            r[i] = (uint)w;
            br = (av < bv + br) ? 1ul : 0ul; }
        { uint i = off + 12;
            ulong av = (ulong)a[i];
            ulong bv = (ulong)b[i];
            ulong w = av - bv - br;
            r[i] = (uint)w;
            br = (av < bv + br) ? 1ul : 0ul; }
        { uint i = off + 13;
            ulong av = (ulong)a[i];
            ulong bv = (ulong)b[i];
            ulong w = av - bv - br;
            r[i] = (uint)w;
            br = (av < bv + br) ? 1ul : 0ul; }
        { uint i = off + 14;
            ulong av = (ulong)a[i];
            ulong bv = (ulong)b[i];
            ulong w = av - bv - br;
            r[i] = (uint)w;
            br = (av < bv + br) ? 1ul : 0ul; }
        { uint i = off + 15;
            ulong av = (ulong)a[i];
            ulong bv = (ulong)b[i];
            ulong w = av - bv - br;
            r[i] = (uint)w;
            br = (av < bv + br) ? 1ul : 0ul; }
    }
    if (br != 0ul) {
        ulong c = 0ul;
    #pragma unroll 32
    for (uint i = 0u; i < 112u; ++i) {
        ulong s = (ulong)r[i] + (ulong)N[i] + c;
        r[i] = (uint)s;
        c = s >> 32;
    }
        return 1;
    }
    return 0;
}
#endif

#endif
#if defined(__AMDGCN__)
static inline int sub_mod_asm_3584b(uint *r, const uint *a, const uint *b,
                                      const uint *N, uint limbs) {
    if (limbs == 112u) { return sub_mod_asm_3584b_body(r, a, b, N); }
    return 0;
}
#else
static inline int sub_mod_asm_3584b(uint *r, const uint *a, const uint *b,
                                      const uint *N, uint limbs) {
    if (limbs == 112u) { return sub_mod_unroll_3584b_body(r, a, b, N); }
    return 0;
}
#endif
