// AUTO-GENERATED by tools/gen_mp_addsub_bits_stage1.py - do not edit.
static inline void add_mod_asm_256b_body(uint *r, const uint *a, const uint *b, const uint *N) {
    uint ca = 0u, cs = 1u;
    asm_fused_block8_priv(a, b, N, r, ca, cs, &ca, &cs);
}

static inline void add_mod_unroll_256b_body(uint *r, const uint *a, const uint *b, const uint *N) {
    ulong carry_add = 0ul;
    ulong carry_sub = 1ul;
    {
        ulong sum = (ulong)a[0] + (ulong)b[0] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[0]) + carry_sub;
        carry_sub = temp >> 32;
        r[0] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[1] + (ulong)b[1] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[1]) + carry_sub;
        carry_sub = temp >> 32;
        r[1] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[2] + (ulong)b[2] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[2]) + carry_sub;
        carry_sub = temp >> 32;
        r[2] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[3] + (ulong)b[3] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[3]) + carry_sub;
        carry_sub = temp >> 32;
        r[3] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[4] + (ulong)b[4] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[4]) + carry_sub;
        carry_sub = temp >> 32;
        r[4] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[5] + (ulong)b[5] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[5]) + carry_sub;
        carry_sub = temp >> 32;
        r[5] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[6] + (ulong)b[6] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[6]) + carry_sub;
        carry_sub = temp >> 32;
        r[6] = (uint)temp;
    }
    {
        ulong sum = (ulong)a[7] + (ulong)b[7] + carry_add;
        carry_add = sum >> 32;
        ulong temp = (ulong)(uint)sum + (ulong)(~N[7]) + carry_sub;
        carry_sub = temp >> 32;
        r[7] = (uint)temp;
    }
    if ((carry_add | carry_sub) != 0ul) {
        return;
    }
    ulong c = 0ul;
    {
        ulong s = (ulong)r[0] + (ulong)N[0] + c;
        r[0] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[1] + (ulong)N[1] + c;
        r[1] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[2] + (ulong)N[2] + c;
        r[2] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[3] + (ulong)N[3] + c;
        r[3] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[4] + (ulong)N[4] + c;
        r[4] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[5] + (ulong)N[5] + c;
        r[5] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[6] + (ulong)N[6] + c;
        r[6] = (uint)s;
        c = s >> 32;
    }
    {
        ulong s = (ulong)r[7] + (ulong)N[7] + c;
        r[7] = (uint)s;
        c = s >> 32;
    }
}

#if defined(__AMDGCN__)
static inline void add_mod_asm_256b(uint *r, const uint *a, const uint *b,
                                       const uint *N, uint limbs) {
    if (limbs == 8u) { add_mod_asm_256b_body(r, a, b, N); }
    (void)limbs;
}
#else
static inline void add_mod_asm_256b(uint *r, const uint *a, const uint *b,
                                       const uint *N, uint limbs) {
    if (limbs == 8u) { add_mod_unroll_256b_body(r, a, b, N); }
    (void)limbs;
}
#endif
