// Correct mont_mul for 2048-bit — direct 64x64 convolution + reduce.
// Product computed in 128-limb T, then reduced in-place.
// AUTO-GENERATED by tools/gen_mont_karatsuba.py - do not edit.

////////////////////////////////////////////////////////////////////////////
//  Montgomery mul — CIOS interleaved (t[66], identical to unroll_2048b)
////////////////////////////////////////////////////////////////////////////
static inline void mont_mul_karatsuba_2048b(uint *out, const uint *a, const uint *b,
                                             const uint *N, uint np0, uint limbs) {
    uint t[66u];
    for (uint i=0u;i<66u;++i) t[i]=0u;
    uint B[64u];
    for (uint j=0u;j<64u;++j) B[j]=b[j];
    for (uint i=0u;i<64u;++i) {
        uint ai=a[i]; ulong carry=0ul;
        for (uint j=0u;j<64u;++j) { ulong uv=(ulong)t[j]+(ulong)ai*(ulong)B[j]+carry; t[j]=(uint)uv; carry=uv>>32; }
        ulong top=(ulong)t[64u]+carry; t[64u]=(uint)top; t[65u]=(uint)(top>>32);
        uint m=(uint)((ulong)t[0]*(ulong)np0); carry=0ul;
        for (uint j=0u;j<64u;++j) { ulong uv=(ulong)t[j]+(ulong)m*(ulong)N[j]+carry; if(j>0u) t[j-1u]=(uint)uv; carry=uv>>32; }
        top=(ulong)t[64u]+carry; t[64u-1u]=(uint)top; top=(ulong)t[65u]+(top>>32); t[64u]=(uint)top; t[65u]=(uint)(top>>32);
    }
    ulong borrow=0ul; uint D[64u];
    for (uint i=0u;i<64u;++i) { ulong tv=(ulong)t[i],nv=(ulong)N[i]; ulong w=tv-nv-borrow; D[i]=(uint)w; borrow=(tv<nv+borrow)?1ul:0ul; }
    uint need_sub=(t[64u]|t[65u])!=0u?1u:0u; need_sub=(borrow==0u)?1u:need_sub; uint mask=0u-need_sub;
    for (uint i=0u;i<64u;++i) out[i]=(D[i]&mask)|(t[i]&~mask);
    (void)limbs;
}

static inline void mont_sqr_karatsuba_2048b(uint *out, const uint *a, const uint *N, uint np0, uint limbs) {
    mont_mul_karatsuba_2048b(out, a, a, N, np0, limbs);
}

////////////////////////////////////////////////////////////////////////////
//  LDS cooperative variant (4 threads)
//  Each thread computes one 32x32 sub-product. Master assembles + reduces.
////////////////////////////////////////////////////////////////////////////

static inline void mont_mul_stage1_karatsuba_2048_coop(
    uint *out, const uint *a, const uint *b, const uint *N,
    __local uint *lds, uint lid)
{
    __local uint *p_lo  = lds;             // 64 uints
    __local uint *p_ma  = lds + 64u;        // 64 uints
    __local uint *p_mb  = lds + 128u;       // 64 uints
    __local uint *p_hi  = lds + 192u;       // 64 uints

    // Thread 0: p_lo = a0*b0
    if (lid == 0u) {
        uint buf[64u];
        for (uint i = 0u; i < 64u; ++i) buf[i] = 0u;
        for (uint i = 0u; i < 32u; ++i) {
            ulong carry = 0ul; uint ai = a[i];
            for (uint j = 0u; j < 32u; ++j) {
                ulong uv = (ulong)buf[i + j] + (ulong)ai * (ulong)b[j] + carry;
                buf[i + j] = (uint)uv; carry = uv >> 32;
            }
        }
        for (uint i = 0u; i < 64u; ++i) p_lo[i] = buf[i];
    }
    // Thread 1: p_ma = a0*b1
    if (lid == 1u) {
        uint buf[64u];
        for (uint i = 0u; i < 64u; ++i) buf[i] = 0u;
        for (uint i = 0u; i < 32u; ++i) {
            ulong carry = 0ul; uint ai = a[i];
            for (uint j = 0u; j < 32u; ++j) {
                ulong uv = (ulong)buf[i + j] + (ulong)ai * (ulong)b[32u + j] + carry;
                buf[i + j] = (uint)uv; carry = uv >> 32;
            }
        }
        for (uint i = 0u; i < 64u; ++i) p_ma[i] = buf[i];
    }
    // Thread 2: p_mb = a1*b0
    if (lid == 2u) {
        uint buf[64u];
        for (uint i = 0u; i < 64u; ++i) buf[i] = 0u;
        for (uint i = 0u; i < 32u; ++i) {
            ulong carry = 0ul; uint ai = a[32u + i];
            for (uint j = 0u; j < 32u; ++j) {
                ulong uv = (ulong)buf[i + j] + (ulong)ai * (ulong)b[j] + carry;
                buf[i + j] = (uint)uv; carry = uv >> 32;
            }
        }
        for (uint i = 0u; i < 64u; ++i) p_mb[i] = buf[i];
    }
    // Thread 3: p_hi = a1*b1
    if (lid == 3u) {
        uint buf[64u];
        for (uint i = 0u; i < 64u; ++i) buf[i] = 0u;
        for (uint i = 0u; i < 32u; ++i) {
            ulong carry = 0ul; uint ai = a[32u + i];
            for (uint j = 0u; j < 32u; ++j) {
                ulong uv = (ulong)buf[i + j] + (ulong)ai * (ulong)b[32u + j] + carry;
                buf[i + j] = (uint)uv; carry = uv >> 32;
            }
        }
        for (uint i = 0u; i < 64u; ++i) p_hi[i] = buf[i];
    }
    barrier(CLK_LOCAL_MEM_FENCE);

    // Master: assemble into T[128] = lo + (ma+mb)*2^1024 + hi*2^2048
    if (lid == 0u) {
        uint lo[64u], ma[64u], mb[64u], hi[64u];
        for (uint i = 0u; i < 64u; ++i) {
            lo[i] = p_lo[i]; ma[i] = p_ma[i]; mb[i] = p_mb[i]; hi[i] = p_hi[i];
        }

        uint T[128u];
        for (uint i = 0u; i < 128u; ++i) T[i] = 0u;

        // T += lo at offset 0
        for (uint i = 0u; i < 64u; ++i) T[i] = lo[i];

        // T += ma at offset 32
        {
            ulong c = 0ul;
            for (uint i = 0u; i < 64u; ++i) {
                ulong s = (ulong)T[32u + i] + (ulong)ma[i] + c;
                T[32u + i] = (uint)s; c = s >> 32;
            }
            for (uint i = 96u; c != 0ul && i < 128u; ++i) {
                ulong s = (ulong)T[i] + c; T[i] = (uint)s; c = s >> 32;
            }
        }

        // T += mb at offset 32
        {
            ulong c = 0ul;
            for (uint i = 0u; i < 64u; ++i) {
                ulong s = (ulong)T[32u + i] + (ulong)mb[i] + c;
                T[32u + i] = (uint)s; c = s >> 32;
            }
            for (uint i = 96u; c != 0ul && i < 128u; ++i) {
                ulong s = (ulong)T[i] + c; T[i] = (uint)s; c = s >> 32;
            }
        }

        // T += hi at offset 64
        {
            ulong c = 0ul;
            for (uint i = 0u; i < 64u; ++i) {
                ulong s = (ulong)T[64u + i] + (ulong)hi[i] + c;
                T[64u + i] = (uint)s; c = s >> 32;
            }
        }

        // Montgomery reduce (np0=1 for ECM primes)
        {
            for (uint i = 0u; i < 64u; ++i) {
                uint m = T[0u];  // np0==1
                ulong c = 0ul; uint j;
                for (j = 0u; j < 64u; ++j) {
                    ulong uv = (ulong)T[j] + (ulong)m * (ulong)N[j] + c;
                    if (j > 0u) T[j - 1u] = (uint)uv;
                    c = uv >> 32;
                }
                for (; j < 128u - i; ++j) {
                    ulong uv = (ulong)T[j] + c;
                    if (j > 0u) T[j - 1u] = (uint)uv;
                    c = uv >> 32; if (c == 0ul) break;
                }
            }
            ulong borrow = 0ul; uint D[64u];
            for (uint i = 0u; i < 64u; ++i) {
                ulong tv = (ulong)T[i], nv = (ulong)N[i];
                ulong w = tv - nv - borrow; D[i] = (uint)w;
                borrow = (tv < nv + borrow) ? 1ul : 0ul;
            }
            uint any_high = 0u;
            for (uint i = 64u; i < 128u; ++i) { if (T[i] != 0u) { any_high = 1u; break; } }
            uint need_sub = any_high | ((borrow == 0u) ? 1u : 0u);
            uint mask = 0u - need_sub;
            for (uint i = 0u; i < 64u; ++i) out[i] = (D[i] & mask) | (T[i] & ~mask);
        }
    }
    barrier(CLK_LOCAL_MEM_FENCE);
}
