// Stage1 Montgomery mul/sqr - 160 active limbs in 160-limb container.
// Inner #pragma unroll for SRA; outer loop kept as-is for fast compile.
// AUTO-GENERATED by tools/gen_mont_unroll.py - do not edit.
static inline void mont_mul_unroll_5120b(uint *out, const uint *a, const uint *b, const uint *N, uint np0, uint limbs) {
    uint t[160u+2u];
    #pragma unroll
    for (uint i=0u;i<160u+2u;++i) t[i]=0u;
    uint B[160u];
    #pragma unroll
    for (uint j=0u;j<160u;++j) B[j]=b[j];
    for (uint i=0u;i<160u;++i) {
        uint ai=a[i]; ulong carry=0ul;
    #pragma unroll
        for (uint j=0u;j<160u;++j) { ulong uv=(ulong)t[j]+(ulong)ai*(ulong)B[j]+carry; t[j]=(uint)uv; carry=uv>>32; }
        ulong top=(ulong)t[160u]+carry; t[160u]=(uint)top; t[160u+1u]=(uint)(top>>32);
        uint m=(uint)((ulong)t[0]*(ulong)np0); carry=0ul;
    #pragma unroll
        for (uint j=0u;j<160u;++j) { ulong uv=(ulong)t[j]+(ulong)m*(ulong)N[j]+carry; if(j>0u) t[j-1u]=(uint)uv; carry=uv>>32; }
        top=(ulong)t[160u]+carry; t[160u-1u]=(uint)top; top=(ulong)t[160u+1u]+(top>>32); t[160u]=(uint)top; t[160u+1u]=(uint)(top>>32);
    }
    ulong borrow=0ul; uint D[160u];
    #pragma unroll
    for (uint i=0u;i<160u;++i) { ulong tv=(ulong)t[i],nv=(ulong)N[i]; ulong w=tv-nv-borrow; D[i]=(uint)w; borrow=(tv<nv+borrow)?1ul:0ul; }
    uint need_sub=(t[160u]|t[160u+1u])!=0u?1u:0u; need_sub=(borrow==0u)?1u:need_sub; uint mask=0u-need_sub;
    #pragma unroll
    for (uint i=0u;i<160u;++i) out[i]=(D[i]&mask)|(t[i]&~mask);
    (void)limbs;
}

static inline void mont_sqr_unroll_5120b(uint *out, const uint *a, const uint *N, uint np0, uint limbs) {
    mont_mul_unroll_5120b(out, a, a, N, np0, limbs);
}
