// AUTO-GENERATED by tools/gen_mont_fips.py - do not edit.
// FIPS Montgomery mul/sqr - 32 limbs (1024-bit).
// 3-register carry accumulator; no t[] array, no spill.

#ifndef MONT_FIXED_1024_LIMBS
#define MONT_FIXED_1024_LIMBS 32u
#endif

static inline void fips_1024_csa_add(uint *t, uint *u, uint *v, ulong prod) {
    ulong val = (ulong)(*v) + prod;
    *v = (uint)val;
    val = (val >> 32) + (ulong)(*u);
    *u = (uint)val;
    val = (val >> 32) + (ulong)(*t);
    *t = (uint)val;
}

static inline void fips_1024_csa_shift(uint *t, uint *u, uint *v) {
    uint tv = *t; uint uv = *u;
    *v = uv; *u = tv; *t = 0u;
}

static inline void fips_1024_finalize_p(uint *out, const uint *P, const uint *n) {
    uint ps = P[32u];
    ulong borrow = 0ul;
    uint D[32u];
    for (uint i = 0u; i < 32u; ++i) {
        ulong tv = (ulong)P[i];
        ulong nv = (ulong)n[i];
        ulong w = tv - nv - borrow;
        D[i] = (uint)w;
        borrow = (tv < nv + borrow) ? 1ul : 0ul;
    }
    uint any_high = (ps != 0u) ? 1u : 0u;
    uint need_sub = any_high | ((borrow == 0u) ? 1u : 0u);
    uint mask = 0u - need_sub;
    for (uint i = 0u; i < 32u; ++i) {
        out[i] = (D[i] & mask) | (P[i] & ~mask);
    }
}

static inline void mont_mul_fips_1024b(uint *out, const uint *a, const uint *b,
                                            const uint *N, uint np0, uint limbs) {
    uint P[33u];
    uint t = 0u;
    uint u = 0u;
    uint v = 0u;

    for (uint i = 0u; i < 32u; ++i) {
        for (uint j = 0u; j < i; ++j) {
            fips_1024_csa_add(&t, &u, &v, (ulong)a[j] * (ulong)b[i - j]);
            fips_1024_csa_add(&t, &u, &v, (ulong)P[j] * (ulong)N[i - j]);
        }
        fips_1024_csa_add(&t, &u, &v, (ulong)a[i] * (ulong)b[0]);
        uint pi = (uint)((ulong)v * (ulong)np0);
        fips_1024_csa_add(&t, &u, &v, (ulong)pi * (ulong)N[0]);
        P[i] = pi;
        fips_1024_csa_shift(&t, &u, &v);
    }

    for (uint i = 32u; i < 64u; ++i) {
        for (uint j = i - 32u + 1u; j < 32u; ++j) {
            fips_1024_csa_add(&t, &u, &v, (ulong)a[j] * (ulong)b[i - j]);
            fips_1024_csa_add(&t, &u, &v, (ulong)P[j] * (ulong)N[i - j]);
        }
        P[i - 32u] = v;
        fips_1024_csa_shift(&t, &u, &v);
    }
    P[32u] = v;

    fips_1024_finalize_p(out, P, N);
    (void)np0;
}

static inline void mont_sqr_fips_1024b(uint *out, const uint *a, const uint *N, uint np0, uint limbs) {
    mont_mul_fips_1024b(out, a, a, N, np0, limbs);
}
