// Stage1 Montgomery mul/sqr LDS variant - 160 active limbs in 160-limb container.
// __local t[]/B[] buffers provided by caller to avoid scratch-memory spill.
// AUTO-GENERATED by tools/gen_mont_unroll.py - do not edit.
static inline void mont_mul_unroll_5120b_local(uint *out, const uint *a, const uint *b, const uint *N,
    uint np0, uint limbs, __local uint *t_local, __local uint *B_local) {
    #pragma unroll
    for (uint i = 0u; i < 160u + 2u; ++i) t_local[i] = 0u;
    #pragma unroll
    for (uint j = 0u; j <160u; ++j) B_local[j] = b[j];
    for (uint i = 0u; i <160u; ++i) {
        uint ai = a[i]; ulong carry = 0ul;
    #pragma unroll
        for (uint j = 0u; j < 160u; ++j) {
            ulong uv = (ulong)t_local[j] + (ulong)ai * (ulong)B_local[j] + carry;
            t_local[j] = (uint)uv; carry = uv>>32;
        }
        ulong top = (ulong)t_local[160u] + carry;
        t_local[160u]    = (uint)top;
        t_local[160u+1u] = (uint)(top>>32);
        uint m = (uint)((ulong)t_local[0] * (ulong)np0);
        carry=0ul;
    #pragma unroll
        for (uint j = 0u; j < 160u; ++j) {
            ulong uv = (ulong)t_local[j] + (ulong)m * (ulong)N[j] + carry;
            if (j > 0u) t_local[j-1u] = (uint)uv; carry = uv>>32;
            }
        top = (ulong)t_local[160u] + carry;
        t_local[160u-1u] = (uint)top;
        top = (ulong)t_local[160u + 1u] + (top>>32);
        t_local[160u]    = (uint)top;
        t_local[160u+1u] = (uint)(top>>32);
    }
    ulong borrow = 0ul;
    uint D[160u];
    #pragma unroll
    for (uint i = 0u;i<160u;++i) {
            ulong tv = (ulong)t_local[i], nv = (ulong)N[i];
            ulong w = tv - nv - borrow;
            D[i] = (uint)w;
            borrow = (tv < nv + borrow) ? 1ul : 0ul;
        }
        uint need_sub = (t_local[160u] | t_local[160u+1u]) != 0u ? 1u : 0u;
        need_sub  = (borrow == 0u) ? 1u : need_sub;
        uint mask = 0u - need_sub;
    #pragma unroll
    for (uint i = 0u; i < 160u; ++i) out[i] = (D[i] & mask) | (t_local[i] & ~mask);
    (void)limbs;
}

static inline void mont_sqr_unroll_5120b_local(uint *out, const uint *a, const uint *N, uint np0, uint limbs,
        __local uint *t_local, __local uint *B_local) {
    mont_mul_unroll_5120b_local(out, a, a, N, np0, limbs, t_local, B_local);
}
