// AUTO-GENERATED by tools/gen_mp_addsub_bits_stage1.py - do not edit.
static inline int sub_mod_asm_2560b_body(uint *r, const uint *a, const uint *b, const uint *N) {
    uint br = 0u;
    asm_sub_fused_block80_priv(a, b, N, r, br, &br);
    return br != 0u ? 1 : 0;
}

#if !defined(__AMDGCN__)
static inline int sub_mod_unroll_2560b_body(uint *r, const uint *a, const uint *b, const uint *N) {
    ulong br = 0ul;
    {
        ulong av = (ulong)a[0];
        ulong bv = (ulong)b[0];
        ulong w = av - bv - br;
        r[0] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[1];
        ulong bv = (ulong)b[1];
        ulong w = av - bv - br;
        r[1] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[2];
        ulong bv = (ulong)b[2];
        ulong w = av - bv - br;
        r[2] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[3];
        ulong bv = (ulong)b[3];
        ulong w = av - bv - br;
        r[3] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[4];
        ulong bv = (ulong)b[4];
        ulong w = av - bv - br;
        r[4] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[5];
        ulong bv = (ulong)b[5];
        ulong w = av - bv - br;
        r[5] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[6];
        ulong bv = (ulong)b[6];
        ulong w = av - bv - br;
        r[6] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[7];
        ulong bv = (ulong)b[7];
        ulong w = av - bv - br;
        r[7] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[8];
        ulong bv = (ulong)b[8];
        ulong w = av - bv - br;
        r[8] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[9];
        ulong bv = (ulong)b[9];
        ulong w = av - bv - br;
        r[9] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[10];
        ulong bv = (ulong)b[10];
        ulong w = av - bv - br;
        r[10] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[11];
        ulong bv = (ulong)b[11];
        ulong w = av - bv - br;
        r[11] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[12];
        ulong bv = (ulong)b[12];
        ulong w = av - bv - br;
        r[12] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[13];
        ulong bv = (ulong)b[13];
        ulong w = av - bv - br;
        r[13] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[14];
        ulong bv = (ulong)b[14];
        ulong w = av - bv - br;
        r[14] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[15];
        ulong bv = (ulong)b[15];
        ulong w = av - bv - br;
        r[15] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[16];
        ulong bv = (ulong)b[16];
        ulong w = av - bv - br;
        r[16] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[17];
        ulong bv = (ulong)b[17];
        ulong w = av - bv - br;
        r[17] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[18];
        ulong bv = (ulong)b[18];
        ulong w = av - bv - br;
        r[18] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[19];
        ulong bv = (ulong)b[19];
        ulong w = av - bv - br;
        r[19] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[20];
        ulong bv = (ulong)b[20];
        ulong w = av - bv - br;
        r[20] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[21];
        ulong bv = (ulong)b[21];
        ulong w = av - bv - br;
        r[21] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[22];
        ulong bv = (ulong)b[22];
        ulong w = av - bv - br;
        r[22] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[23];
        ulong bv = (ulong)b[23];
        ulong w = av - bv - br;
        r[23] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[24];
        ulong bv = (ulong)b[24];
        ulong w = av - bv - br;
        r[24] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[25];
        ulong bv = (ulong)b[25];
        ulong w = av - bv - br;
        r[25] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[26];
        ulong bv = (ulong)b[26];
        ulong w = av - bv - br;
        r[26] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[27];
        ulong bv = (ulong)b[27];
        ulong w = av - bv - br;
        r[27] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[28];
        ulong bv = (ulong)b[28];
        ulong w = av - bv - br;
        r[28] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[29];
        ulong bv = (ulong)b[29];
        ulong w = av - bv - br;
        r[29] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[30];
        ulong bv = (ulong)b[30];
        ulong w = av - bv - br;
        r[30] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[31];
        ulong bv = (ulong)b[31];
        ulong w = av - bv - br;
        r[31] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[32];
        ulong bv = (ulong)b[32];
        ulong w = av - bv - br;
        r[32] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[33];
        ulong bv = (ulong)b[33];
        ulong w = av - bv - br;
        r[33] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[34];
        ulong bv = (ulong)b[34];
        ulong w = av - bv - br;
        r[34] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[35];
        ulong bv = (ulong)b[35];
        ulong w = av - bv - br;
        r[35] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[36];
        ulong bv = (ulong)b[36];
        ulong w = av - bv - br;
        r[36] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[37];
        ulong bv = (ulong)b[37];
        ulong w = av - bv - br;
        r[37] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[38];
        ulong bv = (ulong)b[38];
        ulong w = av - bv - br;
        r[38] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[39];
        ulong bv = (ulong)b[39];
        ulong w = av - bv - br;
        r[39] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[40];
        ulong bv = (ulong)b[40];
        ulong w = av - bv - br;
        r[40] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[41];
        ulong bv = (ulong)b[41];
        ulong w = av - bv - br;
        r[41] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[42];
        ulong bv = (ulong)b[42];
        ulong w = av - bv - br;
        r[42] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[43];
        ulong bv = (ulong)b[43];
        ulong w = av - bv - br;
        r[43] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[44];
        ulong bv = (ulong)b[44];
        ulong w = av - bv - br;
        r[44] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[45];
        ulong bv = (ulong)b[45];
        ulong w = av - bv - br;
        r[45] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[46];
        ulong bv = (ulong)b[46];
        ulong w = av - bv - br;
        r[46] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[47];
        ulong bv = (ulong)b[47];
        ulong w = av - bv - br;
        r[47] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[48];
        ulong bv = (ulong)b[48];
        ulong w = av - bv - br;
        r[48] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[49];
        ulong bv = (ulong)b[49];
        ulong w = av - bv - br;
        r[49] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[50];
        ulong bv = (ulong)b[50];
        ulong w = av - bv - br;
        r[50] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[51];
        ulong bv = (ulong)b[51];
        ulong w = av - bv - br;
        r[51] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[52];
        ulong bv = (ulong)b[52];
        ulong w = av - bv - br;
        r[52] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[53];
        ulong bv = (ulong)b[53];
        ulong w = av - bv - br;
        r[53] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[54];
        ulong bv = (ulong)b[54];
        ulong w = av - bv - br;
        r[54] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[55];
        ulong bv = (ulong)b[55];
        ulong w = av - bv - br;
        r[55] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[56];
        ulong bv = (ulong)b[56];
        ulong w = av - bv - br;
        r[56] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[57];
        ulong bv = (ulong)b[57];
        ulong w = av - bv - br;
        r[57] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[58];
        ulong bv = (ulong)b[58];
        ulong w = av - bv - br;
        r[58] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[59];
        ulong bv = (ulong)b[59];
        ulong w = av - bv - br;
        r[59] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[60];
        ulong bv = (ulong)b[60];
        ulong w = av - bv - br;
        r[60] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[61];
        ulong bv = (ulong)b[61];
        ulong w = av - bv - br;
        r[61] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[62];
        ulong bv = (ulong)b[62];
        ulong w = av - bv - br;
        r[62] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[63];
        ulong bv = (ulong)b[63];
        ulong w = av - bv - br;
        r[63] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[64];
        ulong bv = (ulong)b[64];
        ulong w = av - bv - br;
        r[64] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[65];
        ulong bv = (ulong)b[65];
        ulong w = av - bv - br;
        r[65] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[66];
        ulong bv = (ulong)b[66];
        ulong w = av - bv - br;
        r[66] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[67];
        ulong bv = (ulong)b[67];
        ulong w = av - bv - br;
        r[67] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[68];
        ulong bv = (ulong)b[68];
        ulong w = av - bv - br;
        r[68] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[69];
        ulong bv = (ulong)b[69];
        ulong w = av - bv - br;
        r[69] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[70];
        ulong bv = (ulong)b[70];
        ulong w = av - bv - br;
        r[70] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[71];
        ulong bv = (ulong)b[71];
        ulong w = av - bv - br;
        r[71] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[72];
        ulong bv = (ulong)b[72];
        ulong w = av - bv - br;
        r[72] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[73];
        ulong bv = (ulong)b[73];
        ulong w = av - bv - br;
        r[73] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[74];
        ulong bv = (ulong)b[74];
        ulong w = av - bv - br;
        r[74] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[75];
        ulong bv = (ulong)b[75];
        ulong w = av - bv - br;
        r[75] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[76];
        ulong bv = (ulong)b[76];
        ulong w = av - bv - br;
        r[76] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[77];
        ulong bv = (ulong)b[77];
        ulong w = av - bv - br;
        r[77] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[78];
        ulong bv = (ulong)b[78];
        ulong w = av - bv - br;
        r[78] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[79];
        ulong bv = (ulong)b[79];
        ulong w = av - bv - br;
        r[79] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    if (br != 0ul) {
        ulong c = 0ul;
        {
            ulong s = (ulong)r[0] + (ulong)N[0] + c;
            r[0] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[1] + (ulong)N[1] + c;
            r[1] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[2] + (ulong)N[2] + c;
            r[2] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[3] + (ulong)N[3] + c;
            r[3] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[4] + (ulong)N[4] + c;
            r[4] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[5] + (ulong)N[5] + c;
            r[5] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[6] + (ulong)N[6] + c;
            r[6] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[7] + (ulong)N[7] + c;
            r[7] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[8] + (ulong)N[8] + c;
            r[8] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[9] + (ulong)N[9] + c;
            r[9] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[10] + (ulong)N[10] + c;
            r[10] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[11] + (ulong)N[11] + c;
            r[11] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[12] + (ulong)N[12] + c;
            r[12] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[13] + (ulong)N[13] + c;
            r[13] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[14] + (ulong)N[14] + c;
            r[14] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[15] + (ulong)N[15] + c;
            r[15] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[16] + (ulong)N[16] + c;
            r[16] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[17] + (ulong)N[17] + c;
            r[17] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[18] + (ulong)N[18] + c;
            r[18] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[19] + (ulong)N[19] + c;
            r[19] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[20] + (ulong)N[20] + c;
            r[20] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[21] + (ulong)N[21] + c;
            r[21] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[22] + (ulong)N[22] + c;
            r[22] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[23] + (ulong)N[23] + c;
            r[23] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[24] + (ulong)N[24] + c;
            r[24] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[25] + (ulong)N[25] + c;
            r[25] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[26] + (ulong)N[26] + c;
            r[26] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[27] + (ulong)N[27] + c;
            r[27] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[28] + (ulong)N[28] + c;
            r[28] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[29] + (ulong)N[29] + c;
            r[29] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[30] + (ulong)N[30] + c;
            r[30] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[31] + (ulong)N[31] + c;
            r[31] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[32] + (ulong)N[32] + c;
            r[32] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[33] + (ulong)N[33] + c;
            r[33] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[34] + (ulong)N[34] + c;
            r[34] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[35] + (ulong)N[35] + c;
            r[35] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[36] + (ulong)N[36] + c;
            r[36] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[37] + (ulong)N[37] + c;
            r[37] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[38] + (ulong)N[38] + c;
            r[38] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[39] + (ulong)N[39] + c;
            r[39] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[40] + (ulong)N[40] + c;
            r[40] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[41] + (ulong)N[41] + c;
            r[41] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[42] + (ulong)N[42] + c;
            r[42] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[43] + (ulong)N[43] + c;
            r[43] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[44] + (ulong)N[44] + c;
            r[44] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[45] + (ulong)N[45] + c;
            r[45] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[46] + (ulong)N[46] + c;
            r[46] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[47] + (ulong)N[47] + c;
            r[47] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[48] + (ulong)N[48] + c;
            r[48] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[49] + (ulong)N[49] + c;
            r[49] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[50] + (ulong)N[50] + c;
            r[50] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[51] + (ulong)N[51] + c;
            r[51] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[52] + (ulong)N[52] + c;
            r[52] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[53] + (ulong)N[53] + c;
            r[53] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[54] + (ulong)N[54] + c;
            r[54] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[55] + (ulong)N[55] + c;
            r[55] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[56] + (ulong)N[56] + c;
            r[56] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[57] + (ulong)N[57] + c;
            r[57] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[58] + (ulong)N[58] + c;
            r[58] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[59] + (ulong)N[59] + c;
            r[59] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[60] + (ulong)N[60] + c;
            r[60] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[61] + (ulong)N[61] + c;
            r[61] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[62] + (ulong)N[62] + c;
            r[62] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[63] + (ulong)N[63] + c;
            r[63] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[64] + (ulong)N[64] + c;
            r[64] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[65] + (ulong)N[65] + c;
            r[65] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[66] + (ulong)N[66] + c;
            r[66] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[67] + (ulong)N[67] + c;
            r[67] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[68] + (ulong)N[68] + c;
            r[68] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[69] + (ulong)N[69] + c;
            r[69] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[70] + (ulong)N[70] + c;
            r[70] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[71] + (ulong)N[71] + c;
            r[71] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[72] + (ulong)N[72] + c;
            r[72] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[73] + (ulong)N[73] + c;
            r[73] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[74] + (ulong)N[74] + c;
            r[74] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[75] + (ulong)N[75] + c;
            r[75] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[76] + (ulong)N[76] + c;
            r[76] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[77] + (ulong)N[77] + c;
            r[77] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[78] + (ulong)N[78] + c;
            r[78] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[79] + (ulong)N[79] + c;
            r[79] = (uint)s;
            c = s >> 32;
        }
        return 1;
    }
    return 0;
}

#endif
#if defined(__AMDGCN__)
static inline int sub_mod_asm_2560b(uint *r, const uint *a, const uint *b,
                                      const uint *N, uint limbs) {
    if (limbs == 80u) { return sub_mod_asm_2560b_body(r, a, b, N); }
    return 0;
}
#else
static inline int sub_mod_asm_2560b(uint *r, const uint *a, const uint *b,
                                      const uint *N, uint limbs) {
    if (limbs == 80u) { return sub_mod_unroll_2560b_body(r, a, b, N); }
    return 0;
}
#endif
