// AUTO-GENERATED by tools/gen_mp_addsub_bits_stage1.py - do not edit.
#ifndef SUB_MOD_UNROLL_5120B_BODY_DEFINED
#define SUB_MOD_UNROLL_5120B_BODY_DEFINED
static inline int sub_mod_unroll_5120b_body(uint *r, const uint *a, const uint *b, const uint *N) {
    ulong br = 0ul;
    #pragma unroll
    for (uint blk = 0u; blk < 5u; ++blk) {
        uint off = blk * 32u;
        #pragma unroll 32
        for (uint j = 0u; j < 32u; ++j) {
            uint i = off + j;
            ulong av = (ulong)a[i];
            ulong bv = (ulong)b[i];
            ulong w = av - bv - br;
            r[i] = (uint)w;
            br = (av < bv + br) ? 1ul : 0ul;
        }
    }
    if (br != 0ul) {
        ulong c = 0ul;
    // NVIDIA compiler crash avoidance: no unroll for large limb counts
    for (uint i = 0u; i < 160u; ++i) {
        ulong s = (ulong)r[i] + (ulong)N[i] + c;
        r[i] = (uint)s;
        c = s >> 32;
    }
        return 1;
    }
    return 0;
}
#endif

static inline int sub_mod_unroll_5120b(uint *r, const uint *a, const uint *b,
                                         const uint *N, uint limbs) {
    if (limbs == 160u) { return sub_mod_unroll_5120b_body(r, a, b, N); }
    return 0;
}
