// AUTO-GENERATED by tools/gen_mp_addsub_bits_stage1.py - do not edit.
#ifndef SUB_MOD_UNROLL_3584B_BODY_DEFINED
#define SUB_MOD_UNROLL_3584B_BODY_DEFINED
static inline int sub_mod_unroll_3584b_body(uint *r, const uint *a, const uint *b, const uint *N) {
    ulong br = 0ul;
    #pragma unroll
    for (uint blk = 0u; blk < 3u; ++blk) {
        uint off = blk * 32u;
        #pragma unroll 32
        for (uint j = 0u; j < 32u; ++j) {
            uint i = off + j;
            ulong av = (ulong)a[i];
            ulong bv = (ulong)b[i];
            ulong w = av - bv - br;
            r[i] = (uint)w;
            br = (av < bv + br) ? 1ul : 0ul;
        }
    }
    { uint off = 3 * 32u;
        { uint i = off + 0;
            ulong av = (ulong)a[i];
            ulong bv = (ulong)b[i];
            ulong w = av - bv - br;
            r[i] = (uint)w;
            br = (av < bv + br) ? 1ul : 0ul; }
        { uint i = off + 1;
            ulong av = (ulong)a[i];
            ulong bv = (ulong)b[i];
            ulong w = av - bv - br;
            r[i] = (uint)w;
            br = (av < bv + br) ? 1ul : 0ul; }
        { uint i = off + 2;
            ulong av = (ulong)a[i];
            ulong bv = (ulong)b[i];
            ulong w = av - bv - br;
            r[i] = (uint)w;
            br = (av < bv + br) ? 1ul : 0ul; }
        { uint i = off + 3;
            ulong av = (ulong)a[i];
            ulong bv = (ulong)b[i];
            ulong w = av - bv - br;
            r[i] = (uint)w;
            br = (av < bv + br) ? 1ul : 0ul; }
        { uint i = off + 4;
            ulong av = (ulong)a[i];
            ulong bv = (ulong)b[i];
            ulong w = av - bv - br;
            r[i] = (uint)w;
            br = (av < bv + br) ? 1ul : 0ul; }
        { uint i = off + 5;
            ulong av = (ulong)a[i];
            ulong bv = (ulong)b[i];
            ulong w = av - bv - br;
            r[i] = (uint)w;
            br = (av < bv + br) ? 1ul : 0ul; }
        { uint i = off + 6;
            ulong av = (ulong)a[i];
            ulong bv = (ulong)b[i];
            ulong w = av - bv - br;
            r[i] = (uint)w;
            br = (av < bv + br) ? 1ul : 0ul; }
        { uint i = off + 7;
            ulong av = (ulong)a[i];
            ulong bv = (ulong)b[i];
            ulong w = av - bv - br;
            r[i] = (uint)w;
            br = (av < bv + br) ? 1ul : 0ul; }
        { uint i = off + 8;
            ulong av = (ulong)a[i];
            ulong bv = (ulong)b[i];
            ulong w = av - bv - br;
            r[i] = (uint)w;
            br = (av < bv + br) ? 1ul : 0ul; }
        { uint i = off + 9;
            ulong av = (ulong)a[i];
            ulong bv = (ulong)b[i];
            ulong w = av - bv - br;
            r[i] = (uint)w;
            br = (av < bv + br) ? 1ul : 0ul; }
        { uint i = off + 10;
            ulong av = (ulong)a[i];
            ulong bv = (ulong)b[i];
            ulong w = av - bv - br;
            r[i] = (uint)w;
            br = (av < bv + br) ? 1ul : 0ul; }
        { uint i = off + 11;
            ulong av = (ulong)a[i];
            ulong bv = (ulong)b[i];
            ulong w = av - bv - br;
            r[i] = (uint)w;
            br = (av < bv + br) ? 1ul : 0ul; }
        { uint i = off + 12;
            ulong av = (ulong)a[i];
            ulong bv = (ulong)b[i];
            ulong w = av - bv - br;
            r[i] = (uint)w;
            br = (av < bv + br) ? 1ul : 0ul; }
        { uint i = off + 13;
            ulong av = (ulong)a[i];
            ulong bv = (ulong)b[i];
            ulong w = av - bv - br;
            r[i] = (uint)w;
            br = (av < bv + br) ? 1ul : 0ul; }
        { uint i = off + 14;
            ulong av = (ulong)a[i];
            ulong bv = (ulong)b[i];
            ulong w = av - bv - br;
            r[i] = (uint)w;
            br = (av < bv + br) ? 1ul : 0ul; }
        { uint i = off + 15;
            ulong av = (ulong)a[i];
            ulong bv = (ulong)b[i];
            ulong w = av - bv - br;
            r[i] = (uint)w;
            br = (av < bv + br) ? 1ul : 0ul; }
    }
    if (br != 0ul) {
        ulong c = 0ul;
    #pragma unroll 32
    for (uint i = 0u; i < 112u; ++i) {
        ulong s = (ulong)r[i] + (ulong)N[i] + c;
        r[i] = (uint)s;
        c = s >> 32;
    }
        return 1;
    }
    return 0;
}
#endif

static inline int sub_mod_unroll_3584b(uint *r, const uint *a, const uint *b,
                                         const uint *N, uint limbs) {
    if (limbs == 112u) { return sub_mod_unroll_3584b_body(r, a, b, N); }
    return 0;
}
