// AUTO-GENERATED by tools/gen_mp_addsub_bits_stage1.py - do not edit.
static inline int sub_mod_asm_8192b_body(uint *r, const uint *a, const uint *b, const uint *N) {
    uint br = 0u;
    asm_sub_fused_block32_priv_nofix(a + 0, b + 0, N + 0, r + 0, br, &br);
    asm_sub_fused_block32_priv_nofix(a + 32, b + 32, N + 32, r + 32, br, &br);
    asm_sub_fused_block32_priv_nofix(a + 64, b + 64, N + 64, r + 64, br, &br);
    asm_sub_fused_block32_priv_nofix(a + 96, b + 96, N + 96, r + 96, br, &br);
    asm_sub_fused_block32_priv_nofix(a + 128, b + 128, N + 128, r + 128, br, &br);
    asm_sub_fused_block32_priv_nofix(a + 160, b + 160, N + 160, r + 160, br, &br);
    asm_sub_fused_block32_priv_nofix(a + 192, b + 192, N + 192, r + 192, br, &br);
    asm_sub_fused_block32_priv_nofix(a + 224, b + 224, N + 224, r + 224, br, &br);
    if (br != 0u) {
        ulong c = 0ul;
        c = (ulong)r[0] + (ulong)N[0] + c; r[0] = (uint)c; c >>= 32;
        c = (ulong)r[1] + (ulong)N[1] + c; r[1] = (uint)c; c >>= 32;
        c = (ulong)r[2] + (ulong)N[2] + c; r[2] = (uint)c; c >>= 32;
        c = (ulong)r[3] + (ulong)N[3] + c; r[3] = (uint)c; c >>= 32;
        c = (ulong)r[4] + (ulong)N[4] + c; r[4] = (uint)c; c >>= 32;
        c = (ulong)r[5] + (ulong)N[5] + c; r[5] = (uint)c; c >>= 32;
        c = (ulong)r[6] + (ulong)N[6] + c; r[6] = (uint)c; c >>= 32;
        c = (ulong)r[7] + (ulong)N[7] + c; r[7] = (uint)c; c >>= 32;
        c = (ulong)r[8] + (ulong)N[8] + c; r[8] = (uint)c; c >>= 32;
        c = (ulong)r[9] + (ulong)N[9] + c; r[9] = (uint)c; c >>= 32;
        c = (ulong)r[10] + (ulong)N[10] + c; r[10] = (uint)c; c >>= 32;
        c = (ulong)r[11] + (ulong)N[11] + c; r[11] = (uint)c; c >>= 32;
        c = (ulong)r[12] + (ulong)N[12] + c; r[12] = (uint)c; c >>= 32;
        c = (ulong)r[13] + (ulong)N[13] + c; r[13] = (uint)c; c >>= 32;
        c = (ulong)r[14] + (ulong)N[14] + c; r[14] = (uint)c; c >>= 32;
        c = (ulong)r[15] + (ulong)N[15] + c; r[15] = (uint)c; c >>= 32;
        c = (ulong)r[16] + (ulong)N[16] + c; r[16] = (uint)c; c >>= 32;
        c = (ulong)r[17] + (ulong)N[17] + c; r[17] = (uint)c; c >>= 32;
        c = (ulong)r[18] + (ulong)N[18] + c; r[18] = (uint)c; c >>= 32;
        c = (ulong)r[19] + (ulong)N[19] + c; r[19] = (uint)c; c >>= 32;
        c = (ulong)r[20] + (ulong)N[20] + c; r[20] = (uint)c; c >>= 32;
        c = (ulong)r[21] + (ulong)N[21] + c; r[21] = (uint)c; c >>= 32;
        c = (ulong)r[22] + (ulong)N[22] + c; r[22] = (uint)c; c >>= 32;
        c = (ulong)r[23] + (ulong)N[23] + c; r[23] = (uint)c; c >>= 32;
        c = (ulong)r[24] + (ulong)N[24] + c; r[24] = (uint)c; c >>= 32;
        c = (ulong)r[25] + (ulong)N[25] + c; r[25] = (uint)c; c >>= 32;
        c = (ulong)r[26] + (ulong)N[26] + c; r[26] = (uint)c; c >>= 32;
        c = (ulong)r[27] + (ulong)N[27] + c; r[27] = (uint)c; c >>= 32;
        c = (ulong)r[28] + (ulong)N[28] + c; r[28] = (uint)c; c >>= 32;
        c = (ulong)r[29] + (ulong)N[29] + c; r[29] = (uint)c; c >>= 32;
        c = (ulong)r[30] + (ulong)N[30] + c; r[30] = (uint)c; c >>= 32;
        c = (ulong)r[31] + (ulong)N[31] + c; r[31] = (uint)c; c >>= 32;
        c = (ulong)r[32] + (ulong)N[32] + c; r[32] = (uint)c; c >>= 32;
        c = (ulong)r[33] + (ulong)N[33] + c; r[33] = (uint)c; c >>= 32;
        c = (ulong)r[34] + (ulong)N[34] + c; r[34] = (uint)c; c >>= 32;
        c = (ulong)r[35] + (ulong)N[35] + c; r[35] = (uint)c; c >>= 32;
        c = (ulong)r[36] + (ulong)N[36] + c; r[36] = (uint)c; c >>= 32;
        c = (ulong)r[37] + (ulong)N[37] + c; r[37] = (uint)c; c >>= 32;
        c = (ulong)r[38] + (ulong)N[38] + c; r[38] = (uint)c; c >>= 32;
        c = (ulong)r[39] + (ulong)N[39] + c; r[39] = (uint)c; c >>= 32;
        c = (ulong)r[40] + (ulong)N[40] + c; r[40] = (uint)c; c >>= 32;
        c = (ulong)r[41] + (ulong)N[41] + c; r[41] = (uint)c; c >>= 32;
        c = (ulong)r[42] + (ulong)N[42] + c; r[42] = (uint)c; c >>= 32;
        c = (ulong)r[43] + (ulong)N[43] + c; r[43] = (uint)c; c >>= 32;
        c = (ulong)r[44] + (ulong)N[44] + c; r[44] = (uint)c; c >>= 32;
        c = (ulong)r[45] + (ulong)N[45] + c; r[45] = (uint)c; c >>= 32;
        c = (ulong)r[46] + (ulong)N[46] + c; r[46] = (uint)c; c >>= 32;
        c = (ulong)r[47] + (ulong)N[47] + c; r[47] = (uint)c; c >>= 32;
        c = (ulong)r[48] + (ulong)N[48] + c; r[48] = (uint)c; c >>= 32;
        c = (ulong)r[49] + (ulong)N[49] + c; r[49] = (uint)c; c >>= 32;
        c = (ulong)r[50] + (ulong)N[50] + c; r[50] = (uint)c; c >>= 32;
        c = (ulong)r[51] + (ulong)N[51] + c; r[51] = (uint)c; c >>= 32;
        c = (ulong)r[52] + (ulong)N[52] + c; r[52] = (uint)c; c >>= 32;
        c = (ulong)r[53] + (ulong)N[53] + c; r[53] = (uint)c; c >>= 32;
        c = (ulong)r[54] + (ulong)N[54] + c; r[54] = (uint)c; c >>= 32;
        c = (ulong)r[55] + (ulong)N[55] + c; r[55] = (uint)c; c >>= 32;
        c = (ulong)r[56] + (ulong)N[56] + c; r[56] = (uint)c; c >>= 32;
        c = (ulong)r[57] + (ulong)N[57] + c; r[57] = (uint)c; c >>= 32;
        c = (ulong)r[58] + (ulong)N[58] + c; r[58] = (uint)c; c >>= 32;
        c = (ulong)r[59] + (ulong)N[59] + c; r[59] = (uint)c; c >>= 32;
        c = (ulong)r[60] + (ulong)N[60] + c; r[60] = (uint)c; c >>= 32;
        c = (ulong)r[61] + (ulong)N[61] + c; r[61] = (uint)c; c >>= 32;
        c = (ulong)r[62] + (ulong)N[62] + c; r[62] = (uint)c; c >>= 32;
        c = (ulong)r[63] + (ulong)N[63] + c; r[63] = (uint)c; c >>= 32;
        c = (ulong)r[64] + (ulong)N[64] + c; r[64] = (uint)c; c >>= 32;
        c = (ulong)r[65] + (ulong)N[65] + c; r[65] = (uint)c; c >>= 32;
        c = (ulong)r[66] + (ulong)N[66] + c; r[66] = (uint)c; c >>= 32;
        c = (ulong)r[67] + (ulong)N[67] + c; r[67] = (uint)c; c >>= 32;
        c = (ulong)r[68] + (ulong)N[68] + c; r[68] = (uint)c; c >>= 32;
        c = (ulong)r[69] + (ulong)N[69] + c; r[69] = (uint)c; c >>= 32;
        c = (ulong)r[70] + (ulong)N[70] + c; r[70] = (uint)c; c >>= 32;
        c = (ulong)r[71] + (ulong)N[71] + c; r[71] = (uint)c; c >>= 32;
        c = (ulong)r[72] + (ulong)N[72] + c; r[72] = (uint)c; c >>= 32;
        c = (ulong)r[73] + (ulong)N[73] + c; r[73] = (uint)c; c >>= 32;
        c = (ulong)r[74] + (ulong)N[74] + c; r[74] = (uint)c; c >>= 32;
        c = (ulong)r[75] + (ulong)N[75] + c; r[75] = (uint)c; c >>= 32;
        c = (ulong)r[76] + (ulong)N[76] + c; r[76] = (uint)c; c >>= 32;
        c = (ulong)r[77] + (ulong)N[77] + c; r[77] = (uint)c; c >>= 32;
        c = (ulong)r[78] + (ulong)N[78] + c; r[78] = (uint)c; c >>= 32;
        c = (ulong)r[79] + (ulong)N[79] + c; r[79] = (uint)c; c >>= 32;
        c = (ulong)r[80] + (ulong)N[80] + c; r[80] = (uint)c; c >>= 32;
        c = (ulong)r[81] + (ulong)N[81] + c; r[81] = (uint)c; c >>= 32;
        c = (ulong)r[82] + (ulong)N[82] + c; r[82] = (uint)c; c >>= 32;
        c = (ulong)r[83] + (ulong)N[83] + c; r[83] = (uint)c; c >>= 32;
        c = (ulong)r[84] + (ulong)N[84] + c; r[84] = (uint)c; c >>= 32;
        c = (ulong)r[85] + (ulong)N[85] + c; r[85] = (uint)c; c >>= 32;
        c = (ulong)r[86] + (ulong)N[86] + c; r[86] = (uint)c; c >>= 32;
        c = (ulong)r[87] + (ulong)N[87] + c; r[87] = (uint)c; c >>= 32;
        c = (ulong)r[88] + (ulong)N[88] + c; r[88] = (uint)c; c >>= 32;
        c = (ulong)r[89] + (ulong)N[89] + c; r[89] = (uint)c; c >>= 32;
        c = (ulong)r[90] + (ulong)N[90] + c; r[90] = (uint)c; c >>= 32;
        c = (ulong)r[91] + (ulong)N[91] + c; r[91] = (uint)c; c >>= 32;
        c = (ulong)r[92] + (ulong)N[92] + c; r[92] = (uint)c; c >>= 32;
        c = (ulong)r[93] + (ulong)N[93] + c; r[93] = (uint)c; c >>= 32;
        c = (ulong)r[94] + (ulong)N[94] + c; r[94] = (uint)c; c >>= 32;
        c = (ulong)r[95] + (ulong)N[95] + c; r[95] = (uint)c; c >>= 32;
        c = (ulong)r[96] + (ulong)N[96] + c; r[96] = (uint)c; c >>= 32;
        c = (ulong)r[97] + (ulong)N[97] + c; r[97] = (uint)c; c >>= 32;
        c = (ulong)r[98] + (ulong)N[98] + c; r[98] = (uint)c; c >>= 32;
        c = (ulong)r[99] + (ulong)N[99] + c; r[99] = (uint)c; c >>= 32;
        c = (ulong)r[100] + (ulong)N[100] + c; r[100] = (uint)c; c >>= 32;
        c = (ulong)r[101] + (ulong)N[101] + c; r[101] = (uint)c; c >>= 32;
        c = (ulong)r[102] + (ulong)N[102] + c; r[102] = (uint)c; c >>= 32;
        c = (ulong)r[103] + (ulong)N[103] + c; r[103] = (uint)c; c >>= 32;
        c = (ulong)r[104] + (ulong)N[104] + c; r[104] = (uint)c; c >>= 32;
        c = (ulong)r[105] + (ulong)N[105] + c; r[105] = (uint)c; c >>= 32;
        c = (ulong)r[106] + (ulong)N[106] + c; r[106] = (uint)c; c >>= 32;
        c = (ulong)r[107] + (ulong)N[107] + c; r[107] = (uint)c; c >>= 32;
        c = (ulong)r[108] + (ulong)N[108] + c; r[108] = (uint)c; c >>= 32;
        c = (ulong)r[109] + (ulong)N[109] + c; r[109] = (uint)c; c >>= 32;
        c = (ulong)r[110] + (ulong)N[110] + c; r[110] = (uint)c; c >>= 32;
        c = (ulong)r[111] + (ulong)N[111] + c; r[111] = (uint)c; c >>= 32;
        c = (ulong)r[112] + (ulong)N[112] + c; r[112] = (uint)c; c >>= 32;
        c = (ulong)r[113] + (ulong)N[113] + c; r[113] = (uint)c; c >>= 32;
        c = (ulong)r[114] + (ulong)N[114] + c; r[114] = (uint)c; c >>= 32;
        c = (ulong)r[115] + (ulong)N[115] + c; r[115] = (uint)c; c >>= 32;
        c = (ulong)r[116] + (ulong)N[116] + c; r[116] = (uint)c; c >>= 32;
        c = (ulong)r[117] + (ulong)N[117] + c; r[117] = (uint)c; c >>= 32;
        c = (ulong)r[118] + (ulong)N[118] + c; r[118] = (uint)c; c >>= 32;
        c = (ulong)r[119] + (ulong)N[119] + c; r[119] = (uint)c; c >>= 32;
        c = (ulong)r[120] + (ulong)N[120] + c; r[120] = (uint)c; c >>= 32;
        c = (ulong)r[121] + (ulong)N[121] + c; r[121] = (uint)c; c >>= 32;
        c = (ulong)r[122] + (ulong)N[122] + c; r[122] = (uint)c; c >>= 32;
        c = (ulong)r[123] + (ulong)N[123] + c; r[123] = (uint)c; c >>= 32;
        c = (ulong)r[124] + (ulong)N[124] + c; r[124] = (uint)c; c >>= 32;
        c = (ulong)r[125] + (ulong)N[125] + c; r[125] = (uint)c; c >>= 32;
        c = (ulong)r[126] + (ulong)N[126] + c; r[126] = (uint)c; c >>= 32;
        c = (ulong)r[127] + (ulong)N[127] + c; r[127] = (uint)c; c >>= 32;
        c = (ulong)r[128] + (ulong)N[128] + c; r[128] = (uint)c; c >>= 32;
        c = (ulong)r[129] + (ulong)N[129] + c; r[129] = (uint)c; c >>= 32;
        c = (ulong)r[130] + (ulong)N[130] + c; r[130] = (uint)c; c >>= 32;
        c = (ulong)r[131] + (ulong)N[131] + c; r[131] = (uint)c; c >>= 32;
        c = (ulong)r[132] + (ulong)N[132] + c; r[132] = (uint)c; c >>= 32;
        c = (ulong)r[133] + (ulong)N[133] + c; r[133] = (uint)c; c >>= 32;
        c = (ulong)r[134] + (ulong)N[134] + c; r[134] = (uint)c; c >>= 32;
        c = (ulong)r[135] + (ulong)N[135] + c; r[135] = (uint)c; c >>= 32;
        c = (ulong)r[136] + (ulong)N[136] + c; r[136] = (uint)c; c >>= 32;
        c = (ulong)r[137] + (ulong)N[137] + c; r[137] = (uint)c; c >>= 32;
        c = (ulong)r[138] + (ulong)N[138] + c; r[138] = (uint)c; c >>= 32;
        c = (ulong)r[139] + (ulong)N[139] + c; r[139] = (uint)c; c >>= 32;
        c = (ulong)r[140] + (ulong)N[140] + c; r[140] = (uint)c; c >>= 32;
        c = (ulong)r[141] + (ulong)N[141] + c; r[141] = (uint)c; c >>= 32;
        c = (ulong)r[142] + (ulong)N[142] + c; r[142] = (uint)c; c >>= 32;
        c = (ulong)r[143] + (ulong)N[143] + c; r[143] = (uint)c; c >>= 32;
        c = (ulong)r[144] + (ulong)N[144] + c; r[144] = (uint)c; c >>= 32;
        c = (ulong)r[145] + (ulong)N[145] + c; r[145] = (uint)c; c >>= 32;
        c = (ulong)r[146] + (ulong)N[146] + c; r[146] = (uint)c; c >>= 32;
        c = (ulong)r[147] + (ulong)N[147] + c; r[147] = (uint)c; c >>= 32;
        c = (ulong)r[148] + (ulong)N[148] + c; r[148] = (uint)c; c >>= 32;
        c = (ulong)r[149] + (ulong)N[149] + c; r[149] = (uint)c; c >>= 32;
        c = (ulong)r[150] + (ulong)N[150] + c; r[150] = (uint)c; c >>= 32;
        c = (ulong)r[151] + (ulong)N[151] + c; r[151] = (uint)c; c >>= 32;
        c = (ulong)r[152] + (ulong)N[152] + c; r[152] = (uint)c; c >>= 32;
        c = (ulong)r[153] + (ulong)N[153] + c; r[153] = (uint)c; c >>= 32;
        c = (ulong)r[154] + (ulong)N[154] + c; r[154] = (uint)c; c >>= 32;
        c = (ulong)r[155] + (ulong)N[155] + c; r[155] = (uint)c; c >>= 32;
        c = (ulong)r[156] + (ulong)N[156] + c; r[156] = (uint)c; c >>= 32;
        c = (ulong)r[157] + (ulong)N[157] + c; r[157] = (uint)c; c >>= 32;
        c = (ulong)r[158] + (ulong)N[158] + c; r[158] = (uint)c; c >>= 32;
        c = (ulong)r[159] + (ulong)N[159] + c; r[159] = (uint)c; c >>= 32;
        c = (ulong)r[160] + (ulong)N[160] + c; r[160] = (uint)c; c >>= 32;
        c = (ulong)r[161] + (ulong)N[161] + c; r[161] = (uint)c; c >>= 32;
        c = (ulong)r[162] + (ulong)N[162] + c; r[162] = (uint)c; c >>= 32;
        c = (ulong)r[163] + (ulong)N[163] + c; r[163] = (uint)c; c >>= 32;
        c = (ulong)r[164] + (ulong)N[164] + c; r[164] = (uint)c; c >>= 32;
        c = (ulong)r[165] + (ulong)N[165] + c; r[165] = (uint)c; c >>= 32;
        c = (ulong)r[166] + (ulong)N[166] + c; r[166] = (uint)c; c >>= 32;
        c = (ulong)r[167] + (ulong)N[167] + c; r[167] = (uint)c; c >>= 32;
        c = (ulong)r[168] + (ulong)N[168] + c; r[168] = (uint)c; c >>= 32;
        c = (ulong)r[169] + (ulong)N[169] + c; r[169] = (uint)c; c >>= 32;
        c = (ulong)r[170] + (ulong)N[170] + c; r[170] = (uint)c; c >>= 32;
        c = (ulong)r[171] + (ulong)N[171] + c; r[171] = (uint)c; c >>= 32;
        c = (ulong)r[172] + (ulong)N[172] + c; r[172] = (uint)c; c >>= 32;
        c = (ulong)r[173] + (ulong)N[173] + c; r[173] = (uint)c; c >>= 32;
        c = (ulong)r[174] + (ulong)N[174] + c; r[174] = (uint)c; c >>= 32;
        c = (ulong)r[175] + (ulong)N[175] + c; r[175] = (uint)c; c >>= 32;
        c = (ulong)r[176] + (ulong)N[176] + c; r[176] = (uint)c; c >>= 32;
        c = (ulong)r[177] + (ulong)N[177] + c; r[177] = (uint)c; c >>= 32;
        c = (ulong)r[178] + (ulong)N[178] + c; r[178] = (uint)c; c >>= 32;
        c = (ulong)r[179] + (ulong)N[179] + c; r[179] = (uint)c; c >>= 32;
        c = (ulong)r[180] + (ulong)N[180] + c; r[180] = (uint)c; c >>= 32;
        c = (ulong)r[181] + (ulong)N[181] + c; r[181] = (uint)c; c >>= 32;
        c = (ulong)r[182] + (ulong)N[182] + c; r[182] = (uint)c; c >>= 32;
        c = (ulong)r[183] + (ulong)N[183] + c; r[183] = (uint)c; c >>= 32;
        c = (ulong)r[184] + (ulong)N[184] + c; r[184] = (uint)c; c >>= 32;
        c = (ulong)r[185] + (ulong)N[185] + c; r[185] = (uint)c; c >>= 32;
        c = (ulong)r[186] + (ulong)N[186] + c; r[186] = (uint)c; c >>= 32;
        c = (ulong)r[187] + (ulong)N[187] + c; r[187] = (uint)c; c >>= 32;
        c = (ulong)r[188] + (ulong)N[188] + c; r[188] = (uint)c; c >>= 32;
        c = (ulong)r[189] + (ulong)N[189] + c; r[189] = (uint)c; c >>= 32;
        c = (ulong)r[190] + (ulong)N[190] + c; r[190] = (uint)c; c >>= 32;
        c = (ulong)r[191] + (ulong)N[191] + c; r[191] = (uint)c; c >>= 32;
        c = (ulong)r[192] + (ulong)N[192] + c; r[192] = (uint)c; c >>= 32;
        c = (ulong)r[193] + (ulong)N[193] + c; r[193] = (uint)c; c >>= 32;
        c = (ulong)r[194] + (ulong)N[194] + c; r[194] = (uint)c; c >>= 32;
        c = (ulong)r[195] + (ulong)N[195] + c; r[195] = (uint)c; c >>= 32;
        c = (ulong)r[196] + (ulong)N[196] + c; r[196] = (uint)c; c >>= 32;
        c = (ulong)r[197] + (ulong)N[197] + c; r[197] = (uint)c; c >>= 32;
        c = (ulong)r[198] + (ulong)N[198] + c; r[198] = (uint)c; c >>= 32;
        c = (ulong)r[199] + (ulong)N[199] + c; r[199] = (uint)c; c >>= 32;
        c = (ulong)r[200] + (ulong)N[200] + c; r[200] = (uint)c; c >>= 32;
        c = (ulong)r[201] + (ulong)N[201] + c; r[201] = (uint)c; c >>= 32;
        c = (ulong)r[202] + (ulong)N[202] + c; r[202] = (uint)c; c >>= 32;
        c = (ulong)r[203] + (ulong)N[203] + c; r[203] = (uint)c; c >>= 32;
        c = (ulong)r[204] + (ulong)N[204] + c; r[204] = (uint)c; c >>= 32;
        c = (ulong)r[205] + (ulong)N[205] + c; r[205] = (uint)c; c >>= 32;
        c = (ulong)r[206] + (ulong)N[206] + c; r[206] = (uint)c; c >>= 32;
        c = (ulong)r[207] + (ulong)N[207] + c; r[207] = (uint)c; c >>= 32;
        c = (ulong)r[208] + (ulong)N[208] + c; r[208] = (uint)c; c >>= 32;
        c = (ulong)r[209] + (ulong)N[209] + c; r[209] = (uint)c; c >>= 32;
        c = (ulong)r[210] + (ulong)N[210] + c; r[210] = (uint)c; c >>= 32;
        c = (ulong)r[211] + (ulong)N[211] + c; r[211] = (uint)c; c >>= 32;
        c = (ulong)r[212] + (ulong)N[212] + c; r[212] = (uint)c; c >>= 32;
        c = (ulong)r[213] + (ulong)N[213] + c; r[213] = (uint)c; c >>= 32;
        c = (ulong)r[214] + (ulong)N[214] + c; r[214] = (uint)c; c >>= 32;
        c = (ulong)r[215] + (ulong)N[215] + c; r[215] = (uint)c; c >>= 32;
        c = (ulong)r[216] + (ulong)N[216] + c; r[216] = (uint)c; c >>= 32;
        c = (ulong)r[217] + (ulong)N[217] + c; r[217] = (uint)c; c >>= 32;
        c = (ulong)r[218] + (ulong)N[218] + c; r[218] = (uint)c; c >>= 32;
        c = (ulong)r[219] + (ulong)N[219] + c; r[219] = (uint)c; c >>= 32;
        c = (ulong)r[220] + (ulong)N[220] + c; r[220] = (uint)c; c >>= 32;
        c = (ulong)r[221] + (ulong)N[221] + c; r[221] = (uint)c; c >>= 32;
        c = (ulong)r[222] + (ulong)N[222] + c; r[222] = (uint)c; c >>= 32;
        c = (ulong)r[223] + (ulong)N[223] + c; r[223] = (uint)c; c >>= 32;
        c = (ulong)r[224] + (ulong)N[224] + c; r[224] = (uint)c; c >>= 32;
        c = (ulong)r[225] + (ulong)N[225] + c; r[225] = (uint)c; c >>= 32;
        c = (ulong)r[226] + (ulong)N[226] + c; r[226] = (uint)c; c >>= 32;
        c = (ulong)r[227] + (ulong)N[227] + c; r[227] = (uint)c; c >>= 32;
        c = (ulong)r[228] + (ulong)N[228] + c; r[228] = (uint)c; c >>= 32;
        c = (ulong)r[229] + (ulong)N[229] + c; r[229] = (uint)c; c >>= 32;
        c = (ulong)r[230] + (ulong)N[230] + c; r[230] = (uint)c; c >>= 32;
        c = (ulong)r[231] + (ulong)N[231] + c; r[231] = (uint)c; c >>= 32;
        c = (ulong)r[232] + (ulong)N[232] + c; r[232] = (uint)c; c >>= 32;
        c = (ulong)r[233] + (ulong)N[233] + c; r[233] = (uint)c; c >>= 32;
        c = (ulong)r[234] + (ulong)N[234] + c; r[234] = (uint)c; c >>= 32;
        c = (ulong)r[235] + (ulong)N[235] + c; r[235] = (uint)c; c >>= 32;
        c = (ulong)r[236] + (ulong)N[236] + c; r[236] = (uint)c; c >>= 32;
        c = (ulong)r[237] + (ulong)N[237] + c; r[237] = (uint)c; c >>= 32;
        c = (ulong)r[238] + (ulong)N[238] + c; r[238] = (uint)c; c >>= 32;
        c = (ulong)r[239] + (ulong)N[239] + c; r[239] = (uint)c; c >>= 32;
        c = (ulong)r[240] + (ulong)N[240] + c; r[240] = (uint)c; c >>= 32;
        c = (ulong)r[241] + (ulong)N[241] + c; r[241] = (uint)c; c >>= 32;
        c = (ulong)r[242] + (ulong)N[242] + c; r[242] = (uint)c; c >>= 32;
        c = (ulong)r[243] + (ulong)N[243] + c; r[243] = (uint)c; c >>= 32;
        c = (ulong)r[244] + (ulong)N[244] + c; r[244] = (uint)c; c >>= 32;
        c = (ulong)r[245] + (ulong)N[245] + c; r[245] = (uint)c; c >>= 32;
        c = (ulong)r[246] + (ulong)N[246] + c; r[246] = (uint)c; c >>= 32;
        c = (ulong)r[247] + (ulong)N[247] + c; r[247] = (uint)c; c >>= 32;
        c = (ulong)r[248] + (ulong)N[248] + c; r[248] = (uint)c; c >>= 32;
        c = (ulong)r[249] + (ulong)N[249] + c; r[249] = (uint)c; c >>= 32;
        c = (ulong)r[250] + (ulong)N[250] + c; r[250] = (uint)c; c >>= 32;
        c = (ulong)r[251] + (ulong)N[251] + c; r[251] = (uint)c; c >>= 32;
        c = (ulong)r[252] + (ulong)N[252] + c; r[252] = (uint)c; c >>= 32;
        c = (ulong)r[253] + (ulong)N[253] + c; r[253] = (uint)c; c >>= 32;
        c = (ulong)r[254] + (ulong)N[254] + c; r[254] = (uint)c; c >>= 32;
        c = (ulong)r[255] + (ulong)N[255] + c; r[255] = (uint)c; c >>= 32;
    }
    return br != 0u ? 1 : 0;
}

#if !defined(__AMDGCN__)
static inline int sub_mod_unroll_8192b_body(uint *r, const uint *a, const uint *b, const uint *N) {
    ulong br = 0ul;
    {
        ulong av = (ulong)a[0];
        ulong bv = (ulong)b[0];
        ulong w = av - bv - br;
        r[0] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[1];
        ulong bv = (ulong)b[1];
        ulong w = av - bv - br;
        r[1] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[2];
        ulong bv = (ulong)b[2];
        ulong w = av - bv - br;
        r[2] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[3];
        ulong bv = (ulong)b[3];
        ulong w = av - bv - br;
        r[3] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[4];
        ulong bv = (ulong)b[4];
        ulong w = av - bv - br;
        r[4] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[5];
        ulong bv = (ulong)b[5];
        ulong w = av - bv - br;
        r[5] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[6];
        ulong bv = (ulong)b[6];
        ulong w = av - bv - br;
        r[6] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[7];
        ulong bv = (ulong)b[7];
        ulong w = av - bv - br;
        r[7] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[8];
        ulong bv = (ulong)b[8];
        ulong w = av - bv - br;
        r[8] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[9];
        ulong bv = (ulong)b[9];
        ulong w = av - bv - br;
        r[9] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[10];
        ulong bv = (ulong)b[10];
        ulong w = av - bv - br;
        r[10] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[11];
        ulong bv = (ulong)b[11];
        ulong w = av - bv - br;
        r[11] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[12];
        ulong bv = (ulong)b[12];
        ulong w = av - bv - br;
        r[12] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[13];
        ulong bv = (ulong)b[13];
        ulong w = av - bv - br;
        r[13] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[14];
        ulong bv = (ulong)b[14];
        ulong w = av - bv - br;
        r[14] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[15];
        ulong bv = (ulong)b[15];
        ulong w = av - bv - br;
        r[15] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[16];
        ulong bv = (ulong)b[16];
        ulong w = av - bv - br;
        r[16] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[17];
        ulong bv = (ulong)b[17];
        ulong w = av - bv - br;
        r[17] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[18];
        ulong bv = (ulong)b[18];
        ulong w = av - bv - br;
        r[18] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[19];
        ulong bv = (ulong)b[19];
        ulong w = av - bv - br;
        r[19] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[20];
        ulong bv = (ulong)b[20];
        ulong w = av - bv - br;
        r[20] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[21];
        ulong bv = (ulong)b[21];
        ulong w = av - bv - br;
        r[21] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[22];
        ulong bv = (ulong)b[22];
        ulong w = av - bv - br;
        r[22] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[23];
        ulong bv = (ulong)b[23];
        ulong w = av - bv - br;
        r[23] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[24];
        ulong bv = (ulong)b[24];
        ulong w = av - bv - br;
        r[24] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[25];
        ulong bv = (ulong)b[25];
        ulong w = av - bv - br;
        r[25] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[26];
        ulong bv = (ulong)b[26];
        ulong w = av - bv - br;
        r[26] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[27];
        ulong bv = (ulong)b[27];
        ulong w = av - bv - br;
        r[27] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[28];
        ulong bv = (ulong)b[28];
        ulong w = av - bv - br;
        r[28] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[29];
        ulong bv = (ulong)b[29];
        ulong w = av - bv - br;
        r[29] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[30];
        ulong bv = (ulong)b[30];
        ulong w = av - bv - br;
        r[30] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[31];
        ulong bv = (ulong)b[31];
        ulong w = av - bv - br;
        r[31] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[32];
        ulong bv = (ulong)b[32];
        ulong w = av - bv - br;
        r[32] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[33];
        ulong bv = (ulong)b[33];
        ulong w = av - bv - br;
        r[33] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[34];
        ulong bv = (ulong)b[34];
        ulong w = av - bv - br;
        r[34] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[35];
        ulong bv = (ulong)b[35];
        ulong w = av - bv - br;
        r[35] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[36];
        ulong bv = (ulong)b[36];
        ulong w = av - bv - br;
        r[36] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[37];
        ulong bv = (ulong)b[37];
        ulong w = av - bv - br;
        r[37] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[38];
        ulong bv = (ulong)b[38];
        ulong w = av - bv - br;
        r[38] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[39];
        ulong bv = (ulong)b[39];
        ulong w = av - bv - br;
        r[39] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[40];
        ulong bv = (ulong)b[40];
        ulong w = av - bv - br;
        r[40] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[41];
        ulong bv = (ulong)b[41];
        ulong w = av - bv - br;
        r[41] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[42];
        ulong bv = (ulong)b[42];
        ulong w = av - bv - br;
        r[42] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[43];
        ulong bv = (ulong)b[43];
        ulong w = av - bv - br;
        r[43] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[44];
        ulong bv = (ulong)b[44];
        ulong w = av - bv - br;
        r[44] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[45];
        ulong bv = (ulong)b[45];
        ulong w = av - bv - br;
        r[45] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[46];
        ulong bv = (ulong)b[46];
        ulong w = av - bv - br;
        r[46] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[47];
        ulong bv = (ulong)b[47];
        ulong w = av - bv - br;
        r[47] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[48];
        ulong bv = (ulong)b[48];
        ulong w = av - bv - br;
        r[48] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[49];
        ulong bv = (ulong)b[49];
        ulong w = av - bv - br;
        r[49] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[50];
        ulong bv = (ulong)b[50];
        ulong w = av - bv - br;
        r[50] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[51];
        ulong bv = (ulong)b[51];
        ulong w = av - bv - br;
        r[51] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[52];
        ulong bv = (ulong)b[52];
        ulong w = av - bv - br;
        r[52] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[53];
        ulong bv = (ulong)b[53];
        ulong w = av - bv - br;
        r[53] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[54];
        ulong bv = (ulong)b[54];
        ulong w = av - bv - br;
        r[54] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[55];
        ulong bv = (ulong)b[55];
        ulong w = av - bv - br;
        r[55] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[56];
        ulong bv = (ulong)b[56];
        ulong w = av - bv - br;
        r[56] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[57];
        ulong bv = (ulong)b[57];
        ulong w = av - bv - br;
        r[57] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[58];
        ulong bv = (ulong)b[58];
        ulong w = av - bv - br;
        r[58] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[59];
        ulong bv = (ulong)b[59];
        ulong w = av - bv - br;
        r[59] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[60];
        ulong bv = (ulong)b[60];
        ulong w = av - bv - br;
        r[60] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[61];
        ulong bv = (ulong)b[61];
        ulong w = av - bv - br;
        r[61] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[62];
        ulong bv = (ulong)b[62];
        ulong w = av - bv - br;
        r[62] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[63];
        ulong bv = (ulong)b[63];
        ulong w = av - bv - br;
        r[63] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[64];
        ulong bv = (ulong)b[64];
        ulong w = av - bv - br;
        r[64] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[65];
        ulong bv = (ulong)b[65];
        ulong w = av - bv - br;
        r[65] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[66];
        ulong bv = (ulong)b[66];
        ulong w = av - bv - br;
        r[66] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[67];
        ulong bv = (ulong)b[67];
        ulong w = av - bv - br;
        r[67] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[68];
        ulong bv = (ulong)b[68];
        ulong w = av - bv - br;
        r[68] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[69];
        ulong bv = (ulong)b[69];
        ulong w = av - bv - br;
        r[69] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[70];
        ulong bv = (ulong)b[70];
        ulong w = av - bv - br;
        r[70] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[71];
        ulong bv = (ulong)b[71];
        ulong w = av - bv - br;
        r[71] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[72];
        ulong bv = (ulong)b[72];
        ulong w = av - bv - br;
        r[72] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[73];
        ulong bv = (ulong)b[73];
        ulong w = av - bv - br;
        r[73] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[74];
        ulong bv = (ulong)b[74];
        ulong w = av - bv - br;
        r[74] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[75];
        ulong bv = (ulong)b[75];
        ulong w = av - bv - br;
        r[75] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[76];
        ulong bv = (ulong)b[76];
        ulong w = av - bv - br;
        r[76] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[77];
        ulong bv = (ulong)b[77];
        ulong w = av - bv - br;
        r[77] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[78];
        ulong bv = (ulong)b[78];
        ulong w = av - bv - br;
        r[78] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[79];
        ulong bv = (ulong)b[79];
        ulong w = av - bv - br;
        r[79] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[80];
        ulong bv = (ulong)b[80];
        ulong w = av - bv - br;
        r[80] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[81];
        ulong bv = (ulong)b[81];
        ulong w = av - bv - br;
        r[81] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[82];
        ulong bv = (ulong)b[82];
        ulong w = av - bv - br;
        r[82] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[83];
        ulong bv = (ulong)b[83];
        ulong w = av - bv - br;
        r[83] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[84];
        ulong bv = (ulong)b[84];
        ulong w = av - bv - br;
        r[84] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[85];
        ulong bv = (ulong)b[85];
        ulong w = av - bv - br;
        r[85] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[86];
        ulong bv = (ulong)b[86];
        ulong w = av - bv - br;
        r[86] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[87];
        ulong bv = (ulong)b[87];
        ulong w = av - bv - br;
        r[87] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[88];
        ulong bv = (ulong)b[88];
        ulong w = av - bv - br;
        r[88] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[89];
        ulong bv = (ulong)b[89];
        ulong w = av - bv - br;
        r[89] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[90];
        ulong bv = (ulong)b[90];
        ulong w = av - bv - br;
        r[90] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[91];
        ulong bv = (ulong)b[91];
        ulong w = av - bv - br;
        r[91] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[92];
        ulong bv = (ulong)b[92];
        ulong w = av - bv - br;
        r[92] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[93];
        ulong bv = (ulong)b[93];
        ulong w = av - bv - br;
        r[93] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[94];
        ulong bv = (ulong)b[94];
        ulong w = av - bv - br;
        r[94] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[95];
        ulong bv = (ulong)b[95];
        ulong w = av - bv - br;
        r[95] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[96];
        ulong bv = (ulong)b[96];
        ulong w = av - bv - br;
        r[96] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[97];
        ulong bv = (ulong)b[97];
        ulong w = av - bv - br;
        r[97] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[98];
        ulong bv = (ulong)b[98];
        ulong w = av - bv - br;
        r[98] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[99];
        ulong bv = (ulong)b[99];
        ulong w = av - bv - br;
        r[99] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[100];
        ulong bv = (ulong)b[100];
        ulong w = av - bv - br;
        r[100] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[101];
        ulong bv = (ulong)b[101];
        ulong w = av - bv - br;
        r[101] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[102];
        ulong bv = (ulong)b[102];
        ulong w = av - bv - br;
        r[102] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[103];
        ulong bv = (ulong)b[103];
        ulong w = av - bv - br;
        r[103] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[104];
        ulong bv = (ulong)b[104];
        ulong w = av - bv - br;
        r[104] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[105];
        ulong bv = (ulong)b[105];
        ulong w = av - bv - br;
        r[105] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[106];
        ulong bv = (ulong)b[106];
        ulong w = av - bv - br;
        r[106] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[107];
        ulong bv = (ulong)b[107];
        ulong w = av - bv - br;
        r[107] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[108];
        ulong bv = (ulong)b[108];
        ulong w = av - bv - br;
        r[108] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[109];
        ulong bv = (ulong)b[109];
        ulong w = av - bv - br;
        r[109] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[110];
        ulong bv = (ulong)b[110];
        ulong w = av - bv - br;
        r[110] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[111];
        ulong bv = (ulong)b[111];
        ulong w = av - bv - br;
        r[111] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[112];
        ulong bv = (ulong)b[112];
        ulong w = av - bv - br;
        r[112] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[113];
        ulong bv = (ulong)b[113];
        ulong w = av - bv - br;
        r[113] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[114];
        ulong bv = (ulong)b[114];
        ulong w = av - bv - br;
        r[114] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[115];
        ulong bv = (ulong)b[115];
        ulong w = av - bv - br;
        r[115] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[116];
        ulong bv = (ulong)b[116];
        ulong w = av - bv - br;
        r[116] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[117];
        ulong bv = (ulong)b[117];
        ulong w = av - bv - br;
        r[117] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[118];
        ulong bv = (ulong)b[118];
        ulong w = av - bv - br;
        r[118] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[119];
        ulong bv = (ulong)b[119];
        ulong w = av - bv - br;
        r[119] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[120];
        ulong bv = (ulong)b[120];
        ulong w = av - bv - br;
        r[120] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[121];
        ulong bv = (ulong)b[121];
        ulong w = av - bv - br;
        r[121] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[122];
        ulong bv = (ulong)b[122];
        ulong w = av - bv - br;
        r[122] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[123];
        ulong bv = (ulong)b[123];
        ulong w = av - bv - br;
        r[123] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[124];
        ulong bv = (ulong)b[124];
        ulong w = av - bv - br;
        r[124] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[125];
        ulong bv = (ulong)b[125];
        ulong w = av - bv - br;
        r[125] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[126];
        ulong bv = (ulong)b[126];
        ulong w = av - bv - br;
        r[126] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[127];
        ulong bv = (ulong)b[127];
        ulong w = av - bv - br;
        r[127] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[128];
        ulong bv = (ulong)b[128];
        ulong w = av - bv - br;
        r[128] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[129];
        ulong bv = (ulong)b[129];
        ulong w = av - bv - br;
        r[129] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[130];
        ulong bv = (ulong)b[130];
        ulong w = av - bv - br;
        r[130] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[131];
        ulong bv = (ulong)b[131];
        ulong w = av - bv - br;
        r[131] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[132];
        ulong bv = (ulong)b[132];
        ulong w = av - bv - br;
        r[132] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[133];
        ulong bv = (ulong)b[133];
        ulong w = av - bv - br;
        r[133] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[134];
        ulong bv = (ulong)b[134];
        ulong w = av - bv - br;
        r[134] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[135];
        ulong bv = (ulong)b[135];
        ulong w = av - bv - br;
        r[135] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[136];
        ulong bv = (ulong)b[136];
        ulong w = av - bv - br;
        r[136] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[137];
        ulong bv = (ulong)b[137];
        ulong w = av - bv - br;
        r[137] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[138];
        ulong bv = (ulong)b[138];
        ulong w = av - bv - br;
        r[138] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[139];
        ulong bv = (ulong)b[139];
        ulong w = av - bv - br;
        r[139] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[140];
        ulong bv = (ulong)b[140];
        ulong w = av - bv - br;
        r[140] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[141];
        ulong bv = (ulong)b[141];
        ulong w = av - bv - br;
        r[141] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[142];
        ulong bv = (ulong)b[142];
        ulong w = av - bv - br;
        r[142] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[143];
        ulong bv = (ulong)b[143];
        ulong w = av - bv - br;
        r[143] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[144];
        ulong bv = (ulong)b[144];
        ulong w = av - bv - br;
        r[144] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[145];
        ulong bv = (ulong)b[145];
        ulong w = av - bv - br;
        r[145] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[146];
        ulong bv = (ulong)b[146];
        ulong w = av - bv - br;
        r[146] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[147];
        ulong bv = (ulong)b[147];
        ulong w = av - bv - br;
        r[147] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[148];
        ulong bv = (ulong)b[148];
        ulong w = av - bv - br;
        r[148] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[149];
        ulong bv = (ulong)b[149];
        ulong w = av - bv - br;
        r[149] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[150];
        ulong bv = (ulong)b[150];
        ulong w = av - bv - br;
        r[150] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[151];
        ulong bv = (ulong)b[151];
        ulong w = av - bv - br;
        r[151] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[152];
        ulong bv = (ulong)b[152];
        ulong w = av - bv - br;
        r[152] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[153];
        ulong bv = (ulong)b[153];
        ulong w = av - bv - br;
        r[153] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[154];
        ulong bv = (ulong)b[154];
        ulong w = av - bv - br;
        r[154] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[155];
        ulong bv = (ulong)b[155];
        ulong w = av - bv - br;
        r[155] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[156];
        ulong bv = (ulong)b[156];
        ulong w = av - bv - br;
        r[156] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[157];
        ulong bv = (ulong)b[157];
        ulong w = av - bv - br;
        r[157] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[158];
        ulong bv = (ulong)b[158];
        ulong w = av - bv - br;
        r[158] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[159];
        ulong bv = (ulong)b[159];
        ulong w = av - bv - br;
        r[159] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[160];
        ulong bv = (ulong)b[160];
        ulong w = av - bv - br;
        r[160] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[161];
        ulong bv = (ulong)b[161];
        ulong w = av - bv - br;
        r[161] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[162];
        ulong bv = (ulong)b[162];
        ulong w = av - bv - br;
        r[162] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[163];
        ulong bv = (ulong)b[163];
        ulong w = av - bv - br;
        r[163] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[164];
        ulong bv = (ulong)b[164];
        ulong w = av - bv - br;
        r[164] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[165];
        ulong bv = (ulong)b[165];
        ulong w = av - bv - br;
        r[165] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[166];
        ulong bv = (ulong)b[166];
        ulong w = av - bv - br;
        r[166] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[167];
        ulong bv = (ulong)b[167];
        ulong w = av - bv - br;
        r[167] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[168];
        ulong bv = (ulong)b[168];
        ulong w = av - bv - br;
        r[168] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[169];
        ulong bv = (ulong)b[169];
        ulong w = av - bv - br;
        r[169] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[170];
        ulong bv = (ulong)b[170];
        ulong w = av - bv - br;
        r[170] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[171];
        ulong bv = (ulong)b[171];
        ulong w = av - bv - br;
        r[171] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[172];
        ulong bv = (ulong)b[172];
        ulong w = av - bv - br;
        r[172] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[173];
        ulong bv = (ulong)b[173];
        ulong w = av - bv - br;
        r[173] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[174];
        ulong bv = (ulong)b[174];
        ulong w = av - bv - br;
        r[174] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[175];
        ulong bv = (ulong)b[175];
        ulong w = av - bv - br;
        r[175] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[176];
        ulong bv = (ulong)b[176];
        ulong w = av - bv - br;
        r[176] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[177];
        ulong bv = (ulong)b[177];
        ulong w = av - bv - br;
        r[177] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[178];
        ulong bv = (ulong)b[178];
        ulong w = av - bv - br;
        r[178] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[179];
        ulong bv = (ulong)b[179];
        ulong w = av - bv - br;
        r[179] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[180];
        ulong bv = (ulong)b[180];
        ulong w = av - bv - br;
        r[180] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[181];
        ulong bv = (ulong)b[181];
        ulong w = av - bv - br;
        r[181] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[182];
        ulong bv = (ulong)b[182];
        ulong w = av - bv - br;
        r[182] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[183];
        ulong bv = (ulong)b[183];
        ulong w = av - bv - br;
        r[183] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[184];
        ulong bv = (ulong)b[184];
        ulong w = av - bv - br;
        r[184] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[185];
        ulong bv = (ulong)b[185];
        ulong w = av - bv - br;
        r[185] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[186];
        ulong bv = (ulong)b[186];
        ulong w = av - bv - br;
        r[186] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[187];
        ulong bv = (ulong)b[187];
        ulong w = av - bv - br;
        r[187] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[188];
        ulong bv = (ulong)b[188];
        ulong w = av - bv - br;
        r[188] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[189];
        ulong bv = (ulong)b[189];
        ulong w = av - bv - br;
        r[189] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[190];
        ulong bv = (ulong)b[190];
        ulong w = av - bv - br;
        r[190] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[191];
        ulong bv = (ulong)b[191];
        ulong w = av - bv - br;
        r[191] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[192];
        ulong bv = (ulong)b[192];
        ulong w = av - bv - br;
        r[192] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[193];
        ulong bv = (ulong)b[193];
        ulong w = av - bv - br;
        r[193] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[194];
        ulong bv = (ulong)b[194];
        ulong w = av - bv - br;
        r[194] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[195];
        ulong bv = (ulong)b[195];
        ulong w = av - bv - br;
        r[195] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[196];
        ulong bv = (ulong)b[196];
        ulong w = av - bv - br;
        r[196] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[197];
        ulong bv = (ulong)b[197];
        ulong w = av - bv - br;
        r[197] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[198];
        ulong bv = (ulong)b[198];
        ulong w = av - bv - br;
        r[198] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[199];
        ulong bv = (ulong)b[199];
        ulong w = av - bv - br;
        r[199] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[200];
        ulong bv = (ulong)b[200];
        ulong w = av - bv - br;
        r[200] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[201];
        ulong bv = (ulong)b[201];
        ulong w = av - bv - br;
        r[201] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[202];
        ulong bv = (ulong)b[202];
        ulong w = av - bv - br;
        r[202] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[203];
        ulong bv = (ulong)b[203];
        ulong w = av - bv - br;
        r[203] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[204];
        ulong bv = (ulong)b[204];
        ulong w = av - bv - br;
        r[204] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[205];
        ulong bv = (ulong)b[205];
        ulong w = av - bv - br;
        r[205] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[206];
        ulong bv = (ulong)b[206];
        ulong w = av - bv - br;
        r[206] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[207];
        ulong bv = (ulong)b[207];
        ulong w = av - bv - br;
        r[207] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[208];
        ulong bv = (ulong)b[208];
        ulong w = av - bv - br;
        r[208] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[209];
        ulong bv = (ulong)b[209];
        ulong w = av - bv - br;
        r[209] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[210];
        ulong bv = (ulong)b[210];
        ulong w = av - bv - br;
        r[210] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[211];
        ulong bv = (ulong)b[211];
        ulong w = av - bv - br;
        r[211] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[212];
        ulong bv = (ulong)b[212];
        ulong w = av - bv - br;
        r[212] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[213];
        ulong bv = (ulong)b[213];
        ulong w = av - bv - br;
        r[213] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[214];
        ulong bv = (ulong)b[214];
        ulong w = av - bv - br;
        r[214] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[215];
        ulong bv = (ulong)b[215];
        ulong w = av - bv - br;
        r[215] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[216];
        ulong bv = (ulong)b[216];
        ulong w = av - bv - br;
        r[216] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[217];
        ulong bv = (ulong)b[217];
        ulong w = av - bv - br;
        r[217] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[218];
        ulong bv = (ulong)b[218];
        ulong w = av - bv - br;
        r[218] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[219];
        ulong bv = (ulong)b[219];
        ulong w = av - bv - br;
        r[219] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[220];
        ulong bv = (ulong)b[220];
        ulong w = av - bv - br;
        r[220] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[221];
        ulong bv = (ulong)b[221];
        ulong w = av - bv - br;
        r[221] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[222];
        ulong bv = (ulong)b[222];
        ulong w = av - bv - br;
        r[222] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[223];
        ulong bv = (ulong)b[223];
        ulong w = av - bv - br;
        r[223] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[224];
        ulong bv = (ulong)b[224];
        ulong w = av - bv - br;
        r[224] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[225];
        ulong bv = (ulong)b[225];
        ulong w = av - bv - br;
        r[225] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[226];
        ulong bv = (ulong)b[226];
        ulong w = av - bv - br;
        r[226] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[227];
        ulong bv = (ulong)b[227];
        ulong w = av - bv - br;
        r[227] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[228];
        ulong bv = (ulong)b[228];
        ulong w = av - bv - br;
        r[228] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[229];
        ulong bv = (ulong)b[229];
        ulong w = av - bv - br;
        r[229] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[230];
        ulong bv = (ulong)b[230];
        ulong w = av - bv - br;
        r[230] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[231];
        ulong bv = (ulong)b[231];
        ulong w = av - bv - br;
        r[231] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[232];
        ulong bv = (ulong)b[232];
        ulong w = av - bv - br;
        r[232] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[233];
        ulong bv = (ulong)b[233];
        ulong w = av - bv - br;
        r[233] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[234];
        ulong bv = (ulong)b[234];
        ulong w = av - bv - br;
        r[234] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[235];
        ulong bv = (ulong)b[235];
        ulong w = av - bv - br;
        r[235] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[236];
        ulong bv = (ulong)b[236];
        ulong w = av - bv - br;
        r[236] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[237];
        ulong bv = (ulong)b[237];
        ulong w = av - bv - br;
        r[237] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[238];
        ulong bv = (ulong)b[238];
        ulong w = av - bv - br;
        r[238] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[239];
        ulong bv = (ulong)b[239];
        ulong w = av - bv - br;
        r[239] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[240];
        ulong bv = (ulong)b[240];
        ulong w = av - bv - br;
        r[240] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[241];
        ulong bv = (ulong)b[241];
        ulong w = av - bv - br;
        r[241] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[242];
        ulong bv = (ulong)b[242];
        ulong w = av - bv - br;
        r[242] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[243];
        ulong bv = (ulong)b[243];
        ulong w = av - bv - br;
        r[243] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[244];
        ulong bv = (ulong)b[244];
        ulong w = av - bv - br;
        r[244] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[245];
        ulong bv = (ulong)b[245];
        ulong w = av - bv - br;
        r[245] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[246];
        ulong bv = (ulong)b[246];
        ulong w = av - bv - br;
        r[246] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[247];
        ulong bv = (ulong)b[247];
        ulong w = av - bv - br;
        r[247] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[248];
        ulong bv = (ulong)b[248];
        ulong w = av - bv - br;
        r[248] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[249];
        ulong bv = (ulong)b[249];
        ulong w = av - bv - br;
        r[249] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[250];
        ulong bv = (ulong)b[250];
        ulong w = av - bv - br;
        r[250] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[251];
        ulong bv = (ulong)b[251];
        ulong w = av - bv - br;
        r[251] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[252];
        ulong bv = (ulong)b[252];
        ulong w = av - bv - br;
        r[252] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[253];
        ulong bv = (ulong)b[253];
        ulong w = av - bv - br;
        r[253] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[254];
        ulong bv = (ulong)b[254];
        ulong w = av - bv - br;
        r[254] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[255];
        ulong bv = (ulong)b[255];
        ulong w = av - bv - br;
        r[255] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    if (br != 0ul) {
        ulong c = 0ul;
        {
            ulong s = (ulong)r[0] + (ulong)N[0] + c;
            r[0] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[1] + (ulong)N[1] + c;
            r[1] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[2] + (ulong)N[2] + c;
            r[2] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[3] + (ulong)N[3] + c;
            r[3] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[4] + (ulong)N[4] + c;
            r[4] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[5] + (ulong)N[5] + c;
            r[5] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[6] + (ulong)N[6] + c;
            r[6] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[7] + (ulong)N[7] + c;
            r[7] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[8] + (ulong)N[8] + c;
            r[8] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[9] + (ulong)N[9] + c;
            r[9] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[10] + (ulong)N[10] + c;
            r[10] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[11] + (ulong)N[11] + c;
            r[11] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[12] + (ulong)N[12] + c;
            r[12] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[13] + (ulong)N[13] + c;
            r[13] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[14] + (ulong)N[14] + c;
            r[14] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[15] + (ulong)N[15] + c;
            r[15] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[16] + (ulong)N[16] + c;
            r[16] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[17] + (ulong)N[17] + c;
            r[17] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[18] + (ulong)N[18] + c;
            r[18] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[19] + (ulong)N[19] + c;
            r[19] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[20] + (ulong)N[20] + c;
            r[20] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[21] + (ulong)N[21] + c;
            r[21] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[22] + (ulong)N[22] + c;
            r[22] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[23] + (ulong)N[23] + c;
            r[23] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[24] + (ulong)N[24] + c;
            r[24] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[25] + (ulong)N[25] + c;
            r[25] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[26] + (ulong)N[26] + c;
            r[26] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[27] + (ulong)N[27] + c;
            r[27] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[28] + (ulong)N[28] + c;
            r[28] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[29] + (ulong)N[29] + c;
            r[29] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[30] + (ulong)N[30] + c;
            r[30] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[31] + (ulong)N[31] + c;
            r[31] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[32] + (ulong)N[32] + c;
            r[32] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[33] + (ulong)N[33] + c;
            r[33] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[34] + (ulong)N[34] + c;
            r[34] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[35] + (ulong)N[35] + c;
            r[35] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[36] + (ulong)N[36] + c;
            r[36] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[37] + (ulong)N[37] + c;
            r[37] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[38] + (ulong)N[38] + c;
            r[38] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[39] + (ulong)N[39] + c;
            r[39] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[40] + (ulong)N[40] + c;
            r[40] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[41] + (ulong)N[41] + c;
            r[41] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[42] + (ulong)N[42] + c;
            r[42] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[43] + (ulong)N[43] + c;
            r[43] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[44] + (ulong)N[44] + c;
            r[44] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[45] + (ulong)N[45] + c;
            r[45] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[46] + (ulong)N[46] + c;
            r[46] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[47] + (ulong)N[47] + c;
            r[47] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[48] + (ulong)N[48] + c;
            r[48] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[49] + (ulong)N[49] + c;
            r[49] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[50] + (ulong)N[50] + c;
            r[50] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[51] + (ulong)N[51] + c;
            r[51] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[52] + (ulong)N[52] + c;
            r[52] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[53] + (ulong)N[53] + c;
            r[53] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[54] + (ulong)N[54] + c;
            r[54] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[55] + (ulong)N[55] + c;
            r[55] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[56] + (ulong)N[56] + c;
            r[56] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[57] + (ulong)N[57] + c;
            r[57] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[58] + (ulong)N[58] + c;
            r[58] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[59] + (ulong)N[59] + c;
            r[59] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[60] + (ulong)N[60] + c;
            r[60] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[61] + (ulong)N[61] + c;
            r[61] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[62] + (ulong)N[62] + c;
            r[62] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[63] + (ulong)N[63] + c;
            r[63] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[64] + (ulong)N[64] + c;
            r[64] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[65] + (ulong)N[65] + c;
            r[65] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[66] + (ulong)N[66] + c;
            r[66] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[67] + (ulong)N[67] + c;
            r[67] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[68] + (ulong)N[68] + c;
            r[68] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[69] + (ulong)N[69] + c;
            r[69] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[70] + (ulong)N[70] + c;
            r[70] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[71] + (ulong)N[71] + c;
            r[71] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[72] + (ulong)N[72] + c;
            r[72] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[73] + (ulong)N[73] + c;
            r[73] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[74] + (ulong)N[74] + c;
            r[74] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[75] + (ulong)N[75] + c;
            r[75] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[76] + (ulong)N[76] + c;
            r[76] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[77] + (ulong)N[77] + c;
            r[77] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[78] + (ulong)N[78] + c;
            r[78] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[79] + (ulong)N[79] + c;
            r[79] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[80] + (ulong)N[80] + c;
            r[80] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[81] + (ulong)N[81] + c;
            r[81] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[82] + (ulong)N[82] + c;
            r[82] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[83] + (ulong)N[83] + c;
            r[83] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[84] + (ulong)N[84] + c;
            r[84] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[85] + (ulong)N[85] + c;
            r[85] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[86] + (ulong)N[86] + c;
            r[86] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[87] + (ulong)N[87] + c;
            r[87] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[88] + (ulong)N[88] + c;
            r[88] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[89] + (ulong)N[89] + c;
            r[89] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[90] + (ulong)N[90] + c;
            r[90] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[91] + (ulong)N[91] + c;
            r[91] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[92] + (ulong)N[92] + c;
            r[92] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[93] + (ulong)N[93] + c;
            r[93] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[94] + (ulong)N[94] + c;
            r[94] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[95] + (ulong)N[95] + c;
            r[95] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[96] + (ulong)N[96] + c;
            r[96] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[97] + (ulong)N[97] + c;
            r[97] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[98] + (ulong)N[98] + c;
            r[98] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[99] + (ulong)N[99] + c;
            r[99] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[100] + (ulong)N[100] + c;
            r[100] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[101] + (ulong)N[101] + c;
            r[101] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[102] + (ulong)N[102] + c;
            r[102] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[103] + (ulong)N[103] + c;
            r[103] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[104] + (ulong)N[104] + c;
            r[104] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[105] + (ulong)N[105] + c;
            r[105] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[106] + (ulong)N[106] + c;
            r[106] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[107] + (ulong)N[107] + c;
            r[107] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[108] + (ulong)N[108] + c;
            r[108] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[109] + (ulong)N[109] + c;
            r[109] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[110] + (ulong)N[110] + c;
            r[110] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[111] + (ulong)N[111] + c;
            r[111] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[112] + (ulong)N[112] + c;
            r[112] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[113] + (ulong)N[113] + c;
            r[113] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[114] + (ulong)N[114] + c;
            r[114] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[115] + (ulong)N[115] + c;
            r[115] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[116] + (ulong)N[116] + c;
            r[116] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[117] + (ulong)N[117] + c;
            r[117] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[118] + (ulong)N[118] + c;
            r[118] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[119] + (ulong)N[119] + c;
            r[119] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[120] + (ulong)N[120] + c;
            r[120] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[121] + (ulong)N[121] + c;
            r[121] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[122] + (ulong)N[122] + c;
            r[122] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[123] + (ulong)N[123] + c;
            r[123] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[124] + (ulong)N[124] + c;
            r[124] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[125] + (ulong)N[125] + c;
            r[125] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[126] + (ulong)N[126] + c;
            r[126] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[127] + (ulong)N[127] + c;
            r[127] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[128] + (ulong)N[128] + c;
            r[128] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[129] + (ulong)N[129] + c;
            r[129] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[130] + (ulong)N[130] + c;
            r[130] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[131] + (ulong)N[131] + c;
            r[131] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[132] + (ulong)N[132] + c;
            r[132] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[133] + (ulong)N[133] + c;
            r[133] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[134] + (ulong)N[134] + c;
            r[134] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[135] + (ulong)N[135] + c;
            r[135] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[136] + (ulong)N[136] + c;
            r[136] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[137] + (ulong)N[137] + c;
            r[137] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[138] + (ulong)N[138] + c;
            r[138] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[139] + (ulong)N[139] + c;
            r[139] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[140] + (ulong)N[140] + c;
            r[140] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[141] + (ulong)N[141] + c;
            r[141] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[142] + (ulong)N[142] + c;
            r[142] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[143] + (ulong)N[143] + c;
            r[143] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[144] + (ulong)N[144] + c;
            r[144] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[145] + (ulong)N[145] + c;
            r[145] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[146] + (ulong)N[146] + c;
            r[146] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[147] + (ulong)N[147] + c;
            r[147] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[148] + (ulong)N[148] + c;
            r[148] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[149] + (ulong)N[149] + c;
            r[149] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[150] + (ulong)N[150] + c;
            r[150] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[151] + (ulong)N[151] + c;
            r[151] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[152] + (ulong)N[152] + c;
            r[152] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[153] + (ulong)N[153] + c;
            r[153] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[154] + (ulong)N[154] + c;
            r[154] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[155] + (ulong)N[155] + c;
            r[155] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[156] + (ulong)N[156] + c;
            r[156] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[157] + (ulong)N[157] + c;
            r[157] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[158] + (ulong)N[158] + c;
            r[158] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[159] + (ulong)N[159] + c;
            r[159] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[160] + (ulong)N[160] + c;
            r[160] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[161] + (ulong)N[161] + c;
            r[161] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[162] + (ulong)N[162] + c;
            r[162] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[163] + (ulong)N[163] + c;
            r[163] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[164] + (ulong)N[164] + c;
            r[164] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[165] + (ulong)N[165] + c;
            r[165] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[166] + (ulong)N[166] + c;
            r[166] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[167] + (ulong)N[167] + c;
            r[167] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[168] + (ulong)N[168] + c;
            r[168] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[169] + (ulong)N[169] + c;
            r[169] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[170] + (ulong)N[170] + c;
            r[170] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[171] + (ulong)N[171] + c;
            r[171] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[172] + (ulong)N[172] + c;
            r[172] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[173] + (ulong)N[173] + c;
            r[173] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[174] + (ulong)N[174] + c;
            r[174] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[175] + (ulong)N[175] + c;
            r[175] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[176] + (ulong)N[176] + c;
            r[176] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[177] + (ulong)N[177] + c;
            r[177] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[178] + (ulong)N[178] + c;
            r[178] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[179] + (ulong)N[179] + c;
            r[179] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[180] + (ulong)N[180] + c;
            r[180] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[181] + (ulong)N[181] + c;
            r[181] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[182] + (ulong)N[182] + c;
            r[182] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[183] + (ulong)N[183] + c;
            r[183] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[184] + (ulong)N[184] + c;
            r[184] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[185] + (ulong)N[185] + c;
            r[185] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[186] + (ulong)N[186] + c;
            r[186] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[187] + (ulong)N[187] + c;
            r[187] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[188] + (ulong)N[188] + c;
            r[188] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[189] + (ulong)N[189] + c;
            r[189] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[190] + (ulong)N[190] + c;
            r[190] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[191] + (ulong)N[191] + c;
            r[191] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[192] + (ulong)N[192] + c;
            r[192] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[193] + (ulong)N[193] + c;
            r[193] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[194] + (ulong)N[194] + c;
            r[194] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[195] + (ulong)N[195] + c;
            r[195] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[196] + (ulong)N[196] + c;
            r[196] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[197] + (ulong)N[197] + c;
            r[197] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[198] + (ulong)N[198] + c;
            r[198] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[199] + (ulong)N[199] + c;
            r[199] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[200] + (ulong)N[200] + c;
            r[200] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[201] + (ulong)N[201] + c;
            r[201] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[202] + (ulong)N[202] + c;
            r[202] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[203] + (ulong)N[203] + c;
            r[203] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[204] + (ulong)N[204] + c;
            r[204] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[205] + (ulong)N[205] + c;
            r[205] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[206] + (ulong)N[206] + c;
            r[206] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[207] + (ulong)N[207] + c;
            r[207] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[208] + (ulong)N[208] + c;
            r[208] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[209] + (ulong)N[209] + c;
            r[209] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[210] + (ulong)N[210] + c;
            r[210] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[211] + (ulong)N[211] + c;
            r[211] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[212] + (ulong)N[212] + c;
            r[212] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[213] + (ulong)N[213] + c;
            r[213] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[214] + (ulong)N[214] + c;
            r[214] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[215] + (ulong)N[215] + c;
            r[215] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[216] + (ulong)N[216] + c;
            r[216] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[217] + (ulong)N[217] + c;
            r[217] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[218] + (ulong)N[218] + c;
            r[218] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[219] + (ulong)N[219] + c;
            r[219] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[220] + (ulong)N[220] + c;
            r[220] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[221] + (ulong)N[221] + c;
            r[221] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[222] + (ulong)N[222] + c;
            r[222] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[223] + (ulong)N[223] + c;
            r[223] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[224] + (ulong)N[224] + c;
            r[224] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[225] + (ulong)N[225] + c;
            r[225] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[226] + (ulong)N[226] + c;
            r[226] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[227] + (ulong)N[227] + c;
            r[227] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[228] + (ulong)N[228] + c;
            r[228] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[229] + (ulong)N[229] + c;
            r[229] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[230] + (ulong)N[230] + c;
            r[230] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[231] + (ulong)N[231] + c;
            r[231] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[232] + (ulong)N[232] + c;
            r[232] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[233] + (ulong)N[233] + c;
            r[233] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[234] + (ulong)N[234] + c;
            r[234] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[235] + (ulong)N[235] + c;
            r[235] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[236] + (ulong)N[236] + c;
            r[236] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[237] + (ulong)N[237] + c;
            r[237] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[238] + (ulong)N[238] + c;
            r[238] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[239] + (ulong)N[239] + c;
            r[239] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[240] + (ulong)N[240] + c;
            r[240] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[241] + (ulong)N[241] + c;
            r[241] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[242] + (ulong)N[242] + c;
            r[242] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[243] + (ulong)N[243] + c;
            r[243] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[244] + (ulong)N[244] + c;
            r[244] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[245] + (ulong)N[245] + c;
            r[245] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[246] + (ulong)N[246] + c;
            r[246] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[247] + (ulong)N[247] + c;
            r[247] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[248] + (ulong)N[248] + c;
            r[248] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[249] + (ulong)N[249] + c;
            r[249] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[250] + (ulong)N[250] + c;
            r[250] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[251] + (ulong)N[251] + c;
            r[251] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[252] + (ulong)N[252] + c;
            r[252] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[253] + (ulong)N[253] + c;
            r[253] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[254] + (ulong)N[254] + c;
            r[254] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[255] + (ulong)N[255] + c;
            r[255] = (uint)s;
            c = s >> 32;
        }
        return 1;
    }
    return 0;
}

#endif
#if defined(__AMDGCN__)
static inline int sub_mod_asm_8192b(uint *r, const uint *a, const uint *b,
                                      const uint *N, uint limbs) {
    if (limbs == 256u) { return sub_mod_asm_8192b_body(r, a, b, N); }
    return 0;
}
#else
static inline int sub_mod_asm_8192b(uint *r, const uint *a, const uint *b,
                                      const uint *N, uint limbs) {
    if (limbs == 256u) { return sub_mod_unroll_8192b_body(r, a, b, N); }
    return 0;
}
#endif
