// AUTO-GENERATED by tools/gen_special_mult_unroll.py - do not edit.
// Stage1 special_mult — 256-bit unroll-only (R = 2^32).
// Unrolled single-limb CIOS with 8 hardcoded limbs.
// Inlined into ecm_stage1.cl when MAX_LIMBS <= 8.
static inline void special_mult_ui32_unroll_256b(uint *r, uint m,
        const uint *N, uint np0, uint limbs) {
    uint t[9u];
    #pragma unroll
    for (uint i = 0u; i < 8u; ++i) t[i] = 0u;

    // 1) product: t = r * m
    {
        ulong carry = 0ul;
        #pragma unroll
        for (uint j = 0u; j < 8u; ++j) {
            ulong uv = (ulong)t[j] + (ulong)m * (ulong)r[j] + carry;
            t[j] = (uint)uv;
            carry = uv >> 32;
        }
        t[8u] = (uint)carry;
    }

    // 2) reduction + implicit >>32 (CIOS standard)
    {
        uint mp = (uint)((ulong)t[0] * (ulong)np0);
        ulong carry = 0ul;
        #pragma unroll
        for (uint j = 0u; j < 8u; ++j) {
            ulong uv = (ulong)t[j] + (ulong)mp * (ulong)N[j] + carry;
            if (j > 0u) t[j - 1u] = (uint)uv;
            carry = uv >> 32;
        }
        ulong top = (ulong)t[8u] + carry;
        t[7u] = (uint)top;
        t[8u] = (uint)(top >> 32);
    }

    // 3) branchless conditional subtraction
    {
        ulong borrow = 0ul;
        uint D[8u];
        #pragma unroll
        for (uint i = 0u; i < 8u; ++i) {
            ulong tv = (ulong)t[i], nv = (ulong)N[i];
            ulong w = tv - nv - borrow;
            D[i] = (uint)w;
            borrow = (tv < nv + borrow) ? 1ul : 0ul;
        }
        uint need_sub = (t[8u] != 0u) ? 1u : (borrow == 0ul ? 1u : 0u);
        uint mask = 0u - need_sub;
        #pragma unroll
        for (uint i = 0u; i < 8u; ++i) {
            r[i] = (D[i] & mask) | (t[i] & ~mask);
        }
    }
    (void)limbs;
}
