// AUTO-GENERATED by tools/gen_mp_addsub_bits_stage1.py - do not edit.
static inline int mp_sub_mod_unroll_384b(uint *r, const uint *a, const uint *b, const uint *N) {
    ulong br = 0ul;
    {
        ulong av = (ulong)a[0];
        ulong bv = (ulong)b[0];
        ulong w = av - bv - br;
        r[0] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[1];
        ulong bv = (ulong)b[1];
        ulong w = av - bv - br;
        r[1] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[2];
        ulong bv = (ulong)b[2];
        ulong w = av - bv - br;
        r[2] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[3];
        ulong bv = (ulong)b[3];
        ulong w = av - bv - br;
        r[3] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[4];
        ulong bv = (ulong)b[4];
        ulong w = av - bv - br;
        r[4] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[5];
        ulong bv = (ulong)b[5];
        ulong w = av - bv - br;
        r[5] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[6];
        ulong bv = (ulong)b[6];
        ulong w = av - bv - br;
        r[6] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[7];
        ulong bv = (ulong)b[7];
        ulong w = av - bv - br;
        r[7] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[8];
        ulong bv = (ulong)b[8];
        ulong w = av - bv - br;
        r[8] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[9];
        ulong bv = (ulong)b[9];
        ulong w = av - bv - br;
        r[9] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[10];
        ulong bv = (ulong)b[10];
        ulong w = av - bv - br;
        r[10] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    {
        ulong av = (ulong)a[11];
        ulong bv = (ulong)b[11];
        ulong w = av - bv - br;
        r[11] = (uint)w;
        br = (av < bv + br) ? 1ul : 0ul;
    }
    if (br != 0ul) {
        ulong c = 0ul;
        {
            ulong s = (ulong)r[0] + (ulong)N[0] + c;
            r[0] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[1] + (ulong)N[1] + c;
            r[1] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[2] + (ulong)N[2] + c;
            r[2] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[3] + (ulong)N[3] + c;
            r[3] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[4] + (ulong)N[4] + c;
            r[4] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[5] + (ulong)N[5] + c;
            r[5] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[6] + (ulong)N[6] + c;
            r[6] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[7] + (ulong)N[7] + c;
            r[7] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[8] + (ulong)N[8] + c;
            r[8] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[9] + (ulong)N[9] + c;
            r[9] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[10] + (ulong)N[10] + c;
            r[10] = (uint)s;
            c = s >> 32;
        }
        {
            ulong s = (ulong)r[11] + (ulong)N[11] + c;
            r[11] = (uint)s;
            c = s >> 32;
        }
        return 1;
    }
    return 0;
}

static inline int ecm_stage1_sub_mod(uint *r, const uint *a, const uint *b,
                                       const uint *N, uint limbs) {
    if (limbs == 16u) { return mp_sub_mod_unroll_384b(r, a, b, N); }
    return 0;
}
