#!/usr/bin/env python3
"""Generate stage1 add/sub bit-width paths as per-id files under add_mod/ and sub_mod/."""

from __future__ import annotations

from pathlib import Path

from mp_asm_block_gen import emit_add_block, emit_c_fix_add, emit_sub_block

ROOT = Path(__file__).resolve().parents[1]
ADD_BITS = ROOT / "kernels/opencl/add_mod/bits"
SUB_BITS = ROOT / "kernels/opencl/sub_mod/bits"

WIDTHS = (
    (128, 4, 128),
    (192, 6, 192),
    (256, 8, 256),
    (384, 12, 378),
)


def emit_add_unroll(limbs: int, bits: int) -> str:
    lines = [
        f"static inline void mp_add_mod_unroll_{bits}b(uint *r, const uint *a, const uint *b, const uint *N) {{\n",
        "    ulong carry_add = 0ul;\n",
        "    ulong carry_sub = 1ul;\n",
    ]
    for i in range(limbs):
        lines.append(
            f"    {{\n"
            f"        ulong sum = (ulong)a[{i}] + (ulong)b[{i}] + carry_add;\n"
            f"        carry_add = sum >> 32;\n"
            f"        ulong temp = (ulong)(uint)sum + (ulong)(~N[{i}]) + carry_sub;\n"
            f"        carry_sub = temp >> 32;\n"
            f"        r[{i}] = (uint)temp;\n"
            f"    }}\n"
        )
    lines.append("    if ((carry_add | carry_sub) != 0ul) {\n        return;\n    }\n")
    lines.append("    ulong c = 0ul;\n")
    for i in range(limbs):
        lines.append(
            f"    {{\n"
            f"        ulong s = (ulong)r[{i}] + (ulong)N[{i}] + c;\n"
            f"        r[{i}] = (uint)s;\n"
            f"        c = s >> 32;\n"
            f"    }}\n"
        )
    lines.append("}\n\n")
    return "".join(lines)


def emit_sub_unroll(limbs: int, bits: int) -> str:
    lines = [
        f"static inline int mp_sub_mod_unroll_{bits}b(uint *r, const uint *a, const uint *b, const uint *N) {{\n",
        "    ulong br = 0ul;\n",
    ]
    for i in range(limbs):
        lines.append(
            f"    {{\n"
            f"        ulong av = (ulong)a[{i}];\n"
            f"        ulong bv = (ulong)b[{i}];\n"
            f"        ulong w = av - bv - br;\n"
            f"        r[{i}] = (uint)w;\n"
            f"        br = (av < bv + br) ? 1ul : 0ul;\n"
            f"    }}\n"
        )
    lines.append("    if (br != 0ul) {\n        ulong c = 0ul;\n")
    for i in range(limbs):
        lines.append(
            f"        {{\n"
            f"            ulong s = (ulong)r[{i}] + (ulong)N[{i}] + c;\n"
            f"            r[{i}] = (uint)s;\n"
            f"            c = s >> 32;\n"
            f"        }}\n"
        )
    lines.append("        return 1;\n    }\n    return 0;\n}\n\n")
    return "".join(lines)


def emit_asm_wrappers(limbs: int, bits: int) -> str:
    return (
        f"static inline void mp_add_mod_asm_{bits}b(uint *r, const uint *a, const uint *b, const uint *N) {{\n"
        f"    uint ca = 0u, cs = 1u;\n"
        f"    asm_fused_block{limbs}_priv(a, b, N, r, ca, cs, &ca, &cs);\n"
        f"}}\n\n"
        f"static inline int mp_sub_mod_asm_{bits}b(uint *r, const uint *a, const uint *b, const uint *N) {{\n"
        f"    uint br = 0u;\n"
        f"    asm_sub_fused_block{limbs}_priv(a, b, N, r, br, &br);\n"
        f"    return br != 0u ? 1 : 0;\n"
        f"}}\n\n"
    )


def write_add_bits(bits: int, body: str) -> None:
    path = ADD_BITS / f"unroll_{bits}b.cl"
    path.parent.mkdir(parents=True, exist_ok=True)
    wrapper = (
        f"static inline void ecm_stage1_add_mod(uint *r, const uint *a, const uint *b,\n"
        f"                                        const uint *N, uint limbs) {{\n"
        f"    if (limbs == 16u) {{ mp_add_mod_unroll_{bits}b(r, a, b, N); }}\n"
        f"    (void)limbs;\n"
        f"}}\n"
    )
    path.write_text(
        f"// AUTO-GENERATED by tools/gen_mp_addsub_bits_stage1.py - do not edit.\n{body}{wrapper}",
        encoding="utf-8",
    )
    print(f"Wrote {path}")


def write_sub_bits(bits: int, body: str) -> None:
    path = SUB_BITS / f"unroll_{bits}b.cl"
    path.parent.mkdir(parents=True, exist_ok=True)
    wrapper = (
        f"static inline int ecm_stage1_sub_mod(uint *r, const uint *a, const uint *b,\n"
        f"                                       const uint *N, uint limbs) {{\n"
        f"    if (limbs == 16u) {{ return mp_sub_mod_unroll_{bits}b(r, a, b, N); }}\n"
        f"    return 0;\n"
        f"}}\n"
    )
    path.write_text(
        f"// AUTO-GENERATED by tools/gen_mp_addsub_bits_stage1.py - do not edit.\n{body}{wrapper}",
        encoding="utf-8",
    )
    print(f"Wrote {path}")


def write_add_asm(bits: int, limbs: int, body: str) -> None:
    path = ADD_BITS / f"asm_{bits}b.cl"
    wrapper = (
        f"#if defined(__AMDGCN__)\n"
        f"static inline void ecm_stage1_add_mod(uint *r, const uint *a, const uint *b,\n"
        f"                                        const uint *N, uint limbs) {{\n"
        f"    if (limbs == 16u) {{ mp_add_mod_asm_{bits}b(r, a, b, N); }}\n"
        f"    (void)limbs;\n"
        f"}}\n"
        f"#else\n"
        f"static inline void ecm_stage1_add_mod(uint *r, const uint *a, const uint *b,\n"
        f"                                        const uint *N, uint limbs) {{\n"
        f"    if (limbs == 16u) {{ mp_add_mod_unroll_{bits}b(r, a, b, N); }}\n"
        f"    (void)limbs;\n"
        f"}}\n"
        f"#endif\n"
    )
    path.write_text(
        f"// AUTO-GENERATED by tools/gen_mp_addsub_bits_stage1.py - do not edit.\n{body}{wrapper}",
        encoding="utf-8",
    )
    print(f"Wrote {path}")


def write_sub_asm(bits: int, body: str) -> None:
    path = SUB_BITS / f"asm_{bits}b.cl"
    wrapper = (
        f"#if defined(__AMDGCN__)\n"
        f"static inline int ecm_stage1_sub_mod(uint *r, const uint *a, const uint *b,\n"
        f"                                       const uint *N, uint limbs) {{\n"
        f"    if (limbs == 16u) {{ return mp_sub_mod_asm_{bits}b(r, a, b, N); }}\n"
        f"    return 0;\n"
        f"}}\n"
        f"#else\n"
        f"static inline int ecm_stage1_sub_mod(uint *r, const uint *a, const uint *b,\n"
        f"                                       const uint *N, uint limbs) {{\n"
        f"    if (limbs == 16u) {{ return mp_sub_mod_unroll_{bits}b(r, a, b, N); }}\n"
        f"    return 0;\n"
        f"}}\n"
        f"#endif\n"
    )
    path.write_text(
        f"// AUTO-GENERATED by tools/gen_mp_addsub_bits_stage1.py - do not edit.\n{body}{wrapper}",
        encoding="utf-8",
    )
    print(f"Wrote {path}")


def main() -> None:
    for bits, limbs, _max_n in WIDTHS:
        add_unroll = emit_add_unroll(limbs, bits)
        sub_unroll = emit_sub_unroll(limbs, bits)
        write_add_bits(bits, add_unroll)
        write_sub_bits(bits, sub_unroll)

    asm_common = ["#if defined(__AMDGCN__)\n\n"]
    for _bits, limbs, _max_n in WIDTHS:
        asm_common.append(emit_c_fix_add(limbs))
    for _bits, limbs, _max_n in WIDTHS:
        asm_common.append(emit_add_block(limbs, global_addr=False, fix_in_block=True))
        asm_common.append(emit_sub_block(limbs, global_addr=False, fix_in_block=True))
    asm_common.append("#endif\n\n")

    for bits, limbs, _max_n in WIDTHS:
        parts = ["".join(asm_common), emit_asm_wrappers(limbs, bits), emit_add_unroll(limbs, bits)]
        write_add_asm(bits, limbs, "".join(parts))
        parts_sub = ["".join(asm_common), emit_asm_wrappers(limbs, bits), emit_sub_unroll(limbs, bits)]
        write_sub_asm(bits, "".join(parts_sub))


if __name__ == "__main__":
    main()
