#!/usr/bin/env python3
"""Generate asm_fused_block16 + VCC soft-switch variants for mp_add_mod asm bench."""

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "kernels/opencl/bench/mp_addsub/generated/asm_block16.cl"

N = 16


def emit_c_fix() -> str:
    lines = [
        "// AUTO-GENERATED by tools/gen_mp_addmod_asm_block16.py â€?do not edit.\n",
        "#if defined(MP_ADDMOD_ASM_ENABLE) && defined(__AMDGCN__)\n\n",
        "static inline void c_fix_add_n16(\n",
    ]
    for i in range(N):
        lines.append(f"    uint *r{i}, ")
    lines[-1] = lines[-1].rstrip(", ") + ",\n"
    for i in range(N):
        comma = "," if i < N - 1 else ") {\n"
        lines.append(f"    uint n{i}{comma}")
    lines.append("    ulong c = 0ul;\n    ulong s;\n")
    for i in range(N):
        lines.append(
            f"    s = (ulong)*r{i} + (ulong)n{i} + c; c = s >> 32; *r{i} = (uint)s;\n"
        )
    lines.append("}\n\n")
    return "".join(lines)


def _scalar_loads(prefix: str, src: str) -> str:
    return "".join(f"    uint {prefix}{i} = {src}[{i}];\n" for i in range(N))


def _vccsoft_limb0_standalone() -> list[str]:
    return [
        '        "v_add_co_u32    %[s], vcc_lo, %[a0], %[b0]\\n\\t"',
        '        "v_cndmask_b32   %[ca], %[z], %[one], vcc_lo\\n\\t"',
        '        "v_not_b32       %[nn], %[n0]\\n\\t"',
        '        "v_cmp_eq_u32    vcc_lo, %[one], %[one]\\n\\t"',
        '        "v_add_co_ci_u32 %[r0], vcc_lo, %[s], %[nn], vcc_lo\\n\\t"',
        '        "v_cndmask_b32   %[cs], %[z], %[one], vcc_lo\\n\\t"',
    ]


def _vccsoft_limb0_chunk() -> list[str]:
    return [
        '        "v_cmp_eq_u32    vcc_lo, %[one], %[ca]\\n\\t"',
        '        "v_add_co_ci_u32 %[s], vcc_lo, %[a0], %[b0], vcc_lo\\n\\t"',
        '        "v_cndmask_b32   %[ca], %[z], %[one], vcc_lo\\n\\t"',
        '        "v_cmp_eq_u32    vcc_lo, %[one], %[cs]\\n\\t"',
        '        "v_not_b32       %[nn], %[n0]\\n\\t"',
        '        "v_add_co_ci_u32 %[r0], vcc_lo, %[s], %[nn], vcc_lo\\n\\t"',
        '        "v_cndmask_b32   %[cs], %[z], %[one], vcc_lo\\n\\t"',
    ]


def _vccsoft_limb_i(i: int) -> list[str]:
    return [
        f'        "v_cmp_eq_u32    vcc_lo, %[one], %[ca]\\n\\t"',
        f'        "v_add_co_ci_u32 %[s], vcc_lo, %[a{i}], %[b{i}], vcc_lo\\n\\t"',
        f'        "v_cndmask_b32   %[ca], %[z], %[one], vcc_lo\\n\\t"',
        f'        "v_cmp_eq_u32    vcc_lo, %[one], %[cs]\\n\\t"',
        f'        "v_not_b32       %[nn], %[n{i}]\\n\\t"',
        f'        "v_add_co_ci_u32 %[r{i}], vcc_lo, %[s], %[nn], vcc_lo\\n\\t"',
        f'        "v_cndmask_b32   %[cs], %[z], %[one], vcc_lo\\n\\t"',
    ]


def _vccsoft_asm_lines(chunk: bool) -> list[str]:
    lines = _vccsoft_limb0_chunk() if chunk else _vccsoft_limb0_standalone()
    for i in range(1, N):
        lines.extend(_vccsoft_limb_i(i))
    lines[-1] = lines[-1].replace("\\n\\t\"", '"')
    return lines


def _vccsoft_constraints(chunk: bool) -> str:
    out_r = ", ".join(f'[r{i}] "=&v"(r{i})' for i in range(N))
    ca_cs = (
        '[ca] "+v"(v_ca), [cs] "+v"(v_cs)'
        if chunk
        else '[ca] "=&v"(v_ca), [cs] "=&v"(v_cs)'
    )
    in_ab = ", ".join(
        f'[a{i}] "v"(a{i}), [b{i}] "v"(b{i}), [n{i}] "v"(n{i})' for i in range(N)
    )
    return f"""        : {out_r}, {ca_cs},
          [s] "=&v"(s_tmp), [nn] "=&v"(nn_tmp)
        : {in_ab},
          [z] "v"(z), [one] "v"(one)
        : "vcc_lo");"""


def emit_block16() -> str:
    loads_a = _scalar_loads("a", "a")
    loads_b = _scalar_loads("b", "b")
    loads_n = _scalar_loads("n", "n")
    decl_s = ", ".join(f"s{i}" for i in range(N))
    decl_r = ", ".join(f"r{i}" for i in range(N))
    decl_nn = ", ".join(f"n{i}n" for i in range(N))

    asm_add = ['        "v_cmp_eq_u32    vcc_lo, %[ca_bit], %[o]\\n\\t"']
    for i in range(N):
        asm_add.append(f'        "v_add_co_ci_u32 %[s{i}], vcc_lo, %[a{i}], %[b{i}], vcc_lo\\n\\t"')
    asm_add.append('        "v_cndmask_b32   %[ca], %[z], %[o], vcc_lo\\n\\t"')
    for i in range(N):
        asm_add.append(f'        "v_not_b32       %[n{i}n], %[n{i}]\\n\\t"')
    asm_add.append('        "v_cmp_eq_u32    vcc_lo, %[cs_bit], %[o]\\n\\t"')
    for i in range(N - 1):
        asm_add.append(
            f'        "v_add_co_ci_u32 %[r{i}], vcc_lo, %[s{i}], %[n{i}n], vcc_lo\\n\\t"'
        )
    asm_add.append(
        f'        "v_add_co_ci_u32 %[r{N - 1}], vcc_lo, %[s{N - 1}], %[n{N - 1}n], vcc_lo\\n\\t"'
    )
    asm_add.append('        "v_cndmask_b32   %[cs], %[z], %[o], vcc_lo"')

    out_s = ", ".join(f'[s{i}] "=&v"(s{i})' for i in range(N))
    out_r = ", ".join(f'[r{i}] "=&v"(r{i})' for i in range(N))
    out_nn = ", ".join(f'[n{i}n] "=&v"(n{i}n)' for i in range(N))
    in_ab = ", ".join(f'[a{i}] "v"(a{i}), [b{i}] "v"(b{i})' for i in range(N))
    in_n = ", ".join(f'[n{i}] "v"(n{i})' for i in range(N))
    fix_call = ", ".join(f"&r{i}" for i in range(N))
    fix_n = ", ".join(f"n{i}" for i in range(N))
    stores = "".join(f"    r[{i}] = r{i};\n" for i in range(N))

    return f"""
// 16-limb fused block; streaming __global (no private a[16]).
static inline void asm_fused_block16(__global const uint *a, __global const uint *b,
                                   __global const uint *n, __global uint *r, uint ca_in,
                                   uint cs_in, uint *ca_out, uint *cs_out) {{
{loads_a}{loads_b}{loads_n}    uint {decl_s};
    uint {decl_r};
    uint {decl_nn};
    uint ca = 0u, cs = 0u;
    const uint z = 0u, o = 1u;
    uint ca_bit = ca_in ? o : z;
    uint cs_bit = cs_in ? o : z;

    __asm volatile(
{chr(10).join(asm_add)}
        : {out_s},
          {out_r},
          {out_nn},
          [ca] "=&v"(ca), [cs] "=&v"(cs)
        : {in_ab},
          {in_n},
          [ca_bit] "v"(ca_bit), [cs_bit] "v"(cs_bit), [z] "v"(z), [o] "v"(o)
        : "vcc_lo");

    if ((ca | cs) == 0u) {{
        c_fix_add_n16({fix_call}, {fix_n});
    }}

{stores}    *ca_out = ca;
    *cs_out = cs;
}}
"""


def emit_vccsoft_body(name: str, chunk: bool) -> str:
    loads_a = _scalar_loads("a", "a")
    loads_b = _scalar_loads("b", "b")
    loads_n = _scalar_loads("n", "n")
    decl_r = ", ".join(f"r{i}" for i in range(N))
    fix_call = ", ".join(f"&r{i}" for i in range(N))
    fix_n = ", ".join(f"n{i}" for i in range(N))
    stores = "".join(f"    r[{i}] = r{i};\n" for i in range(N))
    asm = _vccsoft_asm_lines(chunk)
    constraints = _vccsoft_constraints(chunk)

    if chunk:
        sig = f"""static inline void {name}(__global const uint *a, __global const uint *b,
                                           __global const uint *n, __global uint *r, uint ca_in,
                                           uint cs_in, uint *ca_out, uint *cs_out) {{
{loads_a}{loads_b}{loads_n}    uint {decl_r};
    uint v_ca = ca_in;
    uint v_cs = cs_in;
    uint s_tmp, nn_tmp;
    const uint z = 0u, one = 1u;
"""
        tail = f"""
{stores}    *ca_out = v_ca;
    *cs_out = v_cs;
}}
"""
    else:
        sig = f"""__attribute__((always_inline)) static inline void {name}(__global uint *r,
                                                                           __global const uint *a,
                                                                           __global const uint *b,
                                                                           __global const uint *N) {{
{loads_a}{loads_b}{_scalar_loads("n", "N")}    uint {decl_r};
    uint v_ca = 0u, v_cs = 0u;
    uint s_tmp, nn_tmp;
    const uint z = 0u, one = 1u;
"""
        tail = f"""
{stores}}}
"""

    return sig + f"""
    __asm__ volatile(
{chr(10).join(asm)}
{constraints}

    if ((v_ca | v_cs) == 0u) {{
        c_fix_add_n16({fix_call}, {fix_n});
    }}
""" + tail


def main() -> None:
    parts = [
        emit_c_fix(),
        emit_block16(),
        emit_vccsoft_body("mp_add_mod_16_asm_vccsoft", chunk=False),
        emit_vccsoft_body("asm_fused_block16_vccsoft", chunk=True),
        "#endif\n",
    ]
    OUT.write_text("".join(parts), encoding="utf-8")
    print(f"wrote {OUT} ({OUT.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
