#!/usr/bin/env python3
"""Generate fully-unrolled mont_mul_unroll_i24_u32_blsub (384-bit / 16 limbs)."""

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "cgbn/backends/opencl/kernels/mont_mul_unroll_i24_384_manual_generated.cl"

LIMBS = 16
HEADER = f"""// AUTO-GENERATED by tools/gen_mont_mul_unroll_i24_384_manual.py — do not edit.
// Full manual unroll of mont_mul_unroll_i24_u32_blsub_body ({LIMBS * 24}-bit / {LIMBS} limbs).
// Requires mont_mul_unroll_i24.cl helpers (mont_i24_cios_mac_u32, mont_i24_cios_mac_shift_u32).

#ifndef MONT_I24_384_FIXED_LIMBS
#define MONT_I24_384_FIXED_LIMBS {LIMBS}u
#endif

#if MONT_I24_LIMBS == MONT_I24_384_FIXED_LIMBS

"""


def emit_init() -> str:
    lines = [
        f"    uint t[MONT_I24_384_FIXED_LIMBS + 2u];\n",
        f"    uint B[MONT_I24_384_FIXED_LIMBS];\n",
        f"    uint N[MONT_I24_384_FIXED_LIMBS];\n",
    ]
    for i in range(LIMBS + 2):
        lines.append(f"    t[{i}] = 0u;\n")
    for j in range(LIMBS):
        lines.append(f"    B[{j}] = b[base + {j}u];\n")
        lines.append(f"    N[{j}] = n[{j}];\n")
    return "".join(lines)


def emit_pass1_u32() -> str:
    lines = ["        uint carry = 0u;\n"]
    for j in range(LIMBS):
        lines.append(
            f"        carry = mont_i24_cios_mac_u32(&t[{j}], ai, B[{j}], carry);\n"
        )
    lines.append(
        f"        {{ ulong top = (ulong)t[{LIMBS}] + (ulong)carry; "
        f"t[{LIMBS}] = (uint)(top & MONT_I24_LIMB_MASK); "
        f"t[{LIMBS + 1}] = (uint)(top >> MONT_I24_RADIX_BITS); }}\n"
    )
    return "".join(lines)


def emit_pass2_u32() -> str:
    lines = [
        "        const uint m = mul24(t[0], np0);\n",
        "        carry = 0u;\n",
    ]
    for j in range(LIMBS):
        lines.append("        {\n")
        lines.append("            uint limb_val = 0u;\n")
        lines.append(
            f"            carry = mont_i24_cios_mac_shift_u32(t[{j}], m, N[{j}], carry, &limb_val);\n"
        )
        if j > 0:
            lines.append(f"            t[{j - 1}] = limb_val;\n")
        lines.append("        }\n")
    lines.append(
        f"        {{ ulong top = (ulong)t[{LIMBS}] + (ulong)carry; "
        f"t[{LIMBS - 1}] = (uint)(top & MONT_I24_LIMB_MASK); "
        f"top = (ulong)t[{LIMBS + 1}] + (top >> MONT_I24_RADIX_BITS); "
        f"t[{LIMBS}] = (uint)(top & MONT_I24_LIMB_MASK); "
        f"t[{LIMBS + 1}] = (uint)(top >> MONT_I24_RADIX_BITS); }}\n"
    )
    return "".join(lines)


def emit_outer(i: int) -> str:
    return (
        f"    // outer i={i}\n"
        f"    {{\n"
        f"        const uint ai = a[base + {i}u];\n"
        f"{emit_pass1_u32()}"
        f"{emit_pass2_u32()}"
        f"    }}\n"
    )


def emit_subtract_blsub() -> str:
    lines = [
        "    uint borrow = 0u;\n",
        "    uint D[MONT_I24_384_FIXED_LIMBS];\n",
    ]
    for i in range(LIMBS):
        lines.append(
            f"    {{ const uint tv = t[{i}]; const uint nv = N[{i}]; "
            f"D[{i}] = tv - nv - borrow; "
            f"borrow = (uint)((tv < nv) | ((tv == nv) & borrow)); }}\n"
        )
    lines.append(
        f"    const uint any_high = (t[{LIMBS}] | t[{LIMBS + 1}]) != 0u;\n"
    )
    lines.append("    const uint need_sub = any_high | (borrow == 0u);\n")
    lines.append("    const uint mask = 0u - need_sub;\n")
    for i in range(LIMBS):
        lines.append(
            f"    out[base + {i}] = (D[{i}] & mask) | (t[{i}] & ~mask);\n"
        )
    return "".join(lines)


def emit_body() -> str:
    # Unqualified pointers: bench passes __global/__constant; priv uses private — Adreno
    # rejects __global parameters when priv wrappers call the same body.
    parts = [
        "static inline void mont_mul_unroll_i24_384_manual_body(\n",
        "    uint *out,\n",
        "    const uint *a,\n",
        "    const uint *b,\n",
        "    const uint *n,\n",
        "    uint base,\n",
        "    uint np0)\n",
        "{\n",
        emit_init(),
    ]
    for i in range(LIMBS):
        parts.append(emit_outer(i))
    parts.append(emit_subtract_blsub())
    parts.append("}\n\n")
    parts.append(
        "static inline void mont_sqr_unroll_i24_384_manual_body(\n"
        "    uint *out,\n"
        "    const uint *a,\n"
        "    const uint *n,\n"
        "    uint base,\n"
        "    uint np0)\n"
        "{\n"
        "    mont_mul_unroll_i24_384_manual_body(out, a, a, n, base, np0);\n"
        "}\n\n"
        "static inline void mont_mul_priv_i24_u32_384_manual_body(\n"
        "    uint *out,\n"
        "    const uint *a,\n"
        "    const uint *b,\n"
        "    const uint *n,\n"
        "    uint np0)\n"
        "{\n"
        "    mont_mul_unroll_i24_384_manual_body(out, a, b, n, 0u, np0);\n"
        "}\n\n"
        "static inline void mont_sqr_priv_i24_u32_384_manual_body(\n"
        "    uint *out,\n"
        "    const uint *a,\n"
        "    const uint *n,\n"
        "    uint np0)\n"
        "{\n"
        "    mont_mul_priv_i24_u32_384_manual_body(out, a, a, n, np0);\n"
        "}\n\n"
    )
    return "".join(parts)


def main() -> None:
    content = HEADER + emit_body() + "#endif\n"
    OUT.write_text(content, encoding="utf-8")
    print(f"Wrote {OUT} ({len(content.splitlines())} lines)")


if __name__ == "__main__":
    main()
