#!/usr/bin/env python3
"""Generate private b32 asm blocks for ECM stage1 (4096-bit add + sub)."""

from pathlib import Path

from mp_asm_block_gen import emit_add_block, emit_sub_block

ROOT = Path(__file__).resolve().parents[1]
OUT_ADD = ROOT / "kernels/opencl/add_mod/asm_4096b.cl"
OUT_SUB = ROOT / "kernels/opencl/sub_mod/asm_4096b.cl"


def asm_add_body() -> str:
    return (
        "#if defined(__AMDGCN__)\n"
        "static inline void mp_add_mod_asm_b32_4096(uint *r, const uint *a, const uint *b, const uint *N) {\n"
        "    uint ca = 0u, cs = 1u;\n"
        "    #pragma unroll\n"
        "    for (uint blk = 0u; blk < 4u; ++blk) {\n"
        "        uint off = blk * 32u;\n"
        "        asm_fused_block32_priv(a + off, b + off, N + off, r + off, ca, cs, &ca, &cs);\n"
        "    }\n"
        "    if ((ca | cs) == 0u) {\n"
        "        ulong c = 0ul;\n"
        "        #pragma unroll 32\n"
        "        for (uint i = 0u; i < 128u; ++i) {\n"
        "            ulong s = (ulong)r[i] + (ulong)N[i] + c;\n"
        "            r[i] = (uint)s;\n"
        "            c = s >> 32;\n"
        "        }\n"
        "    }\n"
        "}\n"
        "#endif\n"
    )


def asm_sub_body() -> str:
    return (
        "#if defined(__AMDGCN__)\n"
        "static inline int mp_sub_mod_asm_b32_4096(uint *r, const uint *a, const uint *b, const uint *N) {\n"
        "    uint br = 0u;\n"
        "    #pragma unroll\n"
        "    for (uint blk = 0u; blk < 4u; ++blk) {\n"
        "        uint off = blk * 32u;\n"
        "        asm_sub_fused_block32_priv(a + off, b + off, N + off, r + off, br, &br);\n"
        "    }\n"
        "    if (br != 0u) {\n"
        "        ulong c = 0ul;\n"
        "        #pragma unroll 32\n"
        "        for (uint i = 0u; i < 128u; ++i) {\n"
        "            ulong s = (ulong)r[i] + (ulong)N[i] + c;\n"
        "            r[i] = (uint)s;\n"
        "            c = s >> 32;\n"
        "        }\n"
        "        return 1;\n"
        "    }\n"
        "    return 0;\n"
        "}\n"
        "#endif\n"
    )


def main() -> None:
    prefix = [
        "// AUTO-GENERATED by tools/gen_mp_addsub_asm_block32_stage1.py - do not edit.\n",
        "#if defined(__AMDGCN__)\n\n",
        emit_add_block(32, global_addr=False, fix_in_block=False),
        emit_sub_block(32, global_addr=False, fix_in_block=False),
        "#endif\n\n",
    ]
    OUT_ADD.write_text(
        "".join(prefix)
        + asm_add_body()
        + (
            "\nstatic inline void ecm_stage1_add_mod(uint *r, const uint *a, const uint *b,\n"
            "                                        const uint *N, uint limbs) {\n"
            "#if defined(__AMDGCN__)\n"
            "    if (limbs == 128u) { mp_add_mod_asm_b32_4096(r, a, b, N); return; }\n"
            "#else\n"
            "    if (limbs == 128u) { mp_add_mod_fused_unroll_b32_4096(r, a, b, N); return; }\n"
            "#endif\n"
            "    (void)limbs;\n"
            "}\n"
        ),
        encoding="utf-8",
    )
    OUT_SUB.write_text(
        "".join(prefix)
        + asm_sub_body()
        + (
            "\nstatic inline int ecm_stage1_sub_mod(uint *r, const uint *a, const uint *b,\n"
            "                                       const uint *N, uint limbs) {\n"
            "#if defined(__AMDGCN__)\n"
            "    if (limbs == 128u) { return mp_sub_mod_asm_b32_4096(r, a, b, N); }\n"
            "#else\n"
            "    if (limbs == 128u) { return mp_sub_mod_fused_unroll_b32_4096(r, a, b, N); }\n"
            "#endif\n"
            "    return 0;\n"
            "}\n"
        ),
        encoding="utf-8",
    )
    print(f"Wrote {OUT_ADD}")
    print(f"Wrote {OUT_SUB}")


if __name__ == "__main__":
    main()
