#!/usr/bin/env python3
"""Generate asm_fused_block32 for 4096-bit (128-limb) mp_add_mod asm bench."""

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "cgbn/backends/opencl/kernels/mp_addmod_asm_block32_generated.cl"

N = 32


def emit_c_fix() -> str:
    lines = [
        "// AUTO-GENERATED by tools/gen_mp_addmod_asm_block32.py — do not edit.\n",
        "#if defined(MP_ADDMOD_ASM_ENABLE) && defined(__AMDGCN__)\n\n",
        f"static inline void c_fix_add_n{N}(\n",
    ]
    for i in range(N):
        lines.append(f"    uint *r{i}, ")
    lines[-1] = lines[-1].rstrip(", ") + ",\n"
    for i in range(N):
        comma = "," if i < N - 1 else ") {\n"
        lines.append(f"    uint n{i}{comma}")
    lines.append("    ulong c = 0ul;\n    ulong s;\n")
    for i in range(N):
        lines.append(
            f"    s = (ulong)*r{i} + (ulong)n{i} + c; c = s >> 32; *r{i} = (uint)s;\n"
        )
    lines.append("}\n\n")
    return "".join(lines)


def _scalar_loads(prefix: str, src: str) -> str:
    return "".join(f"    uint {prefix}{i} = {src}[{i}];\n" for i in range(N))


def emit_block32() -> str:
    loads_a = _scalar_loads("a", "a")
    loads_b = _scalar_loads("b", "b")
    loads_n = _scalar_loads("n", "n")
    decl_s = ", ".join(f"s{i}" for i in range(N))
    decl_r = ", ".join(f"r{i}" for i in range(N))
    decl_nn = ", ".join(f"n{i}n" for i in range(N))

    asm_add = ['        "v_cmp_eq_u32    vcc_lo, %[ca_bit], %[o]\\n\\t"']
    for i in range(N):
        asm_add.append(f'        "v_add_co_ci_u32 %[s{i}], vcc_lo, %[a{i}], %[b{i}], vcc_lo\\n\\t"')
    asm_add.append('        "v_cndmask_b32   %[ca], %[z], %[o], vcc_lo\\n\\t"')
    for i in range(N):
        asm_add.append(f'        "v_not_b32       %[n{i}n], %[n{i}]\\n\\t"')
    asm_add.append('        "v_cmp_eq_u32    vcc_lo, %[cs_bit], %[o]\\n\\t"')
    for i in range(N - 1):
        asm_add.append(
            f'        "v_add_co_ci_u32 %[r{i}], vcc_lo, %[s{i}], %[n{i}n], vcc_lo\\n\\t"'
        )
    asm_add.append(
        f'        "v_add_co_ci_u32 %[r{N - 1}], vcc_lo, %[s{N - 1}], %[n{N - 1}n], vcc_lo\\n\\t"'
    )
    asm_add.append('        "v_cndmask_b32   %[cs], %[z], %[o], vcc_lo"')

    out_s = ", ".join(f'[s{i}] "=&v"(s{i})' for i in range(N))
    out_r = ", ".join(f'[r{i}] "=&v"(r{i})' for i in range(N))
    out_nn = ", ".join(f'[n{i}n] "=&v"(n{i}n)' for i in range(N))
    in_ab = ", ".join(f'[a{i}] "v"(a{i}), [b{i}] "v"(b{i})' for i in range(N))
    in_n = ", ".join(f'[n{i}] "v"(n{i})' for i in range(N))
    fix_call = ", ".join(f"&r{i}" for i in range(N))
    fix_n = ", ".join(f"n{i}" for i in range(N))
    stores = "".join(f"    r[{i}] = r{i};\n" for i in range(N))

    return f"""
// 32-limb fused block; streaming __global (4096-bit unroll only).
static inline void asm_fused_block32(__global const uint *a, __global const uint *b,
                                   __global const uint *n, __global uint *r, uint ca_in,
                                   uint cs_in, uint *ca_out, uint *cs_out) {{
{loads_a}{loads_b}{loads_n}    uint {decl_s};
    uint {decl_r};
    uint {decl_nn};
    uint ca = 0u, cs = 0u;
    const uint z = 0u, o = 1u;
    uint ca_bit = ca_in ? o : z;
    uint cs_bit = cs_in ? o : z;

    __asm volatile(
{chr(10).join(asm_add)}
        : {out_s},
          {out_r},
          {out_nn},
          [ca] "=&v"(ca), [cs] "=&v"(cs)
        : {in_ab},
          {in_n},
          [ca_bit] "v"(ca_bit), [cs_bit] "v"(cs_bit), [z] "v"(z), [o] "v"(o)
        : "vcc_lo");

    if ((ca | cs) == 0u) {{
        c_fix_add_n{N}({fix_call}, {fix_n});
    }}

{stores}    *ca_out = ca;
    *cs_out = cs;
}}
"""


def main() -> None:
    parts = [emit_c_fix(), emit_block32(), "#endif\n"]
    OUT.write_text("".join(parts), encoding="utf-8")
    print(f"wrote {OUT} ({OUT.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
