#!/usr/bin/env python3
"""Generate 4096-bit (128-limb) mp_add_mod unroll kernel with AMDGCN inline asm."""

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "kernels/opencl/bench/mp_addmod_asm_4096_generated.cl"

HEADER = """// AUTO-GENERATED by tools/gen_mp_addmod_asm_4096.py — do not edit.

// Used for Radeon GPU Analyzer
#ifndef MP_ADDMOD_ASM_ENABLE
#define MP_ADDMOD_ASM_ENABLE 1
#endif
#ifndef MAX_LIMBS
#define MAX_LIMBS 128
#endif

#if defined(MP_ADDMOD_ASM_ENABLE) && (MAX_LIMBS == 128) && defined(__AMDGCN__)

"""


def emit_fused_limb(i: int) -> str:
    return (
        f"    {{\n"
        f"        uint _ca, _cs;\n"
        f"        uint _s = asm_add_u32(a[{i}], b[{i}], ca, &_ca);\n"
        f"        r[{i}] = asm_add_u32(_s, ~n[{i}], cs, &_cs);\n"
        f"        ca = _ca;\n"
        f"        cs = _cs;\n"
        f"    }}\n"
    )


def emit_fix_limb(i: int) -> str:
    return f"        r[{i}] = asm_add_u32(r[{i}], n[{i}], c, &_co); c = _co;\n"


def main() -> None:
    limbs = 128
    parts = [HEADER]
    load_a = "".join(f"    a[{i}] = a_g[base + {i}u];\n" for i in range(limbs))
    load_b = "".join(f"    b[{i}] = b_g[base + {i}u];\n" for i in range(limbs))
    load_n = "".join(f"    n[{i}] = n_g[base + {i}u];\n" for i in range(limbs))
    store = "".join(f"    out[base + {i}u] = r[{i}];\n" for i in range(limbs))

    body = f"""
__kernel void ecm_mp_add_mod_fused_unroll_asm(
    __global const uint *a_g,
    __global const uint *b_g,
    __global const uint *n_g,
    __global uint *out,
    uint limbs)
{{
    if (limbs != {limbs}u) return;
    uint gid = get_global_id(0);
    uint base = gid * {limbs}u;
    uint a[{limbs}], b[{limbs}], n[{limbs}], r[{limbs}];
{load_a}{load_b}{load_n}    uint ca = 0u;
    uint cs = 1u;
"""
    for i in range(limbs):
        body += emit_fused_limb(i)
    body += """
    if (ca == 0u && cs == 0u) {
        uint c = 0u;
        uint _co;
"""
    for i in range(limbs):
        body += emit_fix_limb(i)
    body += f"""    }}
{store}}}
#endif
"""
    parts.append(body)
    OUT.write_text("".join(parts), encoding="utf-8")
    print(f"wrote {OUT} ({OUT.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
