#!/usr/bin/env python3
"""Generate fixed-width special_mult unroll kernels for stage1."""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = ROOT / "kernels/opencl/special_mult"

WIDTHS = (
    (192, 6),
    (256, 8),
    (384, 12),
    (512, 16),
    (768, 24),
    (1024, 32),
    (1536, 48),
    (2048, 64),
    (2560, 80),
    (3072, 96),
    (3584, 112),
    (4096, 128),
    (4608, 144),
    (5120, 160),
    (5632, 176),
    (6144, 192),
    (6656, 208),
    (7168, 224),
    (7680, 240),
    (8192, 256),
)

HEADER = "// AUTO-GENERATED by tools/gen_special_mult_unroll.py - do not edit.\n"


def emit_special_mult(bits: int, limbs: int) -> str:
    L = limbs
    # Zero-init loop
    zero_lines = "    #pragma unroll\n    for (uint i = 0u; i < {L}u; ++i) t[i] = 0u;\n".format(L=L)

    # Product loop
    prod_lines = [
        "    // 1) product: t = r * m\n",
        "    {\n",
        "        ulong carry = 0ul;\n",
        "        #pragma unroll\n",
        "        for (uint j = 0u; j < {L}u; ++j) {{\n".format(L=L),
        "            ulong uv = (ulong)t[j] + (ulong)m * (ulong)r[j] + carry;\n",
        "            t[j] = (uint)uv;\n",
        "            carry = uv >> 32;\n",
        "        }\n",
        "        t[{L}u] = (uint)carry;\n".format(L=L),
        "    }\n",
    ]

    # Reduction loop
    red_lines = [
        "\n",
        "    // 2) reduction + implicit >>32 (CIOS standard)\n",
        "    {\n",
        "        uint mp = (uint)((ulong)t[0] * (ulong)np0);\n",
        "        ulong carry = 0ul;\n",
        "        #pragma unroll\n",
        "        for (uint j = 0u; j < {L}u; ++j) {{\n".format(L=L),
        "            ulong uv = (ulong)t[j] + (ulong)mp * (ulong)N[j] + carry;\n",
        "            if (j > 0u) t[j - 1u] = (uint)uv;\n",
        "            carry = uv >> 32;\n",
        "        }\n",
        "        ulong top = (ulong)t[{L}u] + carry;\n".format(L=L),
        "        t[{Lm1}u] = (uint)top;\n".format(Lm1=L - 1),
        "        t[{L}u] = (uint)(top >> 32);\n".format(L=L),
        "    }\n",
    ]

    # Conditional subtraction
    sub_lines = [
        "\n",
        "    // 3) branchless conditional subtraction\n",
        "    {\n",
        "        ulong borrow = 0ul;\n",
        "        uint D[{L}u];\n".format(L=L),
        "        #pragma unroll\n",
        "        for (uint i = 0u; i < {L}u; ++i) {{\n".format(L=L),
        "            ulong tv = (ulong)t[i], nv = (ulong)N[i];\n",
        "            ulong w = tv - nv - borrow;\n",
        "            D[i] = (uint)w;\n",
        "            borrow = (tv < nv + borrow) ? 1ul : 0ul;\n",
        "        }\n",
        "        uint need_sub = (t[{L}u] != 0u) ? 1u : (borrow == 0ul ? 1u : 0u);\n".format(L=L),
        "        uint mask = 0u - need_sub;\n",
        "        #pragma unroll\n",
        "        for (uint i = 0u; i < {L}u; ++i) {{\n".format(L=L),
        "            r[i] = (D[i] & mask) | (t[i] & ~mask);\n",
        "        }\n",
        "    }\n",
    ]

    body = (
        f"// Stage1 special_mult — {bits}-bit unroll-only (R = 2^32).\n"
        f"// Unrolled single-limb CIOS with {L} hardcoded limbs.\n"
        f"// Inlined into ecm_stage1.cl when MAX_LIMBS <= {L}.\n"
        f"static inline void special_mult_ui32_unroll_{bits}b(uint *r, uint m,\n"
        f"        const uint *N, uint np0, uint limbs) {{\n"
        f"    uint t[{L + 1}u];\n"
        f"{zero_lines}"
        f"\n"
        f'{"".join(prod_lines)}'
        f'{"".join(red_lines)}'
        f'{"".join(sub_lines)}'
        f"    (void)limbs;\n"
        f"}}\n"
    )
    return HEADER + body


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for bits, limbs in WIDTHS:
        path = OUT_DIR / f"special_mult_unroll_{bits}b.cl"
        content = emit_special_mult(bits, limbs)
        path.write_text(content, encoding="utf-8")
        print(f"Wrote {path}")


if __name__ == "__main__":
    main()
