// AUTO-GENERATED by tools/gen_mont_mul_asm_512.py — do not edit.
// ASM-assisted CIOS mont mul (512-bit / 16 limbs).
// Requires mont_mul_asm_fused.cl; optional mont_mul_asm_block8_generated.cl when inline=0.

#ifndef MONT_OPT2_FIXED_LIMBS
#define MONT_OPT2_FIXED_LIMBS 16u
#endif

#if defined(MONT_MUL_ASM_ENABLE) && defined(__AMDGCN__)

static inline void mont_mul_priv_unroll_only_512_asm_body(
    __global uint *out,
    __global const uint *a,
    __global const uint *b,
    __constant uint *n,
    uint base,
    uint np0)
{
    uint t[MONT_OPT2_FIXED_LIMBS + 2u];
    t[0] = 0u;
    t[1] = 0u;
    t[2] = 0u;
    t[3] = 0u;
    t[4] = 0u;
    t[5] = 0u;
    t[6] = 0u;
    t[7] = 0u;
    t[8] = 0u;
    t[9] = 0u;
    t[10] = 0u;
    t[11] = 0u;
    t[12] = 0u;
    t[13] = 0u;
    t[14] = 0u;
    t[15] = 0u;
    t[16] = 0u;
    t[17] = 0u;
    uint B[MONT_OPT2_FIXED_LIMBS];
    uint N[MONT_OPT2_FIXED_LIMBS];
    B[0] = b[base + 0u];
    N[0] = n[0];
    B[1] = b[base + 1u];
    N[1] = n[1];
    B[2] = b[base + 2u];
    N[2] = n[2];
    B[3] = b[base + 3u];
    N[3] = n[3];
    B[4] = b[base + 4u];
    N[4] = n[4];
    B[5] = b[base + 5u];
    N[5] = n[5];
    B[6] = b[base + 6u];
    N[6] = n[6];
    B[7] = b[base + 7u];
    N[7] = n[7];
    B[8] = b[base + 8u];
    N[8] = n[8];
    B[9] = b[base + 9u];
    N[9] = n[9];
    B[10] = b[base + 10u];
    N[10] = n[10];
    B[11] = b[base + 11u];
    N[11] = n[11];
    B[12] = b[base + 12u];
    N[12] = n[12];
    B[13] = b[base + 13u];
    N[13] = n[13];
    B[14] = b[base + 14u];
    N[14] = n[14];
    B[15] = b[base + 15u];
    N[15] = n[15];
    // outer i=0
    {
        uint ai = a[base + 0u];
        ulong carry = 0ul;
        carry = asm_mac_pass1_block8_0(carry, ai, t, B);
        carry = asm_mac_pass1_block8_8(carry, ai, t, B);
        { ulong top = (ulong)t[16] + carry; t[16] = (uint)top; t[17] = (uint)(top >> 32); }
        uint m = (uint)((ulong)t[0] * (ulong)np0);
        carry = asm_red_step0_carry(t[0], m, N[0]);
        carry = asm_mac_pass2_block8_1(carry, m, t, N);
        carry = asm_mac_pass2_block7_9(carry, m, t, N);
        { ulong top = (ulong)t[16] + carry; t[15] = (uint)top; top = (ulong)t[17] + (top >> 32); t[16] = (uint)top; t[17] = (uint)(top >> 32); }
    }
    // outer i=1
    {
        uint ai = a[base + 1u];
        ulong carry = 0ul;
        carry = asm_mac_pass1_block8_0(carry, ai, t, B);
        carry = asm_mac_pass1_block8_8(carry, ai, t, B);
        { ulong top = (ulong)t[16] + carry; t[16] = (uint)top; t[17] = (uint)(top >> 32); }
        uint m = (uint)((ulong)t[0] * (ulong)np0);
        carry = asm_red_step0_carry(t[0], m, N[0]);
        carry = asm_mac_pass2_block8_1(carry, m, t, N);
        carry = asm_mac_pass2_block7_9(carry, m, t, N);
        { ulong top = (ulong)t[16] + carry; t[15] = (uint)top; top = (ulong)t[17] + (top >> 32); t[16] = (uint)top; t[17] = (uint)(top >> 32); }
    }
    // outer i=2
    {
        uint ai = a[base + 2u];
        ulong carry = 0ul;
        carry = asm_mac_pass1_block8_0(carry, ai, t, B);
        carry = asm_mac_pass1_block8_8(carry, ai, t, B);
        { ulong top = (ulong)t[16] + carry; t[16] = (uint)top; t[17] = (uint)(top >> 32); }
        uint m = (uint)((ulong)t[0] * (ulong)np0);
        carry = asm_red_step0_carry(t[0], m, N[0]);
        carry = asm_mac_pass2_block8_1(carry, m, t, N);
        carry = asm_mac_pass2_block7_9(carry, m, t, N);
        { ulong top = (ulong)t[16] + carry; t[15] = (uint)top; top = (ulong)t[17] + (top >> 32); t[16] = (uint)top; t[17] = (uint)(top >> 32); }
    }
    // outer i=3
    {
        uint ai = a[base + 3u];
        ulong carry = 0ul;
        carry = asm_mac_pass1_block8_0(carry, ai, t, B);
        carry = asm_mac_pass1_block8_8(carry, ai, t, B);
        { ulong top = (ulong)t[16] + carry; t[16] = (uint)top; t[17] = (uint)(top >> 32); }
        uint m = (uint)((ulong)t[0] * (ulong)np0);
        carry = asm_red_step0_carry(t[0], m, N[0]);
        carry = asm_mac_pass2_block8_1(carry, m, t, N);
        carry = asm_mac_pass2_block7_9(carry, m, t, N);
        { ulong top = (ulong)t[16] + carry; t[15] = (uint)top; top = (ulong)t[17] + (top >> 32); t[16] = (uint)top; t[17] = (uint)(top >> 32); }
    }
    // outer i=4
    {
        uint ai = a[base + 4u];
        ulong carry = 0ul;
        carry = asm_mac_pass1_block8_0(carry, ai, t, B);
        carry = asm_mac_pass1_block8_8(carry, ai, t, B);
        { ulong top = (ulong)t[16] + carry; t[16] = (uint)top; t[17] = (uint)(top >> 32); }
        uint m = (uint)((ulong)t[0] * (ulong)np0);
        carry = asm_red_step0_carry(t[0], m, N[0]);
        carry = asm_mac_pass2_block8_1(carry, m, t, N);
        carry = asm_mac_pass2_block7_9(carry, m, t, N);
        { ulong top = (ulong)t[16] + carry; t[15] = (uint)top; top = (ulong)t[17] + (top >> 32); t[16] = (uint)top; t[17] = (uint)(top >> 32); }
    }
    // outer i=5
    {
        uint ai = a[base + 5u];
        ulong carry = 0ul;
        carry = asm_mac_pass1_block8_0(carry, ai, t, B);
        carry = asm_mac_pass1_block8_8(carry, ai, t, B);
        { ulong top = (ulong)t[16] + carry; t[16] = (uint)top; t[17] = (uint)(top >> 32); }
        uint m = (uint)((ulong)t[0] * (ulong)np0);
        carry = asm_red_step0_carry(t[0], m, N[0]);
        carry = asm_mac_pass2_block8_1(carry, m, t, N);
        carry = asm_mac_pass2_block7_9(carry, m, t, N);
        { ulong top = (ulong)t[16] + carry; t[15] = (uint)top; top = (ulong)t[17] + (top >> 32); t[16] = (uint)top; t[17] = (uint)(top >> 32); }
    }
    // outer i=6
    {
        uint ai = a[base + 6u];
        ulong carry = 0ul;
        carry = asm_mac_pass1_block8_0(carry, ai, t, B);
        carry = asm_mac_pass1_block8_8(carry, ai, t, B);
        { ulong top = (ulong)t[16] + carry; t[16] = (uint)top; t[17] = (uint)(top >> 32); }
        uint m = (uint)((ulong)t[0] * (ulong)np0);
        carry = asm_red_step0_carry(t[0], m, N[0]);
        carry = asm_mac_pass2_block8_1(carry, m, t, N);
        carry = asm_mac_pass2_block7_9(carry, m, t, N);
        { ulong top = (ulong)t[16] + carry; t[15] = (uint)top; top = (ulong)t[17] + (top >> 32); t[16] = (uint)top; t[17] = (uint)(top >> 32); }
    }
    // outer i=7
    {
        uint ai = a[base + 7u];
        ulong carry = 0ul;
        carry = asm_mac_pass1_block8_0(carry, ai, t, B);
        carry = asm_mac_pass1_block8_8(carry, ai, t, B);
        { ulong top = (ulong)t[16] + carry; t[16] = (uint)top; t[17] = (uint)(top >> 32); }
        uint m = (uint)((ulong)t[0] * (ulong)np0);
        carry = asm_red_step0_carry(t[0], m, N[0]);
        carry = asm_mac_pass2_block8_1(carry, m, t, N);
        carry = asm_mac_pass2_block7_9(carry, m, t, N);
        { ulong top = (ulong)t[16] + carry; t[15] = (uint)top; top = (ulong)t[17] + (top >> 32); t[16] = (uint)top; t[17] = (uint)(top >> 32); }
    }
    // outer i=8
    {
        uint ai = a[base + 8u];
        ulong carry = 0ul;
        carry = asm_mac_pass1_block8_0(carry, ai, t, B);
        carry = asm_mac_pass1_block8_8(carry, ai, t, B);
        { ulong top = (ulong)t[16] + carry; t[16] = (uint)top; t[17] = (uint)(top >> 32); }
        uint m = (uint)((ulong)t[0] * (ulong)np0);
        carry = asm_red_step0_carry(t[0], m, N[0]);
        carry = asm_mac_pass2_block8_1(carry, m, t, N);
        carry = asm_mac_pass2_block7_9(carry, m, t, N);
        { ulong top = (ulong)t[16] + carry; t[15] = (uint)top; top = (ulong)t[17] + (top >> 32); t[16] = (uint)top; t[17] = (uint)(top >> 32); }
    }
    // outer i=9
    {
        uint ai = a[base + 9u];
        ulong carry = 0ul;
        carry = asm_mac_pass1_block8_0(carry, ai, t, B);
        carry = asm_mac_pass1_block8_8(carry, ai, t, B);
        { ulong top = (ulong)t[16] + carry; t[16] = (uint)top; t[17] = (uint)(top >> 32); }
        uint m = (uint)((ulong)t[0] * (ulong)np0);
        carry = asm_red_step0_carry(t[0], m, N[0]);
        carry = asm_mac_pass2_block8_1(carry, m, t, N);
        carry = asm_mac_pass2_block7_9(carry, m, t, N);
        { ulong top = (ulong)t[16] + carry; t[15] = (uint)top; top = (ulong)t[17] + (top >> 32); t[16] = (uint)top; t[17] = (uint)(top >> 32); }
    }
    // outer i=10
    {
        uint ai = a[base + 10u];
        ulong carry = 0ul;
        carry = asm_mac_pass1_block8_0(carry, ai, t, B);
        carry = asm_mac_pass1_block8_8(carry, ai, t, B);
        { ulong top = (ulong)t[16] + carry; t[16] = (uint)top; t[17] = (uint)(top >> 32); }
        uint m = (uint)((ulong)t[0] * (ulong)np0);
        carry = asm_red_step0_carry(t[0], m, N[0]);
        carry = asm_mac_pass2_block8_1(carry, m, t, N);
        carry = asm_mac_pass2_block7_9(carry, m, t, N);
        { ulong top = (ulong)t[16] + carry; t[15] = (uint)top; top = (ulong)t[17] + (top >> 32); t[16] = (uint)top; t[17] = (uint)(top >> 32); }
    }
    // outer i=11
    {
        uint ai = a[base + 11u];
        ulong carry = 0ul;
        carry = asm_mac_pass1_block8_0(carry, ai, t, B);
        carry = asm_mac_pass1_block8_8(carry, ai, t, B);
        { ulong top = (ulong)t[16] + carry; t[16] = (uint)top; t[17] = (uint)(top >> 32); }
        uint m = (uint)((ulong)t[0] * (ulong)np0);
        carry = asm_red_step0_carry(t[0], m, N[0]);
        carry = asm_mac_pass2_block8_1(carry, m, t, N);
        carry = asm_mac_pass2_block7_9(carry, m, t, N);
        { ulong top = (ulong)t[16] + carry; t[15] = (uint)top; top = (ulong)t[17] + (top >> 32); t[16] = (uint)top; t[17] = (uint)(top >> 32); }
    }
    // outer i=12
    {
        uint ai = a[base + 12u];
        ulong carry = 0ul;
        carry = asm_mac_pass1_block8_0(carry, ai, t, B);
        carry = asm_mac_pass1_block8_8(carry, ai, t, B);
        { ulong top = (ulong)t[16] + carry; t[16] = (uint)top; t[17] = (uint)(top >> 32); }
        uint m = (uint)((ulong)t[0] * (ulong)np0);
        carry = asm_red_step0_carry(t[0], m, N[0]);
        carry = asm_mac_pass2_block8_1(carry, m, t, N);
        carry = asm_mac_pass2_block7_9(carry, m, t, N);
        { ulong top = (ulong)t[16] + carry; t[15] = (uint)top; top = (ulong)t[17] + (top >> 32); t[16] = (uint)top; t[17] = (uint)(top >> 32); }
    }
    // outer i=13
    {
        uint ai = a[base + 13u];
        ulong carry = 0ul;
        carry = asm_mac_pass1_block8_0(carry, ai, t, B);
        carry = asm_mac_pass1_block8_8(carry, ai, t, B);
        { ulong top = (ulong)t[16] + carry; t[16] = (uint)top; t[17] = (uint)(top >> 32); }
        uint m = (uint)((ulong)t[0] * (ulong)np0);
        carry = asm_red_step0_carry(t[0], m, N[0]);
        carry = asm_mac_pass2_block8_1(carry, m, t, N);
        carry = asm_mac_pass2_block7_9(carry, m, t, N);
        { ulong top = (ulong)t[16] + carry; t[15] = (uint)top; top = (ulong)t[17] + (top >> 32); t[16] = (uint)top; t[17] = (uint)(top >> 32); }
    }
    // outer i=14
    {
        uint ai = a[base + 14u];
        ulong carry = 0ul;
        carry = asm_mac_pass1_block8_0(carry, ai, t, B);
        carry = asm_mac_pass1_block8_8(carry, ai, t, B);
        { ulong top = (ulong)t[16] + carry; t[16] = (uint)top; t[17] = (uint)(top >> 32); }
        uint m = (uint)((ulong)t[0] * (ulong)np0);
        carry = asm_red_step0_carry(t[0], m, N[0]);
        carry = asm_mac_pass2_block8_1(carry, m, t, N);
        carry = asm_mac_pass2_block7_9(carry, m, t, N);
        { ulong top = (ulong)t[16] + carry; t[15] = (uint)top; top = (ulong)t[17] + (top >> 32); t[16] = (uint)top; t[17] = (uint)(top >> 32); }
    }
    // outer i=15
    {
        uint ai = a[base + 15u];
        ulong carry = 0ul;
        carry = asm_mac_pass1_block8_0(carry, ai, t, B);
        carry = asm_mac_pass1_block8_8(carry, ai, t, B);
        { ulong top = (ulong)t[16] + carry; t[16] = (uint)top; t[17] = (uint)(top >> 32); }
        uint m = (uint)((ulong)t[0] * (ulong)np0);
        carry = asm_red_step0_carry(t[0], m, N[0]);
        carry = asm_mac_pass2_block8_1(carry, m, t, N);
        carry = asm_mac_pass2_block7_9(carry, m, t, N);
        { ulong top = (ulong)t[16] + carry; t[15] = (uint)top; top = (ulong)t[17] + (top >> 32); t[16] = (uint)top; t[17] = (uint)(top >> 32); }
    }
    ulong borrow = 0ul;
    uint D[MONT_OPT2_FIXED_LIMBS];
    { ulong tv = (ulong)t[0]; ulong nv = (ulong)N[0]; ulong w = tv - nv - borrow; D[0] = (uint)w; borrow = (tv < nv + borrow) ? 1ul : 0ul; }
    { ulong tv = (ulong)t[1]; ulong nv = (ulong)N[1]; ulong w = tv - nv - borrow; D[1] = (uint)w; borrow = (tv < nv + borrow) ? 1ul : 0ul; }
    { ulong tv = (ulong)t[2]; ulong nv = (ulong)N[2]; ulong w = tv - nv - borrow; D[2] = (uint)w; borrow = (tv < nv + borrow) ? 1ul : 0ul; }
    { ulong tv = (ulong)t[3]; ulong nv = (ulong)N[3]; ulong w = tv - nv - borrow; D[3] = (uint)w; borrow = (tv < nv + borrow) ? 1ul : 0ul; }
    { ulong tv = (ulong)t[4]; ulong nv = (ulong)N[4]; ulong w = tv - nv - borrow; D[4] = (uint)w; borrow = (tv < nv + borrow) ? 1ul : 0ul; }
    { ulong tv = (ulong)t[5]; ulong nv = (ulong)N[5]; ulong w = tv - nv - borrow; D[5] = (uint)w; borrow = (tv < nv + borrow) ? 1ul : 0ul; }
    { ulong tv = (ulong)t[6]; ulong nv = (ulong)N[6]; ulong w = tv - nv - borrow; D[6] = (uint)w; borrow = (tv < nv + borrow) ? 1ul : 0ul; }
    { ulong tv = (ulong)t[7]; ulong nv = (ulong)N[7]; ulong w = tv - nv - borrow; D[7] = (uint)w; borrow = (tv < nv + borrow) ? 1ul : 0ul; }
    { ulong tv = (ulong)t[8]; ulong nv = (ulong)N[8]; ulong w = tv - nv - borrow; D[8] = (uint)w; borrow = (tv < nv + borrow) ? 1ul : 0ul; }
    { ulong tv = (ulong)t[9]; ulong nv = (ulong)N[9]; ulong w = tv - nv - borrow; D[9] = (uint)w; borrow = (tv < nv + borrow) ? 1ul : 0ul; }
    { ulong tv = (ulong)t[10]; ulong nv = (ulong)N[10]; ulong w = tv - nv - borrow; D[10] = (uint)w; borrow = (tv < nv + borrow) ? 1ul : 0ul; }
    { ulong tv = (ulong)t[11]; ulong nv = (ulong)N[11]; ulong w = tv - nv - borrow; D[11] = (uint)w; borrow = (tv < nv + borrow) ? 1ul : 0ul; }
    { ulong tv = (ulong)t[12]; ulong nv = (ulong)N[12]; ulong w = tv - nv - borrow; D[12] = (uint)w; borrow = (tv < nv + borrow) ? 1ul : 0ul; }
    { ulong tv = (ulong)t[13]; ulong nv = (ulong)N[13]; ulong w = tv - nv - borrow; D[13] = (uint)w; borrow = (tv < nv + borrow) ? 1ul : 0ul; }
    { ulong tv = (ulong)t[14]; ulong nv = (ulong)N[14]; ulong w = tv - nv - borrow; D[14] = (uint)w; borrow = (tv < nv + borrow) ? 1ul : 0ul; }
    { ulong tv = (ulong)t[15]; ulong nv = (ulong)N[15]; ulong w = tv - nv - borrow; D[15] = (uint)w; borrow = (tv < nv + borrow) ? 1ul : 0ul; }
    uint need_sub = (t[MONT_OPT2_FIXED_LIMBS] != 0u || t[MONT_OPT2_FIXED_LIMBS + 1u] != 0u) ? 1u : 0u;
    need_sub = (borrow == 0u) ? 1u : need_sub;
    uint mask = 0u - need_sub;
    out[base + 0] = (D[0] & mask) | (t[0] & ~mask);
    out[base + 1] = (D[1] & mask) | (t[1] & ~mask);
    out[base + 2] = (D[2] & mask) | (t[2] & ~mask);
    out[base + 3] = (D[3] & mask) | (t[3] & ~mask);
    out[base + 4] = (D[4] & mask) | (t[4] & ~mask);
    out[base + 5] = (D[5] & mask) | (t[5] & ~mask);
    out[base + 6] = (D[6] & mask) | (t[6] & ~mask);
    out[base + 7] = (D[7] & mask) | (t[7] & ~mask);
    out[base + 8] = (D[8] & mask) | (t[8] & ~mask);
    out[base + 9] = (D[9] & mask) | (t[9] & ~mask);
    out[base + 10] = (D[10] & mask) | (t[10] & ~mask);
    out[base + 11] = (D[11] & mask) | (t[11] & ~mask);
    out[base + 12] = (D[12] & mask) | (t[12] & ~mask);
    out[base + 13] = (D[13] & mask) | (t[13] & ~mask);
    out[base + 14] = (D[14] & mask) | (t[14] & ~mask);
    out[base + 15] = (D[15] & mask) | (t[15] & ~mask);
}

__kernel void ecm_mont_mul_priv_unroll_only_512_asm_bench(__global const uint *a,
                                                             __global const uint *b,
                                                             __constant uint *n,
                                                             __global uint *out,
                                                             __constant uint *np0_ptr,
                                                             uint limbs, uint iterations) {
    if (limbs != MONT_OPT2_FIXED_LIMBS) {
        return;
    }
    uint gid = get_global_id(0);
    uint base = gid * limbs;
    uint np0 = np0_ptr[0];
    for (uint it = 0u; it < iterations; ++it) {
        if (it == 0u) {
            mont_mul_priv_unroll_only_512_asm_body(out, a, b, n, base, np0);
        } else {
            mont_mul_priv_unroll_only_512_asm_body(out, out, b, n, base, np0);
        }
    }
}

#endif // MONT_MUL_ASM_ENABLE && __AMDGCN__
