// AUTO-GENERATED by tools/gen_mp_addmod_asm_fused.py — do not edit.

#ifndef MP_ADDMOD_ASM_ENABLE
#define MP_ADDMOD_ASM_ENABLE 1
#endif
#ifndef MAX_LIMBS
#define MAX_LIMBS 128
#endif

#if defined(MP_ADDMOD_ASM_ENABLE) && defined(__AMDGCN__)


#if MAX_LIMBS == 8
__kernel void ecm_mp_add_mod_fused_asm8(
    __global const uint *a_g, __global const uint *b_g, __global const uint *n_g,
    __global uint *out, uint limbs)
{
    if (limbs != 8u) return;
    uint base = get_global_id(0) * 8u;
    uint ca = 0u, cs = 1u;
    asm_fused_block8(a_g + base, b_g + base, n_g + base, out + base, ca, cs, &ca, &cs);
}

__kernel void ecm_mp_add_mod_fused_asm8_asmfix(
    __global const uint *a_g, __global const uint *b_g, __global const uint *n_g,
    __global uint *out, uint limbs)
{
    if (limbs != 8u) return;
    uint base = get_global_id(0) * 8u;
    uint ca = 0u, cs = 1u;
    asm_fused_block8_asmfix(a_g + base, b_g + base, n_g + base, out + base, ca, cs, &ca, &cs);
}

__kernel void ecm_mp_add_mod_fused_asm8_vccsoft(
    __global const uint *a_g, __global const uint *b_g, __global const uint *n_g,
    __global uint *out, uint limbs)
{
    if (limbs != 8u) return;
    uint base = get_global_id(0) * 8u;
    mp_add_mod_8_asm_vccsoft(out + base, a_g + base, b_g + base, n_g + base);
}
#endif


#if MAX_LIMBS == 16
__kernel void ecm_mp_add_mod_fused_asm_b16(
    __global const uint *a_g, __global const uint *b_g, __global const uint *n_g,
    __global uint *out, uint limbs)
{
    if (limbs != 16u) return;
    uint base = get_global_id(0) * 16u;
    uint ca = 0u, cs = 1u;
    asm_fused_block16(a_g + base, b_g + base, n_g + base, out + base, ca, cs, &ca, &cs);
}

__kernel void ecm_mp_add_mod_fused_asm_b16_vccsoft(
    __global const uint *a_g, __global const uint *b_g, __global const uint *n_g,
    __global uint *out, uint limbs)
{
    if (limbs != 16u) return;
    uint base = get_global_id(0) * 16u;
    mp_add_mod_16_asm_vccsoft(out + base, a_g + base, b_g + base, n_g + base);
}
#endif


#if MAX_LIMBS == 128
__kernel void ecm_mp_add_mod_fused_unroll_asm(
    __global const uint *a_g, __global const uint *b_g, __global const uint *n_g,
    __global uint *out, uint limbs)
{
    if (limbs != 128u) return;
    uint base = get_global_id(0) * 128u;
    uint ca = 0u, cs = 1u;
    for (uint blk = 0u; blk < 16u; ++blk) {
        uint off = blk * 8u;
        asm_fused_block8(a_g + base + off, b_g + base + off, n_g + base + off,
                         out + base + off, ca, cs, &ca, &cs);
    }
}

__kernel void ecm_mp_add_mod_fused_unroll_asm_b16(
    __global const uint *a_g, __global const uint *b_g, __global const uint *n_g,
    __global uint *out, uint limbs)
{
    if (limbs != 128u) return;
    uint base = get_global_id(0) * 128u;
    uint ca = 0u, cs = 1u;
    for (uint blk = 0u; blk < 8u; ++blk) {
        uint off = blk * 16u;
        asm_fused_block16(a_g + base + off, b_g + base + off, n_g + base + off,
                          out + base + off, ca, cs, &ca, &cs);
    }
}

__kernel void ecm_mp_add_mod_fused_unroll_asm_asmfix(
    __global const uint *a_g, __global const uint *b_g, __global const uint *n_g,
    __global uint *out, uint limbs)
{
    if (limbs != 128u) return;
    uint base = get_global_id(0) * 128u;
    uint ca = 0u, cs = 1u;
    for (uint blk = 0u; blk < 16u; ++blk) {
        uint off = blk * 8u;
        asm_fused_block8_asmfix(a_g + base + off, b_g + base + off, n_g + base + off,
                         out + base + off, ca, cs, &ca, &cs);
    }
}

__kernel void ecm_mp_add_mod_fused_unroll_asm_soft(
    __global const uint *a_g, __global const uint *b_g, __global const uint *n_g,
    __global uint *out, uint limbs)
{
    if (limbs != 128u) return;
    uint base = get_global_id(0) * 128u;
    uint ca = 0u, cs = 1u;
    for (uint blk = 0u; blk < 16u; ++blk) {
        uint off = blk * 8u;
        asm_fused_block8_vccsoft(a_g + base + off, b_g + base + off, n_g + base + off,
                         out + base + off, ca, cs, &ca, &cs);
    }
}

__kernel void ecm_mp_add_mod_fused_unroll_asm_soft_b16(
    __global const uint *a_g, __global const uint *b_g, __global const uint *n_g,
    __global uint *out, uint limbs)
{
    if (limbs != 128u) return;
    uint base = get_global_id(0) * 128u;
    uint ca = 0u, cs = 1u;
    for (uint blk = 0u; blk < 8u; ++blk) {
        uint off = blk * 16u;
        asm_fused_block16_vccsoft(a_g + base + off, b_g + base + off, n_g + base + off,
                                  out + base + off, ca, cs, &ca, &cs);
    }
}

__kernel void ecm_mp_add_mod_fused_unroll_asm_b32(
    __global const uint *a_g, __global const uint *b_g, __global const uint *n_g,
    __global uint *out, uint limbs)
{
    if (limbs != 128u) return;
    uint base = get_global_id(0) * 128u;
    uint ca = 0u, cs = 1u;
    for (uint blk = 0u; blk < 4u; ++blk) {
        uint off = blk * 32u;
        asm_fused_block32(a_g + base + off, b_g + base + off, n_g + base + off,
                          out + base + off, ca, cs, &ca, &cs);
    }
}
#endif

#endif
