// AUTO-GENERATED by tools/gen_mp_addsub_asm_block32_stage1.py - do not edit.
#if defined(ECM_STAGE1_ASM_B32) && defined(__AMDGCN__)



// 32-limb fused add-mod block (private stage1).

static inline void asm_fused_block32_priv(const uint *a, const uint *b,

                                   const uint *n, uint *r, uint ca_in,

                                   uint cs_in, uint *ca_out, uint *cs_out) {

    uint a0 = a[0];
    uint a1 = a[1];
    uint a2 = a[2];
    uint a3 = a[3];
    uint a4 = a[4];
    uint a5 = a[5];
    uint a6 = a[6];
    uint a7 = a[7];
    uint a8 = a[8];
    uint a9 = a[9];
    uint a10 = a[10];
    uint a11 = a[11];
    uint a12 = a[12];
    uint a13 = a[13];
    uint a14 = a[14];
    uint a15 = a[15];
    uint a16 = a[16];
    uint a17 = a[17];
    uint a18 = a[18];
    uint a19 = a[19];
    uint a20 = a[20];
    uint a21 = a[21];
    uint a22 = a[22];
    uint a23 = a[23];
    uint a24 = a[24];
    uint a25 = a[25];
    uint a26 = a[26];
    uint a27 = a[27];
    uint a28 = a[28];
    uint a29 = a[29];
    uint a30 = a[30];
    uint a31 = a[31];
    uint b0 = b[0];
    uint b1 = b[1];
    uint b2 = b[2];
    uint b3 = b[3];
    uint b4 = b[4];
    uint b5 = b[5];
    uint b6 = b[6];
    uint b7 = b[7];
    uint b8 = b[8];
    uint b9 = b[9];
    uint b10 = b[10];
    uint b11 = b[11];
    uint b12 = b[12];
    uint b13 = b[13];
    uint b14 = b[14];
    uint b15 = b[15];
    uint b16 = b[16];
    uint b17 = b[17];
    uint b18 = b[18];
    uint b19 = b[19];
    uint b20 = b[20];
    uint b21 = b[21];
    uint b22 = b[22];
    uint b23 = b[23];
    uint b24 = b[24];
    uint b25 = b[25];
    uint b26 = b[26];
    uint b27 = b[27];
    uint b28 = b[28];
    uint b29 = b[29];
    uint b30 = b[30];
    uint b31 = b[31];
    uint n0 = n[0];
    uint n1 = n[1];
    uint n2 = n[2];
    uint n3 = n[3];
    uint n4 = n[4];
    uint n5 = n[5];
    uint n6 = n[6];
    uint n7 = n[7];
    uint n8 = n[8];
    uint n9 = n[9];
    uint n10 = n[10];
    uint n11 = n[11];
    uint n12 = n[12];
    uint n13 = n[13];
    uint n14 = n[14];
    uint n15 = n[15];
    uint n16 = n[16];
    uint n17 = n[17];
    uint n18 = n[18];
    uint n19 = n[19];
    uint n20 = n[20];
    uint n21 = n[21];
    uint n22 = n[22];
    uint n23 = n[23];
    uint n24 = n[24];
    uint n25 = n[25];
    uint n26 = n[26];
    uint n27 = n[27];
    uint n28 = n[28];
    uint n29 = n[29];
    uint n30 = n[30];
    uint n31 = n[31];
    uint s0, s1, s2, s3, s4, s5, s6, s7, s8, s9, s10, s11, s12, s13, s14, s15, s16, s17, s18, s19, s20, s21, s22, s23, s24, s25, s26, s27, s28, s29, s30, s31;

    uint r0, r1, r2, r3, r4, r5, r6, r7, r8, r9, r10, r11, r12, r13, r14, r15, r16, r17, r18, r19, r20, r21, r22, r23, r24, r25, r26, r27, r28, r29, r30, r31;

    uint n0n, n1n, n2n, n3n, n4n, n5n, n6n, n7n, n8n, n9n, n10n, n11n, n12n, n13n, n14n, n15n, n16n, n17n, n18n, n19n, n20n, n21n, n22n, n23n, n24n, n25n, n26n, n27n, n28n, n29n, n30n, n31n;

    uint ca = 0u, cs = 0u;

    const uint z = 0u, o = 1u;

    uint ca_bit = ca_in ? o : z;

    uint cs_bit = cs_in ? o : z;



    __asm volatile(

        "v_cmp_eq_u32    vcc_lo, %[ca_bit], %[o]\n\t"
        "v_add_co_ci_u32 %[s0], vcc_lo, %[a0], %[b0], vcc_lo\n\t"
        "v_add_co_ci_u32 %[s1], vcc_lo, %[a1], %[b1], vcc_lo\n\t"
        "v_add_co_ci_u32 %[s2], vcc_lo, %[a2], %[b2], vcc_lo\n\t"
        "v_add_co_ci_u32 %[s3], vcc_lo, %[a3], %[b3], vcc_lo\n\t"
        "v_add_co_ci_u32 %[s4], vcc_lo, %[a4], %[b4], vcc_lo\n\t"
        "v_add_co_ci_u32 %[s5], vcc_lo, %[a5], %[b5], vcc_lo\n\t"
        "v_add_co_ci_u32 %[s6], vcc_lo, %[a6], %[b6], vcc_lo\n\t"
        "v_add_co_ci_u32 %[s7], vcc_lo, %[a7], %[b7], vcc_lo\n\t"
        "v_add_co_ci_u32 %[s8], vcc_lo, %[a8], %[b8], vcc_lo\n\t"
        "v_add_co_ci_u32 %[s9], vcc_lo, %[a9], %[b9], vcc_lo\n\t"
        "v_add_co_ci_u32 %[s10], vcc_lo, %[a10], %[b10], vcc_lo\n\t"
        "v_add_co_ci_u32 %[s11], vcc_lo, %[a11], %[b11], vcc_lo\n\t"
        "v_add_co_ci_u32 %[s12], vcc_lo, %[a12], %[b12], vcc_lo\n\t"
        "v_add_co_ci_u32 %[s13], vcc_lo, %[a13], %[b13], vcc_lo\n\t"
        "v_add_co_ci_u32 %[s14], vcc_lo, %[a14], %[b14], vcc_lo\n\t"
        "v_add_co_ci_u32 %[s15], vcc_lo, %[a15], %[b15], vcc_lo\n\t"
        "v_add_co_ci_u32 %[s16], vcc_lo, %[a16], %[b16], vcc_lo\n\t"
        "v_add_co_ci_u32 %[s17], vcc_lo, %[a17], %[b17], vcc_lo\n\t"
        "v_add_co_ci_u32 %[s18], vcc_lo, %[a18], %[b18], vcc_lo\n\t"
        "v_add_co_ci_u32 %[s19], vcc_lo, %[a19], %[b19], vcc_lo\n\t"
        "v_add_co_ci_u32 %[s20], vcc_lo, %[a20], %[b20], vcc_lo\n\t"
        "v_add_co_ci_u32 %[s21], vcc_lo, %[a21], %[b21], vcc_lo\n\t"
        "v_add_co_ci_u32 %[s22], vcc_lo, %[a22], %[b22], vcc_lo\n\t"
        "v_add_co_ci_u32 %[s23], vcc_lo, %[a23], %[b23], vcc_lo\n\t"
        "v_add_co_ci_u32 %[s24], vcc_lo, %[a24], %[b24], vcc_lo\n\t"
        "v_add_co_ci_u32 %[s25], vcc_lo, %[a25], %[b25], vcc_lo\n\t"
        "v_add_co_ci_u32 %[s26], vcc_lo, %[a26], %[b26], vcc_lo\n\t"
        "v_add_co_ci_u32 %[s27], vcc_lo, %[a27], %[b27], vcc_lo\n\t"
        "v_add_co_ci_u32 %[s28], vcc_lo, %[a28], %[b28], vcc_lo\n\t"
        "v_add_co_ci_u32 %[s29], vcc_lo, %[a29], %[b29], vcc_lo\n\t"
        "v_add_co_ci_u32 %[s30], vcc_lo, %[a30], %[b30], vcc_lo\n\t"
        "v_add_co_ci_u32 %[s31], vcc_lo, %[a31], %[b31], vcc_lo\n\t"
        "v_cndmask_b32   %[ca], %[z], %[o], vcc_lo\n\t"
        "v_not_b32       %[n0n], %[n0]\n\t"
        "v_not_b32       %[n1n], %[n1]\n\t"
        "v_not_b32       %[n2n], %[n2]\n\t"
        "v_not_b32       %[n3n], %[n3]\n\t"
        "v_not_b32       %[n4n], %[n4]\n\t"
        "v_not_b32       %[n5n], %[n5]\n\t"
        "v_not_b32       %[n6n], %[n6]\n\t"
        "v_not_b32       %[n7n], %[n7]\n\t"
        "v_not_b32       %[n8n], %[n8]\n\t"
        "v_not_b32       %[n9n], %[n9]\n\t"
        "v_not_b32       %[n10n], %[n10]\n\t"
        "v_not_b32       %[n11n], %[n11]\n\t"
        "v_not_b32       %[n12n], %[n12]\n\t"
        "v_not_b32       %[n13n], %[n13]\n\t"
        "v_not_b32       %[n14n], %[n14]\n\t"
        "v_not_b32       %[n15n], %[n15]\n\t"
        "v_not_b32       %[n16n], %[n16]\n\t"
        "v_not_b32       %[n17n], %[n17]\n\t"
        "v_not_b32       %[n18n], %[n18]\n\t"
        "v_not_b32       %[n19n], %[n19]\n\t"
        "v_not_b32       %[n20n], %[n20]\n\t"
        "v_not_b32       %[n21n], %[n21]\n\t"
        "v_not_b32       %[n22n], %[n22]\n\t"
        "v_not_b32       %[n23n], %[n23]\n\t"
        "v_not_b32       %[n24n], %[n24]\n\t"
        "v_not_b32       %[n25n], %[n25]\n\t"
        "v_not_b32       %[n26n], %[n26]\n\t"
        "v_not_b32       %[n27n], %[n27]\n\t"
        "v_not_b32       %[n28n], %[n28]\n\t"
        "v_not_b32       %[n29n], %[n29]\n\t"
        "v_not_b32       %[n30n], %[n30]\n\t"
        "v_not_b32       %[n31n], %[n31]\n\t"
        "v_cmp_eq_u32    vcc_lo, %[cs_bit], %[o]\n\t"
        "v_add_co_ci_u32 %[r0], vcc_lo, %[s0], %[n0n], vcc_lo\n\t"
        "v_add_co_ci_u32 %[r1], vcc_lo, %[s1], %[n1n], vcc_lo\n\t"
        "v_add_co_ci_u32 %[r2], vcc_lo, %[s2], %[n2n], vcc_lo\n\t"
        "v_add_co_ci_u32 %[r3], vcc_lo, %[s3], %[n3n], vcc_lo\n\t"
        "v_add_co_ci_u32 %[r4], vcc_lo, %[s4], %[n4n], vcc_lo\n\t"
        "v_add_co_ci_u32 %[r5], vcc_lo, %[s5], %[n5n], vcc_lo\n\t"
        "v_add_co_ci_u32 %[r6], vcc_lo, %[s6], %[n6n], vcc_lo\n\t"
        "v_add_co_ci_u32 %[r7], vcc_lo, %[s7], %[n7n], vcc_lo\n\t"
        "v_add_co_ci_u32 %[r8], vcc_lo, %[s8], %[n8n], vcc_lo\n\t"
        "v_add_co_ci_u32 %[r9], vcc_lo, %[s9], %[n9n], vcc_lo\n\t"
        "v_add_co_ci_u32 %[r10], vcc_lo, %[s10], %[n10n], vcc_lo\n\t"
        "v_add_co_ci_u32 %[r11], vcc_lo, %[s11], %[n11n], vcc_lo\n\t"
        "v_add_co_ci_u32 %[r12], vcc_lo, %[s12], %[n12n], vcc_lo\n\t"
        "v_add_co_ci_u32 %[r13], vcc_lo, %[s13], %[n13n], vcc_lo\n\t"
        "v_add_co_ci_u32 %[r14], vcc_lo, %[s14], %[n14n], vcc_lo\n\t"
        "v_add_co_ci_u32 %[r15], vcc_lo, %[s15], %[n15n], vcc_lo\n\t"
        "v_add_co_ci_u32 %[r16], vcc_lo, %[s16], %[n16n], vcc_lo\n\t"
        "v_add_co_ci_u32 %[r17], vcc_lo, %[s17], %[n17n], vcc_lo\n\t"
        "v_add_co_ci_u32 %[r18], vcc_lo, %[s18], %[n18n], vcc_lo\n\t"
        "v_add_co_ci_u32 %[r19], vcc_lo, %[s19], %[n19n], vcc_lo\n\t"
        "v_add_co_ci_u32 %[r20], vcc_lo, %[s20], %[n20n], vcc_lo\n\t"
        "v_add_co_ci_u32 %[r21], vcc_lo, %[s21], %[n21n], vcc_lo\n\t"
        "v_add_co_ci_u32 %[r22], vcc_lo, %[s22], %[n22n], vcc_lo\n\t"
        "v_add_co_ci_u32 %[r23], vcc_lo, %[s23], %[n23n], vcc_lo\n\t"
        "v_add_co_ci_u32 %[r24], vcc_lo, %[s24], %[n24n], vcc_lo\n\t"
        "v_add_co_ci_u32 %[r25], vcc_lo, %[s25], %[n25n], vcc_lo\n\t"
        "v_add_co_ci_u32 %[r26], vcc_lo, %[s26], %[n26n], vcc_lo\n\t"
        "v_add_co_ci_u32 %[r27], vcc_lo, %[s27], %[n27n], vcc_lo\n\t"
        "v_add_co_ci_u32 %[r28], vcc_lo, %[s28], %[n28n], vcc_lo\n\t"
        "v_add_co_ci_u32 %[r29], vcc_lo, %[s29], %[n29n], vcc_lo\n\t"
        "v_add_co_ci_u32 %[r30], vcc_lo, %[s30], %[n30n], vcc_lo\n\t"
        "v_add_co_ci_u32 %[r31], vcc_lo, %[s31], %[n31n], vcc_lo\n\t"
        "v_cndmask_b32   %[cs], %[z], %[o], vcc_lo"

        : [s0] "=&v"(s0), [s1] "=&v"(s1), [s2] "=&v"(s2), [s3] "=&v"(s3), [s4] "=&v"(s4), [s5] "=&v"(s5), [s6] "=&v"(s6), [s7] "=&v"(s7), [s8] "=&v"(s8), [s9] "=&v"(s9), [s10] "=&v"(s10), [s11] "=&v"(s11), [s12] "=&v"(s12), [s13] "=&v"(s13), [s14] "=&v"(s14), [s15] "=&v"(s15), [s16] "=&v"(s16), [s17] "=&v"(s17), [s18] "=&v"(s18), [s19] "=&v"(s19), [s20] "=&v"(s20), [s21] "=&v"(s21), [s22] "=&v"(s22), [s23] "=&v"(s23), [s24] "=&v"(s24), [s25] "=&v"(s25), [s26] "=&v"(s26), [s27] "=&v"(s27), [s28] "=&v"(s28), [s29] "=&v"(s29), [s30] "=&v"(s30), [s31] "=&v"(s31),

          [r0] "=&v"(r0), [r1] "=&v"(r1), [r2] "=&v"(r2), [r3] "=&v"(r3), [r4] "=&v"(r4), [r5] "=&v"(r5), [r6] "=&v"(r6), [r7] "=&v"(r7), [r8] "=&v"(r8), [r9] "=&v"(r9), [r10] "=&v"(r10), [r11] "=&v"(r11), [r12] "=&v"(r12), [r13] "=&v"(r13), [r14] "=&v"(r14), [r15] "=&v"(r15), [r16] "=&v"(r16), [r17] "=&v"(r17), [r18] "=&v"(r18), [r19] "=&v"(r19), [r20] "=&v"(r20), [r21] "=&v"(r21), [r22] "=&v"(r22), [r23] "=&v"(r23), [r24] "=&v"(r24), [r25] "=&v"(r25), [r26] "=&v"(r26), [r27] "=&v"(r27), [r28] "=&v"(r28), [r29] "=&v"(r29), [r30] "=&v"(r30), [r31] "=&v"(r31),

          [n0n] "=&v"(n0n), [n1n] "=&v"(n1n), [n2n] "=&v"(n2n), [n3n] "=&v"(n3n), [n4n] "=&v"(n4n), [n5n] "=&v"(n5n), [n6n] "=&v"(n6n), [n7n] "=&v"(n7n), [n8n] "=&v"(n8n), [n9n] "=&v"(n9n), [n10n] "=&v"(n10n), [n11n] "=&v"(n11n), [n12n] "=&v"(n12n), [n13n] "=&v"(n13n), [n14n] "=&v"(n14n), [n15n] "=&v"(n15n), [n16n] "=&v"(n16n), [n17n] "=&v"(n17n), [n18n] "=&v"(n18n), [n19n] "=&v"(n19n), [n20n] "=&v"(n20n), [n21n] "=&v"(n21n), [n22n] "=&v"(n22n), [n23n] "=&v"(n23n), [n24n] "=&v"(n24n), [n25n] "=&v"(n25n), [n26n] "=&v"(n26n), [n27n] "=&v"(n27n), [n28n] "=&v"(n28n), [n29n] "=&v"(n29n), [n30n] "=&v"(n30n), [n31n] "=&v"(n31n),

          [ca] "=&v"(ca), [cs] "=&v"(cs)

        : [a0] "v"(a0), [b0] "v"(b0), [a1] "v"(a1), [b1] "v"(b1), [a2] "v"(a2), [b2] "v"(b2), [a3] "v"(a3), [b3] "v"(b3), [a4] "v"(a4), [b4] "v"(b4), [a5] "v"(a5), [b5] "v"(b5), [a6] "v"(a6), [b6] "v"(b6), [a7] "v"(a7), [b7] "v"(b7), [a8] "v"(a8), [b8] "v"(b8), [a9] "v"(a9), [b9] "v"(b9), [a10] "v"(a10), [b10] "v"(b10), [a11] "v"(a11), [b11] "v"(b11), [a12] "v"(a12), [b12] "v"(b12), [a13] "v"(a13), [b13] "v"(b13), [a14] "v"(a14), [b14] "v"(b14), [a15] "v"(a15), [b15] "v"(b15), [a16] "v"(a16), [b16] "v"(b16), [a17] "v"(a17), [b17] "v"(b17), [a18] "v"(a18), [b18] "v"(b18), [a19] "v"(a19), [b19] "v"(b19), [a20] "v"(a20), [b20] "v"(b20), [a21] "v"(a21), [b21] "v"(b21), [a22] "v"(a22), [b22] "v"(b22), [a23] "v"(a23), [b23] "v"(b23), [a24] "v"(a24), [b24] "v"(b24), [a25] "v"(a25), [b25] "v"(b25), [a26] "v"(a26), [b26] "v"(b26), [a27] "v"(a27), [b27] "v"(b27), [a28] "v"(a28), [b28] "v"(b28), [a29] "v"(a29), [b29] "v"(b29), [a30] "v"(a30), [b30] "v"(b30), [a31] "v"(a31), [b31] "v"(b31),

          [n0] "v"(n0), [n1] "v"(n1), [n2] "v"(n2), [n3] "v"(n3), [n4] "v"(n4), [n5] "v"(n5), [n6] "v"(n6), [n7] "v"(n7), [n8] "v"(n8), [n9] "v"(n9), [n10] "v"(n10), [n11] "v"(n11), [n12] "v"(n12), [n13] "v"(n13), [n14] "v"(n14), [n15] "v"(n15), [n16] "v"(n16), [n17] "v"(n17), [n18] "v"(n18), [n19] "v"(n19), [n20] "v"(n20), [n21] "v"(n21), [n22] "v"(n22), [n23] "v"(n23), [n24] "v"(n24), [n25] "v"(n25), [n26] "v"(n26), [n27] "v"(n27), [n28] "v"(n28), [n29] "v"(n29), [n30] "v"(n30), [n31] "v"(n31),

          [ca_bit] "v"(ca_bit), [cs_bit] "v"(cs_bit), [z] "v"(z), [o] "v"(o)

        : "vcc_lo");



    r[0] = r0;
    r[1] = r1;
    r[2] = r2;
    r[3] = r3;
    r[4] = r4;
    r[5] = r5;
    r[6] = r6;
    r[7] = r7;
    r[8] = r8;
    r[9] = r9;
    r[10] = r10;
    r[11] = r11;
    r[12] = r12;
    r[13] = r13;
    r[14] = r14;
    r[15] = r15;
    r[16] = r16;
    r[17] = r17;
    r[18] = r18;
    r[19] = r19;
    r[20] = r20;
    r[21] = r21;
    r[22] = r22;
    r[23] = r23;
    r[24] = r24;
    r[25] = r25;
    r[26] = r26;
    r[27] = r27;
    r[28] = r28;
    r[29] = r29;
    r[30] = r30;
    r[31] = r31;
    *ca_out = ca;

    *cs_out = cs;

}



// 32-limb fused sub-mod block (private stage1).

static inline void asm_sub_fused_block32_priv(const uint *a, const uint *b,

                                        const uint *n, uint *r, uint br_in,

                                        uint *br_out) {

    uint a0 = a[0];
    uint a1 = a[1];
    uint a2 = a[2];
    uint a3 = a[3];
    uint a4 = a[4];
    uint a5 = a[5];
    uint a6 = a[6];
    uint a7 = a[7];
    uint a8 = a[8];
    uint a9 = a[9];
    uint a10 = a[10];
    uint a11 = a[11];
    uint a12 = a[12];
    uint a13 = a[13];
    uint a14 = a[14];
    uint a15 = a[15];
    uint a16 = a[16];
    uint a17 = a[17];
    uint a18 = a[18];
    uint a19 = a[19];
    uint a20 = a[20];
    uint a21 = a[21];
    uint a22 = a[22];
    uint a23 = a[23];
    uint a24 = a[24];
    uint a25 = a[25];
    uint a26 = a[26];
    uint a27 = a[27];
    uint a28 = a[28];
    uint a29 = a[29];
    uint a30 = a[30];
    uint a31 = a[31];
    uint b0 = b[0];
    uint b1 = b[1];
    uint b2 = b[2];
    uint b3 = b[3];
    uint b4 = b[4];
    uint b5 = b[5];
    uint b6 = b[6];
    uint b7 = b[7];
    uint b8 = b[8];
    uint b9 = b[9];
    uint b10 = b[10];
    uint b11 = b[11];
    uint b12 = b[12];
    uint b13 = b[13];
    uint b14 = b[14];
    uint b15 = b[15];
    uint b16 = b[16];
    uint b17 = b[17];
    uint b18 = b[18];
    uint b19 = b[19];
    uint b20 = b[20];
    uint b21 = b[21];
    uint b22 = b[22];
    uint b23 = b[23];
    uint b24 = b[24];
    uint b25 = b[25];
    uint b26 = b[26];
    uint b27 = b[27];
    uint b28 = b[28];
    uint b29 = b[29];
    uint b30 = b[30];
    uint b31 = b[31];
    uint n0 = n[0];
    uint n1 = n[1];
    uint n2 = n[2];
    uint n3 = n[3];
    uint n4 = n[4];
    uint n5 = n[5];
    uint n6 = n[6];
    uint n7 = n[7];
    uint n8 = n[8];
    uint n9 = n[9];
    uint n10 = n[10];
    uint n11 = n[11];
    uint n12 = n[12];
    uint n13 = n[13];
    uint n14 = n[14];
    uint n15 = n[15];
    uint n16 = n[16];
    uint n17 = n[17];
    uint n18 = n[18];
    uint n19 = n[19];
    uint n20 = n[20];
    uint n21 = n[21];
    uint n22 = n[22];
    uint n23 = n[23];
    uint n24 = n[24];
    uint n25 = n[25];
    uint n26 = n[26];
    uint n27 = n[27];
    uint n28 = n[28];
    uint n29 = n[29];
    uint n30 = n[30];
    uint n31 = n[31];
    uint r0, r1, r2, r3, r4, r5, r6, r7, r8, r9, r10, r11, r12, r13, r14, r15, r16, r17, r18, r19, r20, r21, r22, r23, r24, r25, r26, r27, r28, r29, r30, r31;

    uint br = 0u;

    const uint z = 0u, o = 1u;

    uint br_bit = br_in ? o : z;



    __asm volatile(

        "v_cmp_eq_u32    vcc_lo, %[br_bit], %[o]\n\t"
        "v_sub_co_ci_u32 %[r0], vcc_lo, %[a0], %[b0], vcc_lo\n\t"
        "v_sub_co_ci_u32 %[r1], vcc_lo, %[a1], %[b1], vcc_lo\n\t"
        "v_sub_co_ci_u32 %[r2], vcc_lo, %[a2], %[b2], vcc_lo\n\t"
        "v_sub_co_ci_u32 %[r3], vcc_lo, %[a3], %[b3], vcc_lo\n\t"
        "v_sub_co_ci_u32 %[r4], vcc_lo, %[a4], %[b4], vcc_lo\n\t"
        "v_sub_co_ci_u32 %[r5], vcc_lo, %[a5], %[b5], vcc_lo\n\t"
        "v_sub_co_ci_u32 %[r6], vcc_lo, %[a6], %[b6], vcc_lo\n\t"
        "v_sub_co_ci_u32 %[r7], vcc_lo, %[a7], %[b7], vcc_lo\n\t"
        "v_sub_co_ci_u32 %[r8], vcc_lo, %[a8], %[b8], vcc_lo\n\t"
        "v_sub_co_ci_u32 %[r9], vcc_lo, %[a9], %[b9], vcc_lo\n\t"
        "v_sub_co_ci_u32 %[r10], vcc_lo, %[a10], %[b10], vcc_lo\n\t"
        "v_sub_co_ci_u32 %[r11], vcc_lo, %[a11], %[b11], vcc_lo\n\t"
        "v_sub_co_ci_u32 %[r12], vcc_lo, %[a12], %[b12], vcc_lo\n\t"
        "v_sub_co_ci_u32 %[r13], vcc_lo, %[a13], %[b13], vcc_lo\n\t"
        "v_sub_co_ci_u32 %[r14], vcc_lo, %[a14], %[b14], vcc_lo\n\t"
        "v_sub_co_ci_u32 %[r15], vcc_lo, %[a15], %[b15], vcc_lo\n\t"
        "v_sub_co_ci_u32 %[r16], vcc_lo, %[a16], %[b16], vcc_lo\n\t"
        "v_sub_co_ci_u32 %[r17], vcc_lo, %[a17], %[b17], vcc_lo\n\t"
        "v_sub_co_ci_u32 %[r18], vcc_lo, %[a18], %[b18], vcc_lo\n\t"
        "v_sub_co_ci_u32 %[r19], vcc_lo, %[a19], %[b19], vcc_lo\n\t"
        "v_sub_co_ci_u32 %[r20], vcc_lo, %[a20], %[b20], vcc_lo\n\t"
        "v_sub_co_ci_u32 %[r21], vcc_lo, %[a21], %[b21], vcc_lo\n\t"
        "v_sub_co_ci_u32 %[r22], vcc_lo, %[a22], %[b22], vcc_lo\n\t"
        "v_sub_co_ci_u32 %[r23], vcc_lo, %[a23], %[b23], vcc_lo\n\t"
        "v_sub_co_ci_u32 %[r24], vcc_lo, %[a24], %[b24], vcc_lo\n\t"
        "v_sub_co_ci_u32 %[r25], vcc_lo, %[a25], %[b25], vcc_lo\n\t"
        "v_sub_co_ci_u32 %[r26], vcc_lo, %[a26], %[b26], vcc_lo\n\t"
        "v_sub_co_ci_u32 %[r27], vcc_lo, %[a27], %[b27], vcc_lo\n\t"
        "v_sub_co_ci_u32 %[r28], vcc_lo, %[a28], %[b28], vcc_lo\n\t"
        "v_sub_co_ci_u32 %[r29], vcc_lo, %[a29], %[b29], vcc_lo\n\t"
        "v_sub_co_ci_u32 %[r30], vcc_lo, %[a30], %[b30], vcc_lo\n\t"
        "v_sub_co_ci_u32 %[r31], vcc_lo, %[a31], %[b31], vcc_lo\n\t"
        "v_cndmask_b32   %[br], %[z], %[o], vcc_lo"

        : [r0] "=&v"(r0), [r1] "=&v"(r1), [r2] "=&v"(r2), [r3] "=&v"(r3), [r4] "=&v"(r4), [r5] "=&v"(r5), [r6] "=&v"(r6), [r7] "=&v"(r7), [r8] "=&v"(r8), [r9] "=&v"(r9), [r10] "=&v"(r10), [r11] "=&v"(r11), [r12] "=&v"(r12), [r13] "=&v"(r13), [r14] "=&v"(r14), [r15] "=&v"(r15), [r16] "=&v"(r16), [r17] "=&v"(r17), [r18] "=&v"(r18), [r19] "=&v"(r19), [r20] "=&v"(r20), [r21] "=&v"(r21), [r22] "=&v"(r22), [r23] "=&v"(r23), [r24] "=&v"(r24), [r25] "=&v"(r25), [r26] "=&v"(r26), [r27] "=&v"(r27), [r28] "=&v"(r28), [r29] "=&v"(r29), [r30] "=&v"(r30), [r31] "=&v"(r31),

          [br] "=&v"(br)

        : [a0] "v"(a0), [b0] "v"(b0), [a1] "v"(a1), [b1] "v"(b1), [a2] "v"(a2), [b2] "v"(b2), [a3] "v"(a3), [b3] "v"(b3), [a4] "v"(a4), [b4] "v"(b4), [a5] "v"(a5), [b5] "v"(b5), [a6] "v"(a6), [b6] "v"(b6), [a7] "v"(a7), [b7] "v"(b7), [a8] "v"(a8), [b8] "v"(b8), [a9] "v"(a9), [b9] "v"(b9), [a10] "v"(a10), [b10] "v"(b10), [a11] "v"(a11), [b11] "v"(b11), [a12] "v"(a12), [b12] "v"(b12), [a13] "v"(a13), [b13] "v"(b13), [a14] "v"(a14), [b14] "v"(b14), [a15] "v"(a15), [b15] "v"(b15), [a16] "v"(a16), [b16] "v"(b16), [a17] "v"(a17), [b17] "v"(b17), [a18] "v"(a18), [b18] "v"(b18), [a19] "v"(a19), [b19] "v"(b19), [a20] "v"(a20), [b20] "v"(b20), [a21] "v"(a21), [b21] "v"(b21), [a22] "v"(a22), [b22] "v"(b22), [a23] "v"(a23), [b23] "v"(b23), [a24] "v"(a24), [b24] "v"(b24), [a25] "v"(a25), [b25] "v"(b25), [a26] "v"(a26), [b26] "v"(b26), [a27] "v"(a27), [b27] "v"(b27), [a28] "v"(a28), [b28] "v"(b28), [a29] "v"(a29), [b29] "v"(b29), [a30] "v"(a30), [b30] "v"(b30), [a31] "v"(a31), [b31] "v"(b31),

          [br_bit] "v"(br_bit), [z] "v"(z), [o] "v"(o)

        : "vcc_lo");



    r[0] = r0;
    r[1] = r1;
    r[2] = r2;
    r[3] = r3;
    r[4] = r4;
    r[5] = r5;
    r[6] = r6;
    r[7] = r7;
    r[8] = r8;
    r[9] = r9;
    r[10] = r10;
    r[11] = r11;
    r[12] = r12;
    r[13] = r13;
    r[14] = r14;
    r[15] = r15;
    r[16] = r16;
    r[17] = r17;
    r[18] = r18;
    r[19] = r19;
    r[20] = r20;
    r[21] = r21;
    r[22] = r22;
    r[23] = r23;
    r[24] = r24;
    r[25] = r25;
    r[26] = r26;
    r[27] = r27;
    r[28] = r28;
    r[29] = r29;
    r[30] = r30;
    r[31] = r31;
    *br_out = br;

}

#endif
