// AUTO-GENERATED by tools/gen_mp_submod_asm_fused.py — do not edit.



#ifndef MP_ADDMOD_ASM_ENABLE

#define MP_ADDMOD_ASM_ENABLE 1

#endif

#ifndef MAX_LIMBS

#define MAX_LIMBS 128

#endif



#if defined(MP_ADDMOD_ASM_ENABLE) && defined(__AMDGCN__)





#if MAX_LIMBS == 128

__kernel void ecm_mp_sub_mod_fused_unroll_asm_b32(

    __global const uint *a_g, __global const uint *b_g, __global const uint *n_g,

    __global uint *out, uint limbs)

{

    if (limbs != 128u) return;

    uint base = get_global_id(0) * 128u;

    uint br = 0u;

    for (uint blk = 0u; blk < 4u; ++blk) {

        uint off = blk * 32u;

        asm_sub_fused_block32(a_g + base + off, b_g + base + off, n_g + base + off,

                              out + base + off, br, &br);

    }

}



#if MP_ADDMOD_ASM_B64

__kernel void ecm_mp_sub_mod_fused_unroll_asm_b64(

    __global const uint *a_g, __global const uint *b_g, __global const uint *n_g,

    __global uint *out, uint limbs)

{

    if (limbs != 128u) return;

    uint base = get_global_id(0) * 128u;

    uint br = 0u;

    for (uint blk = 0u; blk < 2u; ++blk) {

        uint off = blk * 64u;

        asm_sub_fused_block64(a_g + base + off, b_g + base + off, n_g + base + off,

                              out + base + off, br, &br);

    }

}

#endif

#endif



#endif
